.travis.yml
This is the recommended CI approach (see https://github.com/Homebrew/brew/pull/1277#issuecomment-253725994).
Use `--fast` since gazebo takes too long to build.
=> .travis.yml: switch to test-bot --fast

gazebo8.rb, qwt-qt4.rb
=> qwt-qt4: temporary formula

ignition-common.rb
Patches for compilation [have been submitted to upstream](https://bitbucket.org/ignitionrobotics/ign-common/pull-requests/13)
=> New formulae for ign-common

simbody.rb
=> simbody: el_capitan bottle

gazebo5.rb, gazebo6.rb, gazebo7.rb, ogre.rb, ogre1.9.rb, sdformat.rb, sdformat3.rb, sdformat4.rb
Formulae that have el_capitan bottles
=> Bump revision for boost 1.63 bottles

ogre1.9.rb
=> fix find ogre cmake

gazebo5.rb, gazebo6.rb
gazebo without bottles (1-4, 8) updated in b24f3e5f9304facffe801b25f5538a599787aa81
gazebo7 to be done separately since it uses webkit
=> gazebo[56]: depend on qt4-no-webkit

gazebo8.rb
=> gazebo8: help find qwt in brew prefix

ignition-rndf.rb
=> New ignition-rndf formula (take II)

gazebo7.rb, gazebo8.rb, ignition-common.rb
noticed by this build failure:
* https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/561
=> bump revisions due to new tinyxml2

ignition-common.rb
Generate a snapshot of ignition-common that is able to build gazebo_experimental
=> New snapshot of ignition-common: 0.4.0-20170720-2071c29

gazebo7.rb, ogre.rb, sdformat4.rb
This is a subset of #266 since gazebo8 is not building due to https://github.com/Homebrew/homebrew-test-bot/issues/115
=> bump revisions for gazebo7 and deps for boost 1.65

.travis.yml
wait to merge this until we have a high sierra build machine
=> travis.yml: prepare for high sierra

Aliases/ignition-transport4, ignition-transport4.rb
=> Ignition Transport 4 formula

ignition-msgs1.rb
This is the latest commit from the ign-cmake pull request:
https://bitbucket.org/ignitionrobotics/ign-msgs/pull-requests/40/use-ignition-cmake/diff
=> ignition-msgs1: latest 0.9.9

gazebo8.rb, ignition-msgs0.rb, ignition-transport3.rb
as soon as https://github.com/Homebrew/homebrew-core/pull/20606 is merged
=> protobuf 3.5: bump gazebo8, deps

gazebo7.rb, ignition-transport.rb
as soon as https://github.com/Homebrew/homebrew-core/pull/20606 is merged
=> protobuf 3.5: bump gazebo7, ign-transport

Aliases/ignition-fuel-tools, ignition-fuel-tools0.rb
I used the tarball from this jenkins build:
* https://build.osrfoundation.org/job/generic-release-homebrew_pull_request_updater/194/parameters/
I patched two problems and submitted a PR upstreadm:
* https://bitbucket.org/ignitionrobotics/ign-fuel-tools/pull-requests/26/fix-mac-build/commits
=> ignition-fuel-tools: new formula

gazebo7.rb
This will give audio support in bottles and work around some upstream homebrew problems.
=> gazebo7: make ffmpeg recommended dep

ignition-fuel-tools1.rb
there was a new lib zip in https://github.com/Homebrew/homebrew-core/pull/23603
=> fuel-tools1: bump revision for libzip

gazebo9.rb
=> gazebo9: patch for find dart in cmake config

gazebo9.rb
Bumping revision to rebuild the bottle because dartsim version was bumped from  6.3 to 6.4
=> Bump revision on gazebo9 formula

ignition-cmake1.rb
from https://bitbucket.org/ignitionrobotics/ign-cmake/pull-requests/56
=> ignition-cmake1: use commit with pkg-config fix

Aliases/ignition-msgs2, Aliases/ignition-msgs@2, ignition-msgs2.rb
Use math5 and cmake1 with msgs2
=> Msgs2 math5 cmake1

Aliases/ignition-common2, Aliases/ignition-common@2, ignition-common2.rb
needed for https://bitbucket.org/ignitionrobotics/ign-common/pull-requests/109/components-part-6-use-ign-cmake1-and/diff
=> ignition-common2: new, use ign-cmake1, ign-math5

gazebo7.rb, gazebo8.rb, gazebo9.rb, ignition-common1.rb, ignition-fuel-tools1.rb
=> ignition-common1: patch for ffmpeg4

ignition-rendering0.rb
companion to https://bitbucket.org/ignitionrobotics/ign-rendering/pull-requests/58/update-to-use-ign-common2-and-ign-math5/commits
=> ignition-rendering0: use common2, math5

ignition-msgs3.rb
do this separately since it supports different platforms
=> bump msgs3 revision for protobuf3

ignition-msgs0.rb, ignition-msgs1.rb, ignition-transport.rb, ignition-transport3.rb, ignition-transport4.rb
build bottles when https://github.com/Homebrew/homebrew-core/pull/29239 is merged
=> bump formula revisions for protobuf 3.6

ogre2.1.rb
=> ogre2.1: don't try to add plugin lib symlinks

Aliases/ignition-plugin, Aliases/ignition-plugin@0, ignition-plugin0.rb
This will be first used by ignition-physics.
The commit is from the following pull request:
* https://bitbucket.org/ignitionrobotics/ign-plugin/pull-requests/2/part-3-better-plugin-registration-and/diff
=> ignition-plugin0: new formula

gazebo9.rb
need to start bottle builds for this
=> gazebo9: bump revision for dart 6.6

ignition-plugin0.rb
I think I also need to update hashes....
=> Update plugin to use ign-cmak2

Aliases/ignition-gui1, Aliases/ignition-gui@1, ignition-gui0.rb
Needed for gz11 branch: https://build.osrfoundation.org/job/ignition_gui-ci-gz11-homebrew-amd64/1/console
=> Add ignition-gui@1 alias

Formula/gazebo7.rb, Formula/gazebo8.rb
=> gazebo[7-8]: depend on graphviz, bump revision.

Formula/ignition-gazebo0.rb
A commit from the following pull request:
* https://bitbucket.org/ignitionrobotics/ign-gazebo/pull-requests/100/new-mechanism-for-updating-the-value-of/commits
=> ignition-gazebo0: new commit to fix bottle

Aliases/ignition-plugin, Formula/ignition-plugin1.rb
point ignition-plugin alias to ignition-plugin1
replacement for #581
=> ignition-plugin1 1.0.0

Formula/ignition-msgs3.rb, Formula/sdformat8.rb
Needed by [this ign-gazebo PR](https://bitbucket.org/ignitionrobotics/ign-gazebo/pull-requests/143/a-6-user-command-spawn-factory-create/diff)
=> sdformat8: update commit

Formula/ignition-msgs3.rb
This is part of https://github.com/osrf/homebrew-simulation/pull/583/files
=> ignition-msgs3: update commit

Formula/ignition-gazebo0.rb, Formula/ignition-sensors1.rb
disable ignition-gazebo0 bottle
=> ignition-sensors1: add cmake test

Formula/ignition-launch0.rb
Since we lack of any prerelease, not sure what to set as url for the code. @scpeters I think that we need to wait until merging the current PRs in launch and select the newest commit in the repo, is this right?
=> ignition-launch0 initial version

Formula/ignition-rendering2.rb, Formula/ignition-sensors2.rb
Also make small updates to the tests.
=> ignition-rendering2/sensors2: build bottles

Formula/ignition-acropolis.rb
We should find a good test for the formula
=> Add ignition-acropolis formula

Formula/ignition-gazebo2.rb
[ign-gazebo PR](https://bitbucket.org/ignitionrobotics/ign-gazebo/pull-requests/259/blueprint-use-ign-gui2/diff)
=> ign-gazebo2 use ign-gui2

Formula/ignition-gazebo2.rb, Formula/ignition-physics1.rb
Ref: https://formulae.brew.sh/formula/google-benchmark
=> ign-gazebo/physics: use google-benchmark

Formula/simbody.rb
Similar to #677 and partial fix to #676.
Fixes #519.
=> simbody: test and replace Xcode paths

Formula/ignition-rendering1.rb, Formula/ignition-rendering2.rb, Formula/ogre2.1.rb
ignition-rendering[12]: depend on ogre2.1 also now
=> ogre2.1: allow side-by-side install

azure-pipelines.yml
Otherwise it skips testing the gazebo, gui, and rendering formulae.
=> azure-pipelines.yml: try xquartz install

Formula/ignition-sensors2.rb
Bump to this commit: https://bitbucket.org/ignitionrobotics/ign-sensors/commits/3f21986d285b723244362798101a9c4c8c0dbd97?at=default
=> ignition-sensors2 blueprint bump

Formula/ignition-gazebo2.rb
This is a place holder for now. I'd like to get in the last gazebo PR: https://bitbucket.org/ignitionrobotics/ign-gazebo/pull-requests/337/blueprint-log-entity-creation-and-deletion/diff
=> Bump gazebo2 version

Formula/ignition-fuel-tools1.rb, Formula/ignition-fuel-tools2.rb, Formula/ignition-fuel-tools3.rb
revision bumps needed due to https://github.com/Homebrew/homebrew-core/pull/41571
=> ignition-fuel-tools revision bumps for jsoncpp 1.9.0

Formula/ignition-rendering0.rb, Formula/ignition-rendering1.rb, Formula/ignition-rendering2.rb
This should fix #794 without requiring new bottles. Don't merge unless CI is 💚.
=> ignition-rendering*: skip test on azure/travis

Aliases/ignition-rendering3, Formula/ignition-rendering3.rb
Uses the latest commit on ign-rendering's default branch:
https://bitbucket.org/ignitionrobotics/ign-rendering/commits/7af2213e442e4017b39172434012982b4bb64037
=> ign-rendering3 formula

Aliases/ignition-gui3, Formula/ignition-gui3.rb
Goes with this PR:
https://bitbucket.org/ignitionrobotics/ign-gui/pull-requests/221/depend-on-ign-rendering3/
=> ignition-gui3 depend on ignition-rendering3

Aliases/ignition-sensors3, Formula/ignition-sensors3.rb
Goes with this PR:
https://bitbucket.org/ignitionrobotics/ign-sensors/pull-requests/88/depend-on-ign-rendering3/diff
=> ignition-sensors3: depend on ignition-rendering3

Aliases/ignition-gazebo3, Formula/ignition-gazebo3.rb
Goes with this PR: https://bitbucket.org/ignitionrobotics/ign-gazebo/pull-requests/411/depend-on-ign-rendering3-ign-gui3-ign/diff
=> ignition-gazebo3: depend on rendering3, sensors3 and gui3

Formula/ignition-gazebo2.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gui2.rb, Formula/ignition-gui3.rb, Formula/ignition-launch1.rb, Formula/ignition-msgs4.rb, Formula/ignition-sensors2.rb, Formula/ignition-sensors3.rb, Formula/ignition-transport7.rb
=> ignition-msgs4 and dependents: bump revision for protobuf 3.9

Formula/ogre.rb
this doesn't need a bottle rebuild if CI is green
=> ogre: use gist for patch instead of bitbucket

Formula/ignition-acropolis.rb, Formula/ignition-gazebo1.rb, Formula/ignition-gui1.rb, Formula/ignition-launch0.rb, Formula/ignition-msgs3.rb, Formula/ignition-sensors1.rb, Formula/ignition-transport6.rb
Acropolis is end-of-life and the bottles were broken
by protobuf 3.10.
=> ignition-msgs3, dependents: remove bottles

Aliases/ignition-tools1, Formula/ignition-tools1.rb
follow-up to #851 
cc @j-rivero
=> ignition-tools1: initial version usign ign-cmake2

Aliases/ignition-launch2, Formula/ignition-launch2.rb
Goes with https://bitbucket.org/ignitionrobotics/ign-launch/pull-requests/47/
=> ignition-launch2

Aliases/ignition-transport8, Formula/ignition-transport8.rb
See https://bitbucket.org/ignitionrobotics/ign-transport/pull-requests/402/
=> ignition-transport8: depend on ign-msgs5

Formula/ignition-gui3.rb
See https://bitbucket.org/ignitionrobotics/ign-gui/pull-requests/225/
=> ignition-gui3: depend on msgs5 and transport8

Formula/ignition-sensors3.rb
See https://bitbucket.org/ignitionrobotics/ign-sensors/pull-requests/101/
=> ignition-sensors3: depend on msgs5 and transport8

Formula/ignition-gazebo3.rb
See https://bitbucket.org/ignitionrobotics/ign-gazebo/pull-requests/447/
=> ignition-gazebo3: depend on msgs5 and transport8

Formula/ignition-launch2.rb
See https://bitbucket.org/ignitionrobotics/ign-launch/pull-requests/50
=> ignition-launch2: depend on msgs5 and transport8

Formula/ignition-sensors3.rb, Formula/sdformat9.rb
see [ignition-sensors pull request #105](https://bitbucket.org/ignitionrobotics/ign-sensors/pull-requests/105/citadel-depend-on-sdformat9/diff)
=> ignition-sensors3: depend on sdformat9

Formula/ignition-citadel.rb
=> ignition-citadel 1.0.0 (take2)

Formula/dartsim@6.10.0.rb, Formula/ignition-physics1.rb, Formula/ignition-physics2.rb
Required since this fcl upgrade https://github.com/Homebrew/homebrew-core/pull/49975
=> Revision bump dartsim@6.10.0, ignition-physics* for fcl

Formula/gazebo10.rb, Formula/gazebo11.rb, Formula/gazebo9.rb
Required since this fcl upgrade Homebrew/homebrew-core#49975
=> Revision bump gazebo9/10/11 for fcl

Aliases/ignition-gui4, Formula/ignition-gui4.rb
=> ignition-gui4: new formula

Aliases/ignition-gazebo4, Formula/ignition-gazebo4.rb
depends on pull request #970 
bumps dependencies: gui4, sensors4, rendering4
=> ign-gazebo4: new formula

Aliases/ignition-launch3, Formula/ignition-launch3.rb
Needed by this PR: https://bitbucket.org/ignitionrobotics/ign-launch/pull-requests/64/
=> ign-launch3: new formula

Formula/sdformat9.rb
=> sdformat9: depend on urdfdom, add patch

Aliases/ignition-fuel-tools5, Aliases/ignition-msgs6, Formula/ignition-fuel-tools5.rb, Formula/ignition-msgs6.rb
For this PR: https://bitbucket.org/ignitionrobotics/ign-fuel-tools/pull-requests/127/
=> ignition-msgs6, ignition-fuel-tools5: Dome dependencies

Formula/gazebo10.rb, Formula/gazebo9.rb, Formula/ignition-msgs1.rb, Formula/ignition-transport4.rb
Bump revision to get new bottles built
=> Rebuild bottles for: msgs1, transport4, gazebo9 and gazebo10

Formula/dartsim@6.10.0.rb, Formula/ignition-physics1.rb, Formula/ignition-physics2.rb, Formula/sdformat8.rb, Formula/sdformat9.rb
=> Bump revisions for console_bridge 1.0

.github/workflows/main.yml, Formula/bullet@2.87.rb, Formula/chrono-engine.rb, Formula/gazebo2.rb, Formula/gazebo3.rb, Formula/gazebo4.rb, Formula/gazebo5.rb, Formula/gazebo6.rb, Formula/gazebo8.rb, Formula/gazebo@1.rb, Formula/haptix-comm.rb, Formula/ignition-fuel-tools5.rb, Formula/ignition-msgs6.rb, Formula/ignition-transport.rb, Formula/ignition-transport2.rb, Formula/player.rb, Formula/sofa.rb
The first set of changes won't fix all issues. Seems like brew is removing the dependencies on custom build flags (see https://github.com/Homebrew/brew/pull/2482), not sure how we want to react to that change. @scpeters ?
I think that the rest of changes are somehow trivial and should not affect how Formulas work.
=> Style and format fixes to make test-bot happy

Formula/ignition-fuel-tools1.rb
=> ignition-fuel-tools1: revision bump for jsoncpp

Formula/ignition-msgs4.rb, Formula/ignition-msgs5.rb
=> ignition-msgs[45]: rebuild bottles

Formula/ignition-gazebo4.rb, Formula/ignition-gui4.rb, Formula/ignition-sensors4.rb
This is needed by https://github.com/ignitionrobotics/ign-gazebo/pull/144
=> ign-gui4: update commit

Aliases/sdformat10, Formula/sdformat10.rb
Builds from head of `sdf10` branch https://github.com/osrf/sdformat/commit/1e213886f892e6accd1c7b0f104a8af2583ed68b
=> sdformat10: new formula, depends on tinyxml2

Formula/ignition-msgs4.rb, Formula/ignition-msgs5.rb
=> Revision for ignition-msgs[45] for protobuf

Formula/ignition-gazebo4.rb
Broken off #1063, uses the latest commit of https://github.com/ignitionrobotics/ign-gazebo/pull/262/
=> ignition-gazebo4: bump for msgs6, transport9, sdf10, fuel5, physics3

Aliases/ignition-physics3, Formula/ignition-physics3.rb
Needed for https://github.com/ignitionrobotics/ign-gazebo/pull/262
=> Add ign-physics3 formula for Dome

Formula/ignition-msgs6.rb
Need latest msgs6 features for https://github.com/ignitionrobotics/ign-gazebo/pull/262
=> Update msgs6 to latest commit

Formula/ignition-cmake2.rb
Testing a new approach to building bottles.
=> ignition-cmake2: revision bump to rebuild bottles

Formula/ignition-msgs4.rb, Formula/ignition-transport7.rb
Let's see if this will trigger it automatically: build bottle.
=> Rebuild msgs4, transport7

Formula/gazebo9.rb, Formula/ignition-msgs1.rb, Formula/ignition-transport4.rb
Revision bump for ignition-msgs1, ignition-transport7, and gazebo9.
=> Rebuild gazebo9 bottle

Formula/gazebo11.rb, Formula/ignition-fuel-tools4.rb, Formula/ignition-msgs5.rb, Formula/ignition-transport8.rb, Formula/sdformat9.rb
Rebuilds ignition-msgs5, ignition-transport8, ignition-fuel-tools4, sdformat9, and gazebo11.
=> Rebuild gazebo11 bottle

Formula/ignition-blueprint.rb, Formula/ignition-launch1.rb
Bump revisions for ignition-launch1 and ignition-blueprint. Add a test for ignition-launch.
=> Rebuild blueprint bottle

Formula/dartsim@6.10.0.rb, Formula/ignition-physics2.rb
Revision bump for dartsim@6.10.0 and ignition-physics2.
=> Rebuild dartsim bottle

Formula/ignition-citadel.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gui3.rb, Formula/ignition-launch2.rb, Formula/ignition-sensors3.rb
Revision bump for ignition-gui3, ignition-sensors3, ignition-gazebo3, ignition-launch2, and ignition-citadel.
=> Rebuild citadel bottles

Formula/ignition-dome.rb, Formula/ignition-fuel-tools5.rb, Formula/ignition-gazebo4.rb, Formula/ignition-launch3.rb, Formula/ignition-sensors4.rb
Rebuild some bottles and add test for ignition-launch3.
=> Rebuild dome bottles

.github/workflows/main.yml
Separate portions of GitHub workflow script into multiple steps.
Add descriptive comments.
=> Split GitHub workflow into steps

Formula/ignition-blueprint.rb, Formula/ignition-citadel.rb, Formula/ignition-dome.rb, Formula/ignition-fuel-tools5.rb, Formula/ignition-gazebo4.rb, Formula/ignition-gui4.rb, Formula/ignition-launch3.rb, Formula/ignition-msgs6.rb, Formula/ignition-sensors4.rb, Formula/ignition-transport9.rb
Remove all `master`:
* Release branches for Dome libraries
* `main` for collections
=> Update Dome branches and main

Aliases/ignition-fuel-tools6, Aliases/ignition-gazebo5, Aliases/ignition-gui5, Aliases/ignition-launch4, Aliases/ignition-msgs7, Aliases/ignition-physics4, Aliases/ignition-rendering5, Aliases/ignition-sensors5
Aliases for new versions of main branches since the Dome release.
=> Aliases: fuel-tools6, gazebo5, gui5, launch4, msgs7, physics4, rendering5, sensors5

Formula/gazebo11.rb
=> Bump gazebo11 revision to fix boost symbol change

Formula/gazebo9.rb
Patch submitted upstream at https://github.com/osrf/gazebo/pull/2865
=> gazebo9: revision and patch for boost 1.74.0

Aliases/ignition-sensors5, Formula/ignition-sensors5.rb
* Remove alias
* Copy formula from previous version
* Update to use the commit from https://github.com/ignitionrobotics/ign-sensors/pull/55
=> ignition-sensors5: depend on rendering5

Aliases/ignition-gui5, Formula/ignition-gui5.rb
* Remove alias
* Copy formula from previous version
* Update to use the commit from https://github.com/ignitionrobotics/ign-gui/pull/141
=> ignition-gui5: use rendering5

Aliases/ignition-launch4, Formula/ignition-launch4.rb
* Remove alias
* Copy formula from previous version
* Update to use the commit from https://github.com/ignitionrobotics/ign-launch/pull/69
=> ignition-launch4: use rendering5

Formula/ignition-gazebo2.rb, Formula/ignition-gui2.rb, Formula/ignition-msgs4.rb, Formula/ignition-sensors2.rb, Formula/ignition-transport7.rb
=> ignition-msgs4: revision bump for protobuf 3.14

Formula/ignition-fuel-tools5.rb, Formula/ignition-gazebo4.rb, Formula/ignition-gazebo5.rb, Formula/ignition-gui4.rb, Formula/ignition-gui5.rb, Formula/ignition-msgs6.rb, Formula/ignition-sensors4.rb, Formula/ignition-sensors5.rb, Formula/ignition-transport9.rb
Rebuild due to recent protobuf 3.14.0 release (#1205).
=> ignition-msgs6: revision bump for protobuf 3.14

Formula/gazebo11.rb, Formula/ignition-fuel-tools4.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gui3.rb, Formula/ignition-msgs5.rb, Formula/ignition-sensors3.rb, Formula/ignition-transport8.rb
=> ignition-msgs5: revision bump for protobuf 3.14

Formula/gazebo10.rb, Formula/gazebo9.rb, Formula/ignition-msgs1.rb, Formula/ignition-transport4.rb
gazebo9, gazebo10, ignition-msgs1, and ignition-transport4. Part of #1205.
=> Bump revisions for ignition-msgs1 and dependents

Formula/ignition-rendering5.rb
Need latest `rendering5` features for https://github.com/ignitionrobotics/ign-gazebo/pull/460
Signed-off-by: Ashton Larkin <ashton@openrobotics.org>
=> ignition-rendering5: update to latest commit

Formula/ignition-launch1.rb
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_launch1-install_bottle-homebrew-amd64&build=176)](https://build.osrfoundation.org/view/ign-blueprint/job/ignition_launch1-install_bottle-homebrew-amd64/176/) https://build.osrfoundation.org/view/ign-blueprint/job/ignition_launch1-install_bottle-homebrew-amd64/176/
=> ignition-launch1: revision bump for protobuf

Formula/ignition-citadel.rb, Formula/ignition-dome.rb, Formula/ignition-edifice.rb
Use `vcs validate` to test the gazebodistro yaml files.
=> Add tests for ignition collections

Formula/dartsim@6.10.0.rb, Formula/ignition-physics1.rb, Formula/ignition-physics2.rb, Formula/ignition-physics3.rb
=> dartsim@6.10.0 revision bump for bullet 3.08

Formula/ignition-blueprint.rb, Formula/ignition-fuel-tools3.rb, Formula/ignition-gazebo2.rb, Formula/ignition-gui2.rb, Formula/ignition-launch1.rb, Formula/ignition-msgs4.rb, Formula/ignition-physics1.rb, Formula/ignition-rendering2.rb, Formula/ignition-sensors2.rb, Formula/ignition-transport7.rb, Formula/sdformat8.rb
Deprecate on the EOL date and disable one month later.
=> 🏁 Blueprint EOL

Aliases/ignition-msgs7, Formula/ignition-msgs7.rb
Signed-off-by: Nate Koenig <nate@openrobotics.org>
=> ignition-msgs7: new formula

Formula/ignition-rendering0.rb, Formula/ignition-rendering2.rb, Formula/ignition-rendering3.rb, Formula/ignition-rendering4.rb, Formula/ignition-rendering5.rb
=> ignition-rendering*: remove old vars, fix style

Aliases/ignition-transport10, Formula/ignition-transport10.rb
Addresses https://github.com/ignition-tooling/release-tools/issues/362
Uses commit from https://github.com/ignitionrobotics/ign-transport/pull/213/
=> ignition-transport10: new formula

Formula/ignition-sensors5.rb
Addresses https://github.com/ignition-tooling/release-tools/issues/362
Uses commit from https://github.com/ignitionrobotics/ign-sensors/pull/75/
=> ignition-sensors5: depend on msgs7/transport10

Formula/ignition-gui5.rb
Addressing https://github.com/ignition-tooling/release-tools/issues/362
Using commit from https://github.com/ignitionrobotics/ign-gui/pull/167
=> ignition-gui5: depend on msgs7/transport10

Aliases/sdformat11, Formula/sdformat11.rb
Addresses https://github.com/ignition-tooling/release-tools/issues/360
Points to the latest commit on `master`.
=> sdformat11: new formula

Aliases/ignition-physics4, Formula/ignition-physics4.rb
Addresses https://github.com/ignition-tooling/release-tools/issues/360
=> ignition-physics4: new formula

Formula/ignition-edifice.rb, Formula/ignition-gazebo5.rb, Formula/ignition-launch4.rb, Formula/ignition-sensors5.rb, Formula/sdformat10.rb, Formula/sdformat11.rb
Addresses https://github.com/ignition-tooling/release-tools/issues/360
Uses commit from https://github.com/ignitionrobotics/ign-sensors/pull/78
=> ignition-sensors5: depend on sdformat11

Formula/ignition-msgs7.rb
Needed by https://github.com/ignitionrobotics/ign-transport/pull/209
=> ignition-msgs7: revision bump

Formula/ignition-transport10.rb
Needed by https://github.com/ignitionrobotics/ign-gazebo/pull/566
=> ignition-transport10: revision bump

Formula/ignition-rendering5.rb
Bump to latest commit in `main` branch.
Needed by https://github.com/ignitionrobotics/ign-gazebo/pull/514
=> ignition-rendering5: bump commit

Aliases/ignition-common4, Formula/ignition-common4.rb
=> ignition-common4: new formula

Formula/ignition-common3.rb, Formula/ignition-msgs7.rb, Formula/ignition-physics4.rb, Formula/ignition-transport10.rb, Formula/ignition-utils1.rb, Formula/sdformat11.rb
=> ignition-physics4: depend on ignition-common4

Formula/ignition-gazebo5.rb
=> ignition-gazebo5: depend on ignition-common4

Formula/ignition-gui5.rb
=> ignition-gui5: depend on ignition-common4

Formula/ignition-sensors5.rb
=> ignition-sensors5: depend on ignition-common4

Formula/ignition-launch4.rb
=> ignition-launch4: depend on ignition-common4

Formula/ignition-rendering5.rb
=> ignition-rendering5: depend on ignition-common4

Formula/ignition-edifice.rb
=> ignition-edifice: depend on ignition-common4

Formula/ignition-gazebo5.rb
Part of https://github.com/ignitionrobotics/ign-gazebo/issues/568
=> ign-gazebo5: depend on ign-utils1

Formula/ignition-common4.rb
Part of https://github.com/ignitionrobotics/ign-common/issues/161
=> ignition-common4: depend on ignition-utils1

Formula/ignition-msgs7.rb
Needed by a couple of downstream PRs.
=> ignition-msgs7: bump commit

Formula/ignition-transport10.rb
Needed by https://github.com/ignitionrobotics/ign-transport/pull/216
=> ignition-transport10: use ignition-utils1

Formula/ignition-utils1.rb
Update commit to use https://github.com/ignitionrobotics/ign-utils/pull/2, needed by https://github.com/ignitionrobotics/ign-transport/pull/216
=> ignition-utils1: update to include cli component

Formula/ignition-common1.rb, Formula/ignition-common2.rb, Formula/ignition-fuel-tools1.rb, Formula/ignition-fuel-tools2.rb, Formula/ignition-fuel-tools3.rb, Formula/ignition-gazebo4.rb, Formula/ignition-math2.rb, Formula/ignition-math3.rb, Formula/ignition-math4.rb, Formula/ignition-math5.rb, Formula/ignition-math6.rb, Formula/ignition-msgs7.rb, Formula/ignition-plugin0.rb, Formula/ignition-plugin1.rb, Formula/ignition-rendering4.rb, Formula/ignition-rendering5.rb, Formula/ignition-tools.rb, Formula/ignition-utils1.rb, Formula/sdformat4.rb, Formula/sdformat5.rb, Formula/sdformat6.rb, Formula/sdformat7.rb, Formula/simbody.rb, Formula/tinyxml2@6.2.0.rb
=> Fix whitespace in bottle alignment

Formula/ignition-physics4.rb
needed by https://github.com/ignitionrobotics/ign-gazebo/pull/542
=> ignition-physics4: newer commit for SDFormat 1.8

Formula/ogre2.1.rb
fix style as recommended by https://github.com/Homebrew/brew/pull/10634
=> ogre2.1: fix style

Formula/ignition-fuel-tools6.rb
Needed by https://github.com/ignitionrobotics/ign-gazebo/pull/577
=> ignition-fuel-tools6: Bump revision

Formula/ignition-fuel-tools6.rb, Formula/ignition-gui5.rb, Formula/ignition-msgs7.rb, Formula/ignition-sensors5.rb, Formula/ignition-transport10.rb
=> Rebuild ignition-msgs7 and dependents

Formula/ignition-fuel-tools4.rb, Formula/ignition-gui3.rb, Formula/ignition-msgs5.rb, Formula/ignition-sensors3.rb, Formula/ignition-transport8.rb
=> Rebuild ignition-msgs5 and dependents

Formula/ignition-citadel.rb, Formula/ignition-edifice.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gazebo5.rb, Formula/ignition-launch2.rb, Formula/ignition-launch4.rb
Also bump revisions to rebuild launch and collection bottles.
=> ignition-gazebo[35]: use qt@5 in test

Formula/ignition-msgs1.rb, Formula/ignition-transport4.rb
=> ignition-msgs1: rebuild for protobuf 3.15

Formula/sdformat11.rb
This is needed to fix `ign-gazebo`'s CI
=> sdformat11: bump commit

Formula/ignition-physics4.rb
Signed-off-by: Louise Poubel <louise@openrobotics.org>
=> ignition-physics4: bump commit

Formula/ogre2.2.rb
Mostly a copy of ogre2.1 formula with the following changes:
* Updated code snapshot and branch
* Updated patch to compile with cmake3 and c++11
* Disabled the patch for "GL3+ compilation with Xcode 10" (maybe merged upstream?)
=> New ogre2.2 formula

Aliases/ignition-common5, Aliases/ignition-fuel-tools7, Aliases/ignition-gazebo6, Aliases/ignition-gui6, Aliases/ignition-launch5, Aliases/ignition-msgs8, Aliases/ignition-physics5, Aliases/ignition-rendering6, Aliases/ignition-sensors6, Aliases/ignition-transport11, Aliases/ignition-utils2, Aliases/sdformat12
Similar to https://github.com/osrf/homebrew-simulation/commit/1f8602af6f52e06e0542eebfbdbe97f5f6cf950c
https://github.com/ignition-tooling/release-tools/issues/421
=> Aliases: common5, fuel-tools7, gazebo6, gui6, launch5, msgs8, physics5, msgs8, physics5, sensors6, transport11, utils2, sdformat12

Aliases/ignition-fortress, Aliases/ignition-fortress1
Until we bump versions, fortress is the same as edifice.
https://github.com/ignition-tooling/release-tools/issues/421
=> Alias: ignition-fortress

Formula/sdformat10.rb
=> sdformat10: revision bump to build bottle

Aliases/ignition-rendering6, Formula/ignition-rendering6.rb
=> Bumps in fortress : ign-rendering

Aliases/ignition-msgs8, Formula/ignition-msgs8.rb
=> Bumps in fortress : ign-msgs

Aliases/sdformat12, Formula/sdformat12.rb
=> Bumps in fortress : sdformat

Aliases/ignition-physics5, Formula/ignition-physics5.rb
=> Bumps in fortress : ign-physics

Aliases/ignition-transport11, Formula/ignition-transport11.rb
=> Bumps in fortress : ign-transport

Aliases/ignition-sensors6, Formula/ignition-sensors6.rb
=> Bumps in fortress : ign-sensors

Aliases/ignition-gui6, Formula/ignition-gui6.rb
=> Bumps in fortress : ign-gui

Aliases/ignition-fuel-tools7, Formula/ignition-fuel-tools7.rb
=> Bumps in fortress : ign-fuel-tools

Aliases/ignition-gazebo6, Formula/ignition-gazebo6.rb
=> Bumps in fortress : ign-gazebo

Aliases/ignition-launch5, Formula/ignition-launch5.rb
=> Bumps in fortress : ign-launch

Aliases/ignition-fortress, Formula/ignition-fortress.rb
=> Bumps in fortress : ign-fortress

Formula/gazebo11.rb
=> gazebo11: revision bump for dart 6.10.0

Formula/gazebo9.rb
=> gazebo9: revision bump for dart 6.10.0

Formula/ignition-msgs8.rb
Needed by https://github.com/ignitionrobotics/ign-gazebo/pull/811
=> ignition-msgs8: bump commit

Formula/dartsim@6.10.0.rb, Formula/ignition-physics4.rb, Formula/ignition-physics5.rb
Fix for ignition parts of #1455.
=> Bump revisions for dartsim@6.10.0, ignition-physics[45] for bullet

Formula/gazebo11.rb, Formula/gazebo9.rb
=> Bump gazebo9 and gazebo11 to rebuild bottles after bullet upgrade

Formula/ignition-physics5.rb
Similar approach to https://github.com/osrf/homebrew-simulation/pull/1459
Needed by https://github.com/ignitionrobotics/ign-gazebo/pull/811
=> ignition-physics5: build main branch from source

Formula/ignition-rendering6.rb
Similar to #1460, part of #1314, needed since https://github.com/ignitionrobotics/ign-rendering/pull/314 was merged.
=> ignition-rendering6: build main branch from source

Formula/ignition-msgs1.rb, Formula/ignition-msgs5.rb, Formula/ignition-msgs6.rb, Formula/ignition-msgs7.rb
=> Bump ignition-msgs* for protobuf 3.17.0

Formula/ignition-transport10.rb, Formula/ignition-transport11.rb, Formula/ignition-transport4.rb, Formula/ignition-transport8.rb, Formula/ignition-transport9.rb
=> Bump ign-transport* for protobuf 3.17.0

Formula/ignition-fuel-tools1.rb, Formula/ignition-fuel-tools4.rb, Formula/ignition-fuel-tools5.rb, Formula/ignition-fuel-tools6.rb
=> bump fuel tools protobuf317

Formula/gazebo9.rb
=> Bump gazebo9 for protobuf 3.17.0

Formula/ignition-gui3.rb, Formula/ignition-gui4.rb, Formula/ignition-gui5.rb, Formula/ignition-gui6.rb
=> bump gui protobuf317

Formula/gazebo11.rb, Formula/gazebo9.rb
=> bump gazebo11 protobuf317

Formula/ignition-sensors3.rb, Formula/ignition-sensors4.rb, Formula/ignition-sensors5.rb, Formula/ignition-sensors6.rb
=> ignition-sensors: bump for protobuf

Formula/gazebo11.rb, Formula/gazebo9.rb
=> gazebo*: remove bottles due to tbb

Formula/ignition-launch2.rb, Formula/ignition-launch3.rb, Formula/ignition-launch4.rb, Formula/ignition-launch5.rb
=> ignition-launch: bump revision for protobuf

Formula/gazebo9.rb
=> gazebo9: use tbb@2020 and update test

Formula/ignition-citadel.rb, Formula/ignition-dome.rb, Formula/ignition-edifice.rb, Formula/ignition-fortress.rb
=> ignition collections: bump revision for protobuf

Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui6.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb
=> Fortress deps: build from main branch

Formula/gazebo9.rb
=> gazebo9: use tbb@2020_u3

Formula/ignition-dome.rb, Formula/ignition-edifice.rb, Formula/ignition-gazebo4.rb, Formula/ignition-gazebo5.rb, Formula/ignition-gazebo6.rb, Formula/ignition-physics3.rb, Formula/ignition-physics4.rb, Formula/ignition-physics5.rb, Formula/ignition-sensors4.rb, Formula/ignition-sensors5.rb, Formula/ignition-sensors6.rb
=> tinyxml2 fallout: unbottle dependents of sdformat1*

Formula/ignition-msgs1.rb
Follow up to #1490 - Broken https://build.osrfoundation.org/job/gazebo-ci-pr_any-homebrew-amd64/2431/consoleFull#12022289356ea37b8d-a6d4-40ae-8431-d90c018842af
=> tinyxml2 fallout: rebuild msgs1 bottle

Formula/dartsim@6.10.0.rb
=> tinyxml2 fallout: rebuild sdformat bottles for dartsim@6.10.0

Formula/sdformat10.rb, Formula/sdformat11.rb, Formula/sdformat12.rb, Formula/sdformat9.rb
=> tinyxml2 fallout: rebuild sdformat bottles

Formula/ignition-msgs4.rb, Formula/ignition-msgs5.rb, Formula/ignition-msgs6.rb, Formula/ignition-msgs7.rb, Formula/ignition-msgs8.rb
=> tinyxml2 fallout: rebuild msgs* bottles

Formula/ignition-common0.rb, Formula/ignition-common1.rb, Formula/ignition-common2.rb, Formula/ignition-common3.rb, Formula/ignition-common4.rb
=> tinyxml2 fallout: rebuild common* bottles 

Formula/ignition-transport10.rb, Formula/ignition-transport9.rb
=> tinyxml2 fallout: rebuild transport* bottles 

Formula/ignition-rendering3.rb, Formula/ignition-rendering4.rb, Formula/ignition-rendering5.rb, Formula/ignition-rendering6.rb
=> tinyxml2 fallout: rebuild rendering* bottles 

Formula/ignition-fuel-tools1.rb, Formula/ignition-fuel-tools4.rb, Formula/ignition-fuel-tools5.rb, Formula/ignition-fuel-tools6.rb, Formula/ignition-fuel-tools7.rb
=> tinyxml2 fallout: rebuild fuel-tools* bottles 

Formula/ignition-physics2.rb, Formula/ignition-physics3.rb, Formula/ignition-physics4.rb, Formula/ignition-physics5.rb
=> tinyxml2 fallout: rebuild physics* bottles

Formula/ignition-transport8.rb
=> tinyxml2 fallout: rebuild transport8 bottle

Formula/ignition-transport11.rb
=> ignition-transport11: disable bottle for tinyxml2

Formula/dartsim@6.10.0.rb
I don't know if this is the correct thing to do. I'm trying to sync the macOS binaries with the latest Ubuntu ones to fix https://github.com/ignitionrobotics/ign-physics/pull/262/.
=> [dart] Bump commit

Formula/ignition-fuel-tools7.rb, Formula/ignition-msgs8.rb, Formula/ignition-physics5.rb, Formula/ignition-rendering6.rb, Formula/ignition-transport11.rb
Build from source instead. Follow-up to #1529
=> Remove fortress bottles for now

Aliases/ignition-plugin2, Formula/ignition-plugin2.rb
Add dependency on ignition-utils1. Needed by https://github.com/ignitionrobotics/ign-plugin/pull/55
=> ignition-plugin2: new formula

Formula/gazebo9.rb
=> gazebo9: revision bump for dartsim, qwt

Formula/gazebo9.rb
=> gazebo9: depend on qwt-qt5

Formula/dartsim@6.10.0.rb, Formula/ignition-physics2.rb, Formula/ignition-physics3.rb, Formula/ignition-physics4.rb
Rebuild bottles for dartsim@6.10.0 and ignition-physics*. Part of #1570.
=> dartsim@6.10.0: revision bump for fcl 0.7.0

Formula/gazebo11.rb
=> gazebo11: revision bump for fcl

Formula/gazebo9.rb
=> gazebo9: revision bump for fcl

Formula/ignition-rendering6.rb
=> ignition-rendering6: use ogre 2.2

Formula/dartsim@6.10.0.rb
Needed by https://github.com/ignitionrobotics/ign-physics/pull/267/
=> dartsim@6.10.0 bump commit

Aliases/ignition-fuel-tools8, Aliases/ignition-gazebo7, Aliases/ignition-gui7, Aliases/ignition-launch6, Aliases/ignition-msgs9, Aliases/ignition-physics6, Aliases/ignition-rendering7, Aliases/ignition-sensors7, Aliases/ignition-transport12, Aliases/sdformat13
Part of https://github.com/ignition-tooling/release-tools/issues/459
=> Add aliases for new major versions

Formula/gazebo9.rb, Formula/sdformat6.rb
Needed since urdfdom 3.0.0 was released in https://github.com/Homebrew/homebrew-core/pull/87001
=> sdformat6: revision bump for urdfdom

Formula/gazebo11.rb
=> gazebo11 bump for new DART (takeII)

Formula/ignition-cmake2.rb
Open pull request to build big_sur bottle for ignition-cmake2
=> ignition-cmake2: --only-big_sur

Aliases/ignition-sensors7, Formula/ignition-sensors7.rb
=> Bumps in garden : ign-sensors

Aliases/ignition-gui7, Formula/ignition-gui7.rb
=> Bumps in garden : ign-gui

Formula/ignition-rendering7.rb
Motivated by https://github.com/ignitionrobotics/ign-rendering/pull/490#discussion_r751910398
Part of https://github.com/ignitionrobotics/ign-rendering/issues/491
=> ignition-rendering7: depend on ignition-utils1

Aliases/ignition-gazebo7, Formula/ignition-gazebo7.rb
=> Bumps in garden : ign-gazebo

Aliases/ignition-launch6, Formula/ignition-launch6.rb
=> Bumps in garden : ign-launch

Formula/ignition-garden.rb
=> Bumps in garden : ign-garden

Formula/cmake@3.21.4.rb
Needed for gazebo11 CI. Workaround for https://github.com/ignition-tooling/release-tools/issues/573.
=> cmake@3.21.4: new formula

README.md
Accompanies https://github.com/ignition-tooling/release-tools/pull/556
=> Docs for building bottles for new macOS version

Formula/ignition-cmake0.rb, Formula/ignition-math4.rb
Testing https://github.com/ignition-tooling/release-tools/pull/556
=> ignition-math4: keep old bottles

Formula/ignition-common1.rb, Formula/ignition-fuel-tools1.rb, Formula/ignition-msgs1.rb, Formula/ignition-transport4.rb
Use this chance to build big_sur bottles.
=> Set RPATH for gazebo9 deps

Formula/sdformat6.rb
=> sdformat6: set RPATH and bump revision

Aliases/ignition-msgs9, Formula/ignition-msgs9.rb
=> Bumps in garden : ci_matching_branch/bump_garden_ign-msgs9

Aliases/ignition-transport12, Formula/ignition-transport12.rb
=> Bumps in garden : ci_matching_branch/bump_garden_ign-transport12

Aliases/ignition-fuel-tools8, Formula/ignition-fuel-tools8.rb
=> Bumps in garden : ci_matching_branch/bump_garden_ign-fuel-tools8

Formula/ignition-sensors7.rb
=> Bumps in garden : ci_matching_branch/bump_garden_ign-sensors7

Formula/ignition-gui7.rb
=> Bumps in garden : ci_matching_branch/bump_garden_ign-gui7

Formula/ignition-gazebo7.rb
=> Bumps in garden : ci_matching_branch/bump_garden_ign-gazebo7

Formula/ignition-launch6.rb
=> Bumps in garden : ci_matching_branch/bump_garden_ign-launch6

Formula/dartsim@6.10.0.rb, Formula/ignition-physics3.rb, Formula/ignition-physics4.rb, Formula/ignition-physics5.rb
=> Rebuild dartsim, ignition-physics for bullet 3.21.0

Formula/tbb@2020_u3.rb
Trivial change to comment needed for bottle build
=> tbb@2020_u3: build big_sur bottle

Formula/ignition-fuel-tools4.rb
Really an excuse to build a big_sur bottle
=> ignition-fuel-tools4: set CMAKE_INSTALL_RPATH

Formula/ignition-physics2.rb
Part of #1709. Not sure why I didn't include this in #1712.
=> ignition-physics2: revision bump for bullet 3.21.0

Formula/gazebo11.rb
=> gazebo11: revision bump for bullet 3.21.0

Formula/ignition-sensors6.rb
Make trivial change to allow bottle build.
=> ignition-sensors6: big_sur bottle

Aliases/ignition-physics6, Formula/ignition-physics6.rb
=> Bumps in garden : create ignition-physics6

Aliases/ignition-math7, Formula/ignition-math7.rb
=> Bumps in garden : create ignition-math7

Aliases/sdformat13, Formula/sdformat13.rb
=> Bumps in garden : create sdformat13

Formula/ignition-math7.rb
=> ignition-math7: depend on ignition-utils1

Formula/ignition-dome.rb, Formula/ignition-fuel-tools5.rb, Formula/ignition-gazebo4.rb, Formula/ignition-gui4.rb, Formula/ignition-launch3.rb, Formula/ignition-msgs6.rb, Formula/ignition-physics3.rb, Formula/ignition-rendering4.rb, Formula/ignition-sensors4.rb, Formula/ignition-transport9.rb, Formula/sdformat10.rb
* Follow up to https://github.com/osrf/homebrew-simulation/pull/1734
* Repeating the mistakes from Blueprint, see https://github.com/osrf/homebrew-simulation/pull/1256
* Part of https://github.com/ignition-tooling/release-tools/issues/600
=> ignition-dome: remove disable!

Formula/ignition-rendering5.rb
Minor change to allow building a big_sur bottle
=> ignition-rendering5: build big_sur bottle

Formula/ignition-msgs5.rb, Formula/ignition-msgs7.rb, Formula/ignition-msgs8.rb
=> Rebuild ignition-msgs* for protobuf 3.19.1

Formula/gazebo10.rb, Formula/gazebo2.rb, Formula/gazebo3.rb, Formula/gazebo4.rb, Formula/gazebo5.rb, Formula/gazebo6.rb, Formula/gazebo7.rb, Formula/gazebo8.rb, Formula/gazebo@1.rb, Formula/simbody.rb
I've cherry-picked a portion of #1698 from @dlech to merge while we discuss the remaining portions.
=> Some Apple M1 fixes from dlech

Formula/ignition-transport10.rb, Formula/ignition-transport11.rb, Formula/ignition-transport8.rb, Formula/ignition-transport9.rb
=> Rebuild ignition-transport* for protobuf 3.19.1

Formula/ignition-fuel-tools4.rb, Formula/ignition-fuel-tools5.rb, Formula/ignition-fuel-tools6.rb, Formula/ignition-fuel-tools7.rb
=> Rebuild ignition-fuel-tools* for protobuf 3.19.1

Formula/gazebo11.rb
=> gazebo11: revision bump for protobuf

Formula/ignition-sensors3.rb, Formula/ignition-sensors4.rb, Formula/ignition-sensors5.rb, Formula/ignition-sensors6.rb
=> Rebuild ignition-sensors* for protobuf 3.19.1

Formula/ignition-gui3.rb, Formula/ignition-gui4.rb, Formula/ignition-gui5.rb, Formula/ignition-gui6.rb
=> Rebuild ignition-gui* for protobuf 3.19.1

Formula/ignition-launch2.rb, Formula/ignition-launch3.rb, Formula/ignition-launch4.rb, Formula/ignition-launch5.rb
=> Rebuild ignition-launch* for protobuf 3.19.1

Formula/ignition-citadel.rb, Formula/ignition-dome.rb, Formula/ignition-edifice.rb, Formula/ignition-fortress.rb
=> Rebuild ignition collections for protobuf 3.19.1

Formula/ignition-common5.rb
=> Bumps in garden: ign-common5 use ign-math7

Formula/sdformat13.rb
=> Bumps in garden: sdformat13 use ign-math7

Formula/ignition-msgs9.rb
=> Bumps in garden: ign-msgs9 use ign-math7

Formula/ignition-rendering7.rb
=> Bumps in garden: ign-rendering7 use ign-math7 and ign-common5

Formula/ignition-gui7.rb
=> Bumps in garden : ign-gui7 depend on ign-common5

Formula/ignition-sensors7.rb
=> Bumps in garden: ign-sensors7 use ign-math7, ign-common5 and sdformat13 

Aliases/ignition-fortress1
Point to ignition-fortress instead of ignition-edifice
=> Fix ignition-fortress1 alias

Formula/ignition-fuel-tools1.rb, Formula/ignition-fuel-tools4.rb, Formula/ignition-fuel-tools6.rb
Part of https://github.com/osrf/homebrew-simulation/issues/1780.
=> ignition-fuel-tools{1,4,6} rebuild bottles for jsoncpp

Formula/ignition-dome.rb, Formula/ignition-fuel-tools5.rb, Formula/ignition-gazebo4.rb, Formula/ignition-gui4.rb, Formula/ignition-launch3.rb, Formula/ignition-msgs6.rb, Formula/ignition-physics3.rb, Formula/ignition-rendering4.rb, Formula/ignition-sensors4.rb, Formula/ignition-transport9.rb, Formula/sdformat10.rb
Part of https://github.com/ignition-tooling/release-tools/issues/600.
=> dome: add disable! date 2 months after EOL

Formula/gazebo2.rb, Formula/gazebo3.rb, Formula/gazebo4.rb, Formula/gazebo5.rb, Formula/gazebo6.rb, Formula/gazebo8.rb, Formula/gazebo@1.rb
=> Disable old versions of gazebo in 2022-02-28

Formula/ignition-common5.rb
Add dependency needed by https://github.com/ignitionrobotics/ign-common/pull/267
=> ignition-common5: depend on gdal

Formula/ignition-gazebo3.rb, Formula/ignition-gazebo5.rb, Formula/ignition-gazebo6.rb, Formula/ignition-launch2.rb, Formula/ignition-launch4.rb, Formula/ignition-launch5.rb
=> Disable more bottle linked against ffmpeg

Formula/gazebo11.rb, Formula/gazebo9.rb, Formula/ignition-common1.rb, Formula/ignition-common3.rb, Formula/ignition-common4.rb, Formula/ignition-common5.rb
This is a keg-only formula but it should work for now. Part of #1800
=> ignition-common*, gazebo9,11: depend on ffmpeg@4

Formula/ignition-common1.rb, Formula/ignition-fuel-tools1.rb
=> Rebuild ignition-common1/fuel-tools1 with ffmpeg@4

Formula/ignition-common3.rb, Formula/ignition-gazebo3.rb, Formula/ignition-launch2.rb
=> Rebuild ign-common3/dependents with ffmpeg@4

Formula/ignition-common4.rb, Formula/ignition-gazebo5.rb, Formula/ignition-gazebo6.rb, Formula/ignition-launch4.rb, Formula/ignition-launch5.rb
Part of https://github.com/osrf/homebrew-simulation/issues/1800
=> Rebuild ign-common4/dependents with ffmpeg@4

Formula/gazebo11.rb
Rebuild gazebo11 bottle using ffmpeg@4. Part of #1800.
=> gazebo11: revision bump for ffmpeg4

Formula/gazebo9.rb
Part of https://github.com/osrf/homebrew-simulation/issues/1722.
=> gazebo9: rebuild for boost 1.78

Formula/gazebo11.rb
Part of https://github.com/osrf/homebrew-simulation/issues/1722.
=> gazebo11: rebuild for boost 1.78

Formula/ignition-common3.rb
Patch from ignitionrobotics/ign-common#325
=> ignition-common3: patch for ffmpeg 5.0 support

Formula/ignition-common4.rb, Formula/ignition-gazebo5.rb, Formula/ignition-gazebo6.rb, Formula/ignition-launch4.rb, Formula/ignition-launch5.rb
Patch from ignitionrobotics/ign-common#325
=> ignition-common4: patch for ffmpeg5 support

Formula/ignition-fuel-tools7.rb, Formula/ignition-gui6.rb, Formula/ignition-msgs8.rb
=> fortress dependencies: fix RPATH

Aliases/ignition-utils2, Formula/ignition-utils2.rb
=> Bumps in garden : ign-utils2

Formula/ignition-common5.rb
=> Bumps in garden : ign-common5

Formula/ignition-math7.rb
=> Bumps in garden : ign-math7

Formula/sdformat13.rb
See: https://github.com/ignition-tooling/release-tools/issues/685
=> Bumps in garden : ign-sdformat13

Formula/ignition-transport12.rb
=> Bumps in garden : ign-transport12

Formula/ignition-rendering7.rb
=> Bumps in garden : ign-rendering7

Formula/ignition-physics6.rb
=> Bumps in garden : ign-physics6

Formula/ignition-gui7.rb
=> Bumps in garden : ign-gui7

Formula/ignition-gazebo7.rb
=> Bumps in garden : ign-utils2, ign-plugin2

Formula/ignition-launch6.rb
=> Bumps in garden : ign-launch6

Formula/ignition-msgs9.rb
=> Bumps in garden : ign-msgs9

Formula/sdformat13.rb
=> Bumps in garden : sdformat13

Formula/ignition-fuel-tools8.rb
=> Bumps in garden : ign-fuel-tools8

Formula/ignition-sensors7.rb
=> Bumps in garden : ign-sensors7

Formula/ignition-plugin2.rb
=> ign-plugin2: depend on ign-tools2

Formula/ignition-gazebo7.rb
=> Bumps in garden : ign-gazebo7

Formula/dartsim@6.10.0.rb, Formula/ignition-physics2.rb, Formula/ignition-physics5.rb
Follow-up to https://github.com/osrf/homebrew-simulation/pull/1912 and https://github.com/Homebrew/homebrew-core/pull/100511
=> Rebuild dartsim, ign-physics for bullet 3.2.4

Formula/gazebo11.rb
Follow-up to https://github.com/osrf/homebrew-simulation/pull/1912 and https://github.com/Homebrew/homebrew-core/pull/100511
=> gazebo11: revision bump for bullet

Formula/gazebo9.rb
Follow-up to https://github.com/osrf/homebrew-simulation/pull/1912 and https://github.com/Homebrew/homebrew-core/pull/100511
=> gazebo9: revision bump for bullet

Formula/ignition-tools2.rb
* Goes with https://github.com/gazebosim/gz-tools/pull/96
=> gz-tools2: depend on gz-cmake3

Formula/ignition-utils2.rb
* Goes with https://github.com/gazebosim/gz-utils/pull/57
=> ignition-utils2: Rename CMake project to gz-utils2

Formula/ignition-plugin2.rb
* Goes with https://github.com/gazebosim/gz-plugin/pull/82
=> ignition-plugin2: Rename CMake project to gz-plugin2

Formula/gazebo11.rb, Formula/gazebo9.rb
Part of https://github.com/osrf/homebrew-simulation/issues/1951
=> Disable bottles broken by boost 1.79

Formula/gazebo9.rb
Part of https://github.com/osrf/homebrew-simulation/issues/1951
=> gazebo9: rebuild bottle for boost 1.79

Formula/gazebo11.rb
Part of https://github.com/osrf/homebrew-simulation/issues/1951.
=> gazebo11: rebuild bottles for boost 1.79

Formula/ignition-msgs8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/1860
=> Rebuild ignition-msgs8 for protobuf

Formula/ignition-citadel.rb, Formula/ignition-fuel-tools4.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gui3.rb, Formula/ignition-launch2.rb, Formula/ignition-sensors3.rb, Formula/ignition-transport8.rb
Created with:
~~~
for f in $(brew uses ignition-msgs5)
do
echo $f
brew bump-revision --message="rebuild after protobuf" $f
done
~~~
and rebased to remove gazebo11 to simplify the build.
=> Rebuild citadel bottles after protobuf bump

Formula/ignition-msgs1.rb
=> ignition-msgs1: rebuild after protobuf bump

Formula/gazebo11.rb
=> gazebo11: revision bump rebuild after protobuf

Formula/gazebo9.rb, Formula/ignition-transport4.rb
Part of https://github.com/osrf/homebrew-simulation/issues/1860
=> gazebo9: revision bump after protobuf

Formula/ignition-garden.rb
Fix for [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_garden-install_bottle-homebrew-amd64&build=253)](https://build.osrfoundation.org/view/ign-garden/job/ignition_garden-install_bottle-homebrew-amd64/253/) https://build.osrfoundation.org/view/ign-garden/job/ignition_garden-install_bottle-homebrew-amd64/253/
=> ignition-garden: fix test

Formula/ogre2.3.rb
=> Add OGRE2.3 formula

Formula/ignition-common5.rb
* It goes with https://github.com/gazebosim/gz-common/pull/393
=> gz-common5: depend on assimp

Formula/ignition-cmake3.rb, Formula/ignition-rendering7.rb
=> ignition-rendering7: use ogre2.3

Formula/ignition-common5.rb
Required for https://github.com/gazebosim/gz-common/pull/402
=> gz-common5: depend on libcsv

Formula/ignition-cmake3.rb, Formula/ignition-common5.rb, Formula/ignition-fuel-tools8.rb, Formula/ignition-gui7.rb, Formula/ignition-launch6.rb, Formula/ignition-math7.rb, Formula/ignition-msgs9.rb, Formula/ignition-physics6.rb, Formula/ignition-plugin2.rb, Formula/ignition-rendering7.rb, Formula/ignition-sensors7.rb, Formula/ignition-tools2.rb, Formula/ignition-transport12.rb, Formula/ignition-utils2.rb, Formula/sdformat13.rb
* Part of https://github.com/gazebo-tooling/release-tools/issues/578
=> Use Garden stable branches

Formula/ignition-gazebo7.rb
* Part of https://github.com/gazebo-tooling/release-tools/issues/578
* Follow up to https://github.com/osrf/homebrew-simulation/pull/1985
=> Update gz-sim7 branch

Formula/gazebo11.rb, Formula/gazebo9.rb, Formula/gz-tools2.rb
=> gz-tools2: conflicts_with gazebo9 / gazebo11

Formula/gz-launch6.rb, Formula/gz-sim7.rb
Forgot to call build bottle in #2063 so bumping rev to get a new one
=> Bump rev in gz-launch6/gz-sim7 to build bottle

Formula/chrono-engine.rb
* Update to most recent tag
* :build depend on eigen
* depend on irrlicht
* Remove outdated patch and caveats
* Add test
* Fix cmake config install path
=> chrono-engine 7.0.3

Formula/gazebo11.rb
=> gazebo11: revision bump for boost

Formula/gazebo9.rb
=> gazebo9: revision bump for boost

Formula/ignition-edifice.rb, Formula/ignition-fuel-tools6.rb, Formula/ignition-gazebo5.rb, Formula/ignition-gui5.rb, Formula/ignition-launch4.rb, Formula/ignition-msgs7.rb, Formula/ignition-physics4.rb, Formula/ignition-rendering5.rb, Formula/ignition-sensors5.rb, Formula/ignition-transport10.rb, Formula/sdformat11.rb
=> Disable deprecated edifice formulae

Formula/ignition-transport2.rb, Formula/ignition-transport3.rb, Formula/sdformat5.rb
=> Deprecate other EOL formulae

Formula/ignition-physics5.rb
Cherry-picked ignition-physics5 changes from #2108.
=> ignition-physics5: build monterey bottle

Formula/ignition-cmake2.rb, Formula/ignition-rendering6.rb
=> ignition-rendering6: test both ogre components

.github/workflows/main.yml
I'm hoping this will fix the `brew doctor` issues with the open pull requests.
=> workflow: runs-on ubuntu-22.04

Formula/ignition-rendering3.rb
Signed-off-by: Nate Koenig <nate@openrobotics.org>
Bump revision in order to fix(create) bottle.
=> ignition-rendering3: revision bump

Formula/gz-common5.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2161
=> gz-common5: remove broken bottles

Formula/gz-common5.rb
=> gz-common5: revision bump for gdal

Aliases/gz-rendering8, Formula/gz-rendering8.rb
Removed gz-rendering8 alias and added gz-rendering8.rb formula
=> gz-rendering8: new formula

Formula/gz-gui8.rb, Formula/gz-launch7.rb, Formula/gz-rendering8.rb, Formula/gz-sensors8.rb, Formula/gz-sim8.rb
Needed for homebrew to clone the `main` branch instead of `master`
=> Use main branch in Harmonic formulas

Formula/gazebo11.rb
=> gazebo11: revision bump for dartsim

Formula/gazebo11.rb
=> gazebo11: rebuild bottle for bullet 3.25

Formula/dartsim@6.10.0.rb, Formula/gz-physics6.rb, Formula/ignition-physics2.rb, Formula/ignition-physics5.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2188
=> Rebuild dartsim and gz-physics* bottles for bullet 3.25

Formula/ignition-cmake1.rb, Formula/ignition-common0.rb, Formula/ignition-common2.rb, Formula/ignition-fuel-tools0.rb, Formula/ignition-fuel-tools2.rb, Formula/ignition-math3.rb, Formula/ignition-math5.rb, Formula/ignition-math@1.rb, Formula/ignition-msgs0.rb, Formula/ignition-msgs2.rb, Formula/ignition-plugin0.rb, Formula/ignition-rendering0.rb, Formula/ignition-transport2.rb, Formula/ignition-transport3.rb, Formula/ignition-transport5.rb, Formula/sdformat.rb, Formula/sdformat3.rb, Formula/sdformat4.rb, Formula/sdformat5.rb, Formula/sdformat7.rb
=> Disable formulae deprecated since 2019

Formula/ignition-math6.rb
Need to bump revision for python
=> ignition-math6: remove broken bottle

Aliases/gz-fuel-tools9, Formula/gz-fuel-tools9.rb
Signed-off-by: Ian Chen <ichen@openrobotics.org>
=> gz-fuel-tools9: depend on gz-msgs10

Formula/ignition-citadel.rb, Formula/ignition-fortress.rb, Formula/ignition-gazebo6.rb, Formula/ignition-math6.rb
=> gz-math6: use python@3.11, rebuild bottles

.github/workflows/main.yml
Trying to fix CI errors in https://github.com/osrf/homebrew-simulation/pull/2216
=> workflow: tap homebrew/core explicitly

.github/ISSUE_TEMPLATE/broken_bottle.md, .github/ISSUE_TEMPLATE/bug.md
Also request `brew config` in new issues.
=> Add issue template for broken bottles

Formula/gazebo11.rb, Formula/gz-common5.rb, Formula/ignition-common3.rb, Formula/ignition-common4.rb
=> Remove bottles broken by ffmpeg 6.0

Formula/gz-sim7.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gazebo6.rb
=> Remove broken gz-sim* bottles for ffmpeg 6

Formula/gz-common5.rb
=> gz-common5: revision bump for rebuild

Formula/ignition-common4.rb, Formula/ignition-gazebo6.rb, Formula/ignition-launch5.rb
=> gz-common4, sim6, launch5: rebuild bottles

Formula/ignition-common3.rb, Formula/ignition-gazebo3.rb, Formula/ignition-launch2.rb
=> gz-common3, sim3, launch2: rebuild bottles

Formula/gazebo11.rb
part of https://github.com/osrf/homebrew-simulation/issues/2241
=> gazebo11: revision bump for rebuild

Formula/gazebo11.rb, Formula/gazebo9.rb, Formula/gz-fuel-tools8.rb, Formula/gz-garden.rb, Formula/gz-gui7.rb, Formula/gz-launch6.rb, Formula/gz-msgs10.rb, Formula/gz-msgs9.rb, Formula/gz-sensors7.rb, Formula/gz-sim7.rb, Formula/gz-transport12.rb, Formula/gz-transport13.rb, Formula/ignition-citadel.rb, Formula/ignition-fortress.rb, Formula/ignition-fuel-tools4.rb, Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui3.rb, Formula/ignition-gui6.rb, Formula/ignition-launch2.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs1.rb, Formula/ignition-msgs5.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors3.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb, Formula/ignition-transport4.rb, Formula/ignition-transport8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2274.
=> Remove broken bottles, depend on protobuf@21

Formula/ignition-fuel-tools4.rb, Formula/ignition-gui3.rb, Formula/ignition-sensors3.rb
=> Rebuild some citadel bottles

Formula/ignition-fuel-tools7.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb
=> Rebuild some fortress bottles

Formula/gz-msgs9.rb, Formula/gz-transport12.rb
Part of #2274. I'm having trouble with other dependent packages and will rebuild them when possible.
=> gz-msgs9, gz-transport12: rebuild bottles

Formula/ignition-gazebo3.rb, Formula/ignition-gazebo6.rb
=> gz-sim3, gz-sim6: add patch to support new protobuf

Formula/ignition-fortress.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui6.rb, Formula/ignition-launch5.rb
=> Rebuild rest of Fortress for protobuf

Formula/ignition-citadel.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gui3.rb, Formula/ignition-launch2.rb
=> Rebuild rest of Citadel for protobuf

Formula/gz-gui7.rb, Formula/gz-sensors7.rb, Formula/gz-sim7.rb
=> gz-gui7, gz-sensors7, gz-sim: patch for protobuf

Formula/gz-launch6.rb, Formula/gz-launch7.rb, Formula/ignition-launch2.rb, Formula/ignition-launch5.rb
Part of #2302. Also remove some broken bottles.
=> gz-launch*: explicitly depend on protobuf

Formula/ignition-fuel-tools4.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gui3.rb, Formula/ignition-launch2.rb, Formula/ignition-msgs5.rb, Formula/ignition-sensors3.rb, Formula/ignition-transport8.rb
=> Rebuild citadel bottles for protobuf again

Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui6.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb
=> Rebuild fortress bottles for protobuf again

Formula/gz-rendering7.rb
=> gz-rendering7: remove bottle broken by geospatial

Formula/gz-common5.rb, Formula/gz-fuel-tools8.rb, Formula/gz-garden.rb, Formula/gz-gui7.rb, Formula/gz-launch6.rb, Formula/gz-physics6.rb, Formula/gz-rendering7.rb, Formula/gz-sensors7.rb, Formula/gz-sim7.rb
=> Garden: rebuild bottles for protobuf

Formula/gazebo11.rb, Formula/gz-fuel-tools8.rb, Formula/gz-gui7.rb, Formula/gz-launch6.rb, Formula/gz-msgs9.rb, Formula/gz-sensors7.rb, Formula/gz-sim7.rb, Formula/gz-transport12.rb, Formula/ignition-fuel-tools4.rb, Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui3.rb, Formula/ignition-gui6.rb, Formula/ignition-launch2.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs5.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors3.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb, Formula/ignition-transport8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2314.
=> Remove bottles broken by protobuf 23.4

.github/ISSUE_TEMPLATE/broken_bottle.md
=> Fix typo in issue template

Formula/gz-fuel-tools8.rb, Formula/gz-gui7.rb, Formula/gz-launch6.rb, Formula/gz-msgs9.rb, Formula/gz-sensors7.rb, Formula/gz-sim7.rb, Formula/gz-transport12.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2314.
=> Rebuild garden bottles for protobuf 23.4

Formula/ignition-fuel-tools4.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gui3.rb, Formula/ignition-launch2.rb, Formula/ignition-msgs5.rb, Formula/ignition-sensors3.rb, Formula/ignition-transport8.rb
Part of #2314.
~~~
for f in $(grep -L '^ *bottle do' $(grep -rnI depend.*ignition ignition-citadel | sed -e 's@.* "@@' -e 's@"@.rb@'))
do
done
~~~
=> Rebuild citadel bottles for protobuf 23.4

Formula/gazebo11.rb
=> gazebo11: rebuild bottle for protobuf

Aliases/sdformat14, Formula/sdformat14.rb
=> sdformat14: new formula for Harmonic

Formula/gz-common5.rb, Formula/gz-fuel-tools8.rb, Formula/gz-garden.rb, Formula/gz-gui7.rb, Formula/gz-launch6.rb, Formula/gz-physics6.rb, Formula/gz-rendering7.rb, Formula/gz-sensors7.rb, Formula/gz-sim7.rb
=> Remove bottles broken by gdal 3.7.1

Aliases/gz-physics7, Formula/gz-physics7.rb
=> Bumps in harmonic : ci_matching_branch/bump_harmonic_gz-physics7

Formula/gz-common5.rb, Formula/gz-fuel-tools8.rb, Formula/gz-garden.rb, Formula/gz-gui7.rb, Formula/gz-launch6.rb, Formula/gz-physics6.rb, Formula/gz-rendering7.rb, Formula/gz-sensors7.rb, Formula/gz-sim7.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2328
=> Rebuild Garden bottles for gdal

Formula/gz-sim8.rb
=> Bumps in harmonic : ci_matching_branch/bump_harmonic_gz-sim8

Formula/gz-launch7.rb
=> gz-launch7: fix version

Formula/ogre1.9.rb, Formula/ogre2.3.rb
Cosmetic changes made to allow building bottles.
=> ogre1.9, ogre2.3: build ventura bottles

Formula/gz-common5.rb, Formula/gz-fuel-tools8.rb, Formula/gz-gui7.rb, Formula/gz-msgs9.rb, Formula/gz-physics6.rb, Formula/gz-plugin2.rb, Formula/gz-rendering7.rb, Formula/gz-sensors7.rb, Formula/gz-transport12.rb, Formula/sdformat13.rb
Everything below gz-sim7.
Part of https://github.com/osrf/homebrew-simulation/issues/2337.
=> Garden: more ventura bottles

Formula/gz-transport13.rb
Needed for https://github.com/gazebosim/gz-sim/pull/2081
=> gz-transport13: install python bindings

Formula/gz-msgs10.rb
Needed for https://github.com/gazebosim/gz-sim/pull/2081
=> gz-msgs10: install python bindings

Formula/gazebo11.rb, Formula/gz-fuel-tools8.rb, Formula/gz-gui7.rb, Formula/gz-launch6.rb, Formula/gz-msgs9.rb, Formula/gz-sensors7.rb, Formula/gz-sim7.rb, Formula/gz-transport12.rb, Formula/ignition-fuel-tools4.rb, Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui3.rb, Formula/ignition-gui6.rb, Formula/ignition-launch2.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs5.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors3.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb, Formula/ignition-transport8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2339.
Generated using the loop in https://github.com/osrf/homebrew-simulation/issues/2314#issuecomment-1626396384.
=> Remove broken protobuf bottles

Formula/ignition-cmake2.rb, Formula/ignition-common3.rb, Formula/ignition-common4.rb, Formula/ignition-math6.rb, Formula/ignition-plugin1.rb, Formula/ignition-tools.rb, Formula/ignition-utils1.rb
Cosmetic changes the the following formulae:
* gz-cmake2
* gz-common3
* gz-common4
* gz-math6
* gz-plugin1
Part of https://github.com/osrf/homebrew-simulation/issues/2337.
=> Ventura bottles for citadel/fortress base

Formula/gz-fuel-tools8.rb, Formula/gz-gui7.rb, Formula/gz-launch6.rb, Formula/gz-msgs9.rb, Formula/gz-sensors7.rb, Formula/gz-sim7.rb, Formula/gz-transport12.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2339.
=> Rebuild garden bottles

Formula/ignition-physics5.rb, Formula/ignition-rendering6.rb, Formula/ogre2.2.rb, Formula/sdformat12.rb
* sdformat12
* gz-physics5
* ogre2.2
* gz-rendering6
Part of #2337.
=> Fortress: build Ventura bottles part 2

Formula/dartsim@6.10.0.rb, Formula/ignition-physics2.rb
* dartsim@6.10.0
* gz-physics2
Part of #2337.
=> Citadel: build Ventura bottles part 3

Formula/ignition-fuel-tools4.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gui3.rb, Formula/ignition-launch2.rb, Formula/ignition-msgs5.rb, Formula/ignition-sensors3.rb, Formula/ignition-transport8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2339.
=> Citadel: rebuild bottles after protobuf

README.md
Copied from https://github.com/osrf/homebrew-simulation/issues/2314#issuecomment-1626396384.
=> README: add snippet to remove broken bottles

Formula/ignition-citadel.rb, Formula/ignition-gazebo3.rb, Formula/ignition-launch2.rb
=> Citadel: build remaining Ventura bottles

Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui6.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb
=> Fortress: rebuild bottles after protobuf upgrade

Formula/gazebo11.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2339
=> gazebo11: rebuild after protobuf upgrade

Formula/gazebo11.rb, Formula/simbody.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2337.
=> simbody, gazebo11: build Ventura bottles

Formula/gz-garden.rb
=> gz-garden: build ventura bottle

Formula/gazebo11.rb, Formula/gz-fuel-tools8.rb, Formula/gz-fuel-tools9.rb, Formula/gz-gui7.rb, Formula/gz-gui8.rb, Formula/gz-launch6.rb, Formula/gz-launch7.rb, Formula/gz-msgs10.rb, Formula/gz-msgs9.rb, Formula/gz-sensors7.rb, Formula/gz-sensors8.rb, Formula/gz-sim7.rb, Formula/gz-sim8.rb, Formula/gz-transport12.rb, Formula/gz-transport13.rb, Formula/ignition-fuel-tools4.rb, Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui3.rb, Formula/ignition-gui6.rb, Formula/ignition-launch2.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs5.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors3.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb, Formula/ignition-transport8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2394.
=> Remove bottles broken by protobuf 24.3

Formula/gz-fuel-tools8.rb, Formula/gz-gui7.rb, Formula/gz-launch6.rb, Formula/gz-msgs9.rb, Formula/gz-sensors7.rb, Formula/gz-sim7.rb, Formula/gz-transport12.rb
Part of https://github.com/osrf/homebrew-simulation/pull/2395
=> Rebuild garden bottles for protobuf

Formula/gz-fuel-tools9.rb, Formula/gz-gui8.rb, Formula/gz-launch7.rb, Formula/gz-msgs10.rb, Formula/gz-sensors8.rb, Formula/gz-sim8.rb, Formula/gz-transport13.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2394
=> Rebuild harmonic bottles for protobuf 24.3

Formula/gz-plugin2.rb
New bottles aren't needed for this
=> gz-plugin2: clean up syntax in test, add comments

Formula/gz-gui7.rb, Formula/gz-launch6.rb, Formula/gz-sim7.rb, Formula/ogre2.3.rb
=> Garden: rpath issues in gui plugins, ogre2.3

Formula/gz-gui8.rb, Formula/gz-launch7.rb, Formula/gz-physics7.rb, Formula/gz-rendering8.rb, Formula/gz-sim8.rb, Formula/gz-transport13.rb
Repeat #2409 and #2410 for Harmonic formulae.
=> Harmonic: fix rpath issues and add tests

Formula/gazebo11.rb, Formula/gz-fuel-tools8.rb, Formula/gz-fuel-tools9.rb, Formula/gz-gui7.rb, Formula/gz-gui8.rb, Formula/gz-launch6.rb, Formula/gz-launch7.rb, Formula/gz-msgs10.rb, Formula/gz-msgs9.rb, Formula/gz-sensors7.rb, Formula/gz-sensors8.rb, Formula/gz-sim7.rb, Formula/gz-sim8.rb, Formula/gz-transport12.rb, Formula/gz-transport13.rb, Formula/ignition-fuel-tools4.rb, Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui3.rb, Formula/ignition-gui6.rb, Formula/ignition-launch2.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs5.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors3.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb, Formula/ignition-transport8.rb
Part of #2455.
Implemented with script from https://github.com/osrf/homebrew-simulation#to-disable-broken-bottles
=> Remove broken bottles for protobuf 24.4

Formula/gz-fuel-tools9.rb, Formula/gz-gui8.rb, Formula/gz-launch7.rb, Formula/gz-msgs10.rb, Formula/gz-sensors8.rb, Formula/gz-sim8.rb, Formula/gz-transport13.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2455.
=> Rebuild harmonic bottles for protobuf 24.4

Formula/gz-fuel-tools8.rb, Formula/gz-gui7.rb, Formula/gz-launch6.rb, Formula/gz-msgs9.rb, Formula/gz-sensors7.rb, Formula/gz-sim7.rb, Formula/gz-transport12.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2455.
=> Rebuild garden bottles for protobuf 24.4

Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui6.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb
=> Rebuild fortress bottles for protobuf 24.4

Formula/ignition-fuel-tools4.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gui3.rb, Formula/ignition-launch2.rb, Formula/ignition-msgs5.rb, Formula/ignition-sensors3.rb, Formula/ignition-transport8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2455.
=> Rebuild citadel bottles for protobuf 24.4

Aliases/gz-cmake4, Formula/gz-cmake4.rb
=> gz-cmake4: new formula for ionic

Aliases/gz-fuel-tools10, Aliases/gz-gui9, Aliases/gz-launch8, Aliases/gz-physics8, Aliases/gz-rendering9, Aliases/gz-sensors9, Aliases/gz-sim9, Aliases/gz-transport14, Aliases/sdformat15
=> Add aliases for libraries that are being bumped for Ionic

Aliases/gz-ionic
Part of https://github.com/gazebo-tooling/release-tools/issues/1026
=> gz-ionic: alias to gz-harmonic

Aliases/gz-utils3, Formula/gz-utils3.rb
=> gz-utils3: new formula for ionic

Aliases/gz-math8, Formula/gz-math8.rb
=> gz-math8: new formula for ionic

Aliases/sdformat15, Formula/sdformat15.rb
=> sdformat15: new formula for ionic

Aliases/gz-plugin3, Formula/gz-plugin3.rb
=> gz-plugin3: new formula for ionic

Aliases/gz-msgs11, Formula/gz-msgs11.rb
=> gz-msgs11: new formula for ionic

Aliases/gz-common6, Formula/gz-common6.rb
=> gz-common6: new formula for ionic

Formula/sdformat15.rb
=> Bumps in ionic : ci_matching_branch/bump_ionic_sdformat15

Aliases/gz-transport14, Formula/gz-transport14.rb
=> Bumps in ionic : ci_matching_branch/bump_ionic_gz-transport14

Aliases/gz-fuel-tools10, Formula/gz-fuel-tools10.rb
=> Bumps in ionic : ci_matching_branch/bump_ionic_gz-fuel-tools10

Aliases/gz-gui9, Formula/gz-gui9.rb
=> Bumps in ionic : ci_matching_branch/bump_ionic_gz-gui9

Formula/gazebo11.rb, Formula/gz-fuel-tools8.rb, Formula/gz-fuel-tools9.rb, Formula/gz-gui7.rb, Formula/gz-gui8.rb, Formula/gz-launch6.rb, Formula/gz-launch7.rb, Formula/gz-msgs10.rb, Formula/gz-msgs9.rb, Formula/gz-sensors7.rb, Formula/gz-sensors8.rb, Formula/gz-sim7.rb, Formula/gz-sim8.rb, Formula/gz-transport12.rb, Formula/gz-transport13.rb, Formula/ignition-fuel-tools4.rb, Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui3.rb, Formula/ignition-gui6.rb, Formula/ignition-launch2.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs5.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors3.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb, Formula/ignition-transport8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2483.
Implemented with script from https://github.com/osrf/homebrew-simulation#to-disable-broken-bottles
=> Remove bottles broken by protobuf 25

Formula/gz-fuel-tools8.rb, Formula/gz-gui7.rb, Formula/gz-launch6.rb, Formula/gz-msgs9.rb, Formula/gz-sensors7.rb, Formula/gz-sim7.rb, Formula/gz-transport12.rb
Part of #2483.
~~~
for f in $(grep -L '^ *bottle do' $(grep -rnI depend.*gz gz-garden.rb | sed -e 's@.* "@@' -e 's@"@.rb@'))
do
done
~~~
=> Rebuild garden bottles for protobuf 25

Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui6.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb
Part of #2483.
~~~
for f in $(grep -L '^ *bottle do' $(grep -rnI depend.*ignition ignition-fortress.rb | sed -e 's@.* "@@' -e 's@"@.rb@'))
do
done
~~~
=> Rebuild fortress bottles for protobuf 25

Formula/gazebo11.rb
=> Rebuild gazebo11 bottle for protobuf 25

Formula/gazebo11.rb, Formula/gz-fuel-tools8.rb, Formula/gz-fuel-tools9.rb, Formula/gz-gui7.rb, Formula/gz-gui8.rb, Formula/gz-launch6.rb, Formula/gz-launch7.rb, Formula/gz-msgs10.rb, Formula/gz-msgs9.rb, Formula/gz-sensors7.rb, Formula/gz-sensors8.rb, Formula/gz-sim7.rb, Formula/gz-sim8.rb, Formula/gz-transport12.rb, Formula/gz-transport13.rb, Formula/ignition-fuel-tools4.rb, Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui3.rb, Formula/ignition-gui6.rb, Formula/ignition-launch2.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs5.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors3.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb, Formula/ignition-transport8.rb
Implemented with script from https://github.com/osrf/homebrew-simulation#to-disable-broken-bottles
=> Remove bottles broken by protobuf 25.1

Formula/gz-fuel-tools9.rb, Formula/gz-gui8.rb, Formula/gz-launch7.rb, Formula/gz-msgs10.rb, Formula/gz-sensors8.rb, Formula/gz-sim8.rb, Formula/gz-transport13.rb
~~~
for f in $(grep -L '^ *bottle do' $(grep -rnI depend.*gz gz-harmonic.rb | sed -e 's@.* "@@' -e 's@"@.rb@'))
do
done
~~~
=> Rebuild harmonic bottles for protobuf 25.1

Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui6.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb
~~~
for f in $(grep -L '^ *bottle do' $(grep -rnI depend.*ignition ignition-fortress.rb | sed -e 's@.* "@@' -e 's@"@.rb@'))
do
done
~~~
=> Rebuild fortress bottles for protobuf 25.1

Formula/gazebo11.rb, Formula/ignition-fuel-tools4.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gui3.rb, Formula/ignition-launch2.rb, Formula/ignition-msgs5.rb, Formula/ignition-sensors3.rb, Formula/ignition-transport8.rb
~~~
for f in $(grep -L '^ *bottle do' $(grep -rnI depend.*ignition ignition-citadel.rb | sed -e 's@.* "@@' -e 's@"@.rb@'))
do
done
brew bump-revision --message="rebuild bottle" gazebo11
~~~
=> Rebuild citadel, gazebo11 bottles for protobuf 25.1

Formula/gz-common5.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2499.
=> gz-common5: remove bottle broken by gdal

Formula/gz-common5.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2499.
=> gz-common5: rebuild bottle for gdal 3.8

Formula/gazebo11.rb
Part of #2505, follow up to #2507.
=> gazebo11: depend on urdfdom, remove bottle

Formula/gz-physics7.rb, Formula/sdformat14.rb
Part of #2505.
~~~
for f in $(grep -L '^ *bottle do' $(grep -rnI 'depend.*"[gs][zd][-f]' gz-harmonic.rb | sed -e 's@.* "@@' -e 's@"@.rb@'))
do
done
~~~
=> Rebuild harmonic bottles for urdfdom 4.0.0

Formula/cmake@3.21.4.rb, Formula/gazebo10.rb, Formula/gazebo7.rb, Formula/gazebo9.rb, Formula/haptix-comm.rb, Formula/ignition-cmake0.rb, Formula/ignition-common1.rb, Formula/ignition-fuel-tools1.rb, Formula/ignition-math2.rb, Formula/ignition-math4.rb, Formula/ignition-msgs1.rb, Formula/ignition-rndf0.rb, Formula/ignition-transport.rb, Formula/ignition-transport4.rb, Formula/sdformat6.rb, Formula/tbb@2020_u3.rb, Formula/tinyxml2@6.2.0.rb
This disables and deprecates a bunch of old formulae.
=> Disable / deprecate old formulae

Formula/tinyxml1.rb
=> tinyxml1 extracted from homebrew/core/tinyxml

Formula/ignition-fortress.rb, Formula/ignition-gazebo6.rb, Formula/ignition-launch5.rb, Formula/ignition-physics5.rb, Formula/ignition-sensors6.rb, Formula/sdformat12.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2503 and https://github.com/osrf/homebrew-simulation/issues/2505.
=> Rebuild fortress bottles for urdfdom 4.0.0

Formula/gz-harmonic.rb, Formula/gz-launch7.rb, Formula/gz-sensors8.rb, Formula/gz-sim8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2503.
=> Rebuild more harmonic bottles for urdfdom 4.0.0

Formula/gazebo11.rb, Formula/gz-fuel-tools8.rb, Formula/gz-fuel-tools9.rb, Formula/gz-gui7.rb, Formula/gz-gui8.rb, Formula/gz-launch6.rb, Formula/gz-launch7.rb, Formula/gz-msgs10.rb, Formula/gz-msgs9.rb, Formula/gz-sensors7.rb, Formula/gz-sensors8.rb, Formula/gz-sim7.rb, Formula/gz-sim8.rb, Formula/gz-transport12.rb, Formula/gz-transport13.rb, Formula/ignition-fuel-tools4.rb, Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui3.rb, Formula/ignition-gui6.rb, Formula/ignition-launch2.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs5.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors3.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb, Formula/ignition-transport8.rb
Implemented with script from https://github.com/osrf/homebrew-simulation#to-disable-broken-bottles
Merge after the following is merged:
* https://github.com/Homebrew/homebrew-core/pull/159459
=> Remove bottles broken by protobuf 25.2

Formula/gz-fuel-tools9.rb, Formula/gz-gui8.rb, Formula/gz-launch7.rb, Formula/gz-sensors8.rb, Formula/gz-sim8.rb, Formula/gz-transport13.rb
=> Rebuild harmonic bottles for protobuf 25.2

Formula/ignition-fuel-tools4.rb, Formula/ignition-gui3.rb, Formula/ignition-msgs5.rb, Formula/ignition-sensors3.rb, Formula/ignition-transport8.rb
=> Rebuild most citadel bottles

Formula/gazebo11.rb
=> gazebo11: revision bump rebuild bottle

Formula/gz-sim7.rb, Formula/sdformat13.rb
Part of https://github.com/gazebosim/gz-sim/issues/2249.
=> Garden: fix finding python version

Formula/gz-msgs10.rb, Formula/gz-sim8.rb, Formula/gz-transport13.rb, Formula/sdformat14.rb
Part of https://github.com/gazebosim/gz-sim/issues/2249.
=> Harmonic: fix finding python version

Formula/ignition-gazebo6.rb, Formula/ignition-launch5.rb
=> Fortress: finish rebuilding bottles for protobuf

Formula/ignition-gazebo3.rb, Formula/ignition-launch2.rb
=> Citadel: finish rebuilding bottles for protobuf

Formula/gz-gui7.rb, Formula/gz-gui8.rb, Formula/gz-gui9.rb, Formula/gz-launch6.rb, Formula/gz-launch7.rb, Formula/gz-launch8.rb, Formula/gz-physics6.rb, Formula/gz-physics7.rb, Formula/gz-physics8.rb, Formula/gz-rendering7.rb, Formula/gz-rendering8.rb, Formula/gz-rendering9.rb, Formula/gz-sim7.rb, Formula/gz-sim8.rb, Formula/gz-sim9.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui6.rb, Formula/ignition-launch5.rb, Formula/ignition-physics5.rb, Formula/ignition-rendering6.rb, Formula/ogre2.2.rb, Formula/ogre2.3.rb
Required as of brew 4.2.7 due to https://github.com/Homebrew/brew/pull/16540.
This can be merged without new bottles.
=> Use SystemCommand::Mixin to fix tests

Aliases/ignition-msgs
This is needed since https://github.com/Homebrew/brew/pull/16622.
=> Remove ignition-msgs alias

Formula/gz-gui9.rb, Formula/gz-launch8.rb
* gz-gui9 and gz-launch8
Partial fix for https://github.com/osrf/buildfarm-tools/issues/27#issuecomment-1938625007.
=> Ionic: fix some plugin paths

Formula/gz-garden.rb, Formula/gz-harmonic.rb
=> Remove more bottles downstream of gz-common5

Formula/gz-common5.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2504.
=> gz-common5: rebuild bottle for tinyxml2

Formula/gz-transport13.rb, Formula/sdformat14.rb
Part of #2504. Patches from https://github.com/gazebosim/sdformat/pull/1367 and https://github.com/gazebosim/gz-transport/pull/472.
=> Harmonic: patches to fix finding python

Formula/gz-fuel-tools9.rb, Formula/gz-gui8.rb, Formula/gz-harmonic.rb, Formula/gz-launch7.rb, Formula/gz-msgs10.rb, Formula/gz-physics7.rb, Formula/gz-sensors8.rb, Formula/gz-sim8.rb, Formula/gz-transport13.rb, Formula/sdformat14.rb
Part of #2504.
~~~
for f in $(grep -L '^ *bottle do' $(grep -rnI 'depend.*"[gs][zd][-f]' gz-harmonic.rb | sed -e 's@.* "@@' -e 's@"@.rb@'))
do
done
brew bump-revision gz-harmonic --message="rebuild bottle"
~~~
=> Harmonic: rebuild bottles for tinyxml2

Formula/ignition-common4.rb, Formula/ignition-fortress.rb, Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui6.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs8.rb, Formula/ignition-physics5.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb, Formula/sdformat12.rb
Part of #2504.
~~~
for f in $(grep -L '^ *bottle do' $(grep -rnI 'depend.*"[is][gd][nf]' ignition-fortress.rb | sed -e 's@.* "@@' -e 's@"@.rb@'))
do
done
brew bump-revision ignition-fortress --message="rebuild bottle"
~~~
=> Fortress: rebuild bottles for tinyxml2

Formula/gz-fuel-tools9.rb, Formula/gz-gui8.rb, Formula/gz-harmonic.rb, Formula/gz-launch7.rb, Formula/gz-msgs10.rb, Formula/gz-sensors8.rb, Formula/gz-sim8.rb, Formula/gz-transport13.rb
Part of #2571.
~~~
for f in $(grep -L '^ *bottle do' $(grep -rnI 'depend.*"[gs][zd][-f]' gz-harmonic.rb | sed -e 's@.* "@@' -e 's@"@.rb@'))
do
done
brew bump-revision gz-harmonic --message="rebuild bottle"
~~~
=> Harmonic: rebuild bottles for protobuf

Formula/ignition-gazebo3.rb, Formula/ignition-gui3.rb, Formula/ignition-launch2.rb, Formula/ignition-sensors3.rb
Part of #2571.
~~~
for f in $(grep -L '^ *bottle do' $(grep -rnI 'depend.*"[is][gd][nf]' ignition-citadel.rb | sed -e 's@.* "@@' -e 's@"@.rb@'))
do
done
~~~
=> Citadel: rebuild bottles for protobuf

Formula/gz-math8.rb, Formula/gz-msgs11.rb, Formula/gz-sim9.rb, Formula/gz-transport14.rb, Formula/sdformat15.rb
* gz-math8
* gz-msgs11
* gz-sim9
* gz-transport14
* sdformat15
Tested with `gz-sim9`:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_sim9-install_bottle-homebrew-amd64&build=70)](https://build.osrfoundation.org/view/gz-ionic/job/gz_sim9-install_bottle-homebrew-amd64/70/) https://build.osrfoundation.org/view/gz-ionic/job/gz_sim9-install_bottle-homebrew-amd64/70/
=> Ionic: use python@3.12

Formula/gz-garden.rb, Formula/gz-harmonic.rb, Formula/gz-math7.rb, Formula/gz-msgs10.rb, Formula/gz-sim7.rb, Formula/gz-sim8.rb, Formula/gz-transport13.rb, Formula/sdformat13.rb, Formula/sdformat14.rb
Part of #2580.
Testing:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_sim8-install_bottle-homebrew-amd64&build=71)](https://build.osrfoundation.org/view/gz-harmonic/job/gz_sim8-install_bottle-homebrew-amd64/71/) https://build.osrfoundation.org/view/gz-harmonic/job/gz_sim8-install_bottle-homebrew-amd64/71/
=> Garden, Harmonic: remove broken bottles, use python@3.12

Formula/gz-math7.rb, Formula/gz-msgs10.rb, Formula/gz-sim7.rb, Formula/gz-sim8.rb, Formula/gz-transport13.rb, Formula/sdformat13.rb, Formula/sdformat14.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2580. Follow-up to #2582.
=> Garden, Harmonic: rebuild bottles with python 3.12

Formula/gazebo11.rb, Formula/gz-fuel-tools8.rb, Formula/gz-fuel-tools9.rb, Formula/gz-gui7.rb, Formula/gz-gui8.rb, Formula/gz-launch6.rb, Formula/gz-launch7.rb, Formula/gz-msgs10.rb, Formula/gz-msgs9.rb, Formula/gz-sensors7.rb, Formula/gz-sensors8.rb, Formula/gz-sim7.rb, Formula/gz-sim8.rb, Formula/gz-transport12.rb, Formula/gz-transport13.rb, Formula/ignition-fuel-tools4.rb, Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui3.rb, Formula/ignition-gui6.rb, Formula/ignition-launch2.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs5.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors3.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb, Formula/ignition-transport8.rb
Related to https://github.com/osrf/homebrew-simulation/issues/2587
=> Disable broken bottles after abseil bump

Formula/ignition-fuel-tools4.rb, Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui3.rb, Formula/ignition-gui6.rb, Formula/ignition-launch2.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs5.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors3.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb, Formula/ignition-transport8.rb
=> Citadel, Fortress: rebuild bottles for abseil (#2587)

Formula/dartsim@6.10.0.rb, Formula/gazebo11.rb, Formula/gz-physics6.rb, Formula/gz-physics7.rb, Formula/ignition-physics2.rb, Formula/ignition-physics5.rb
=> Remove bottles broken by octomap 1.10

Formula/gz-fuel-tools9.rb, Formula/gz-gui8.rb, Formula/gz-launch7.rb, Formula/gz-msgs10.rb, Formula/gz-physics7.rb, Formula/gz-sensors8.rb, Formula/gz-sim8.rb, Formula/gz-transport13.rb
Part of #2611.
~~~
do
brew bump-revision --message="for protobuf" $f
done
~~~
=> Rebuild harmonic bottles for protobuf 26

Formula/gz-fuel-tools8.rb, Formula/gz-gui7.rb, Formula/gz-launch6.rb, Formula/gz-msgs9.rb, Formula/gz-physics6.rb, Formula/gz-sensors7.rb, Formula/gz-sim7.rb, Formula/gz-transport12.rb
Part of #2611.
~~~
do
brew bump-revision --message="for protobuf" $f
done
~~~
=> Rebuild garden bottles for protobuf 26

Formula/dartsim@6.10.0.rb, Formula/ignition-fuel-tools4.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gui3.rb, Formula/ignition-launch2.rb, Formula/ignition-msgs5.rb, Formula/ignition-physics2.rb, Formula/ignition-sensors3.rb, Formula/ignition-transport8.rb
Part of #2611.
~~~
do
brew bump-revision --message="for protobuf" $f
done
~~~
=> Rebuild citadel bottles for protobuf

Formula/gazebo11.rb
=> gazebo11: rebuild bottle for protobuf 26

Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui6.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs8.rb, Formula/ignition-physics5.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb
Part of #2611.
~~~
do
brew bump-revision --message="for protobuf" $f
done
~~~
=> Rebuild fortress bottles for protobuf

Formula/gz-fuel-tools8.rb, Formula/gz-gui7.rb, Formula/gz-launch6.rb, Formula/gz-physics6.rb, Formula/gz-rendering7.rb, Formula/gz-sensors7.rb, Formula/gz-sim7.rb
Part of #2628.
~~~
do
brew bump-revision --message="for ffmpeg" $f
done
~~~
=> Rebuild garden bottles for ffmpeg 7

Formula/ignition-common3.rb, Formula/ignition-fuel-tools4.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gui3.rb, Formula/ignition-launch2.rb, Formula/ignition-physics2.rb, Formula/ignition-rendering3.rb, Formula/ignition-sensors3.rb
Part of #2628.
~~~
do
brew bump-revision --message="for ffmpeg" $f
done
~~~
=> Rebuild citadel bottles for ffmpeg 7

Formula/ignition-common4.rb, Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui6.rb, Formula/ignition-launch5.rb, Formula/ignition-physics5.rb, Formula/ignition-rendering6.rb, Formula/ignition-sensors6.rb
Part of #2628.
~~~
do
brew bump-revision --message="for ffmpeg" $f
done
~~~
=> Rebuild fortress bottles for ffmpeg 7

Formula/gazebo11.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2628.
=> gazebo11: rebuild for ffmpeg7

Formula/gz-fuel-tools9.rb, Formula/gz-gui8.rb, Formula/gz-launch7.rb, Formula/gz-physics7.rb, Formula/gz-rendering8.rb, Formula/gz-sensors8.rb, Formula/gz-sim8.rb
Part of #2639.
~~~
do
brew bump-revision --message="for llvm" $f
done
~~~
=> Rebuild harmonic bottles for llvm

Formula/gz-fuel-tools8.rb, Formula/gz-gui7.rb, Formula/gz-launch6.rb, Formula/gz-physics6.rb, Formula/gz-rendering7.rb, Formula/gz-sensors7.rb, Formula/gz-sim7.rb
Part of #2639.
~~~
do
brew bump-revision --message="for llvm" $f
done
~~~
=> Rebuild garden bottles for llvm

Formula/gz-fuel-tools9.rb, Formula/gz-gui8.rb, Formula/gz-launch7.rb, Formula/gz-physics7.rb, Formula/gz-sim8.rb
Part of #2651.
Created using script from https://github.com/osrf/homebrew-simulation/pull/2610:
~~~
do
brew bump-revision --message="for llvm" $f
done
~~~
=> Rebuild harmonic bottles for gdal

Formula/gz-fuel-tools9.rb, Formula/gz-gui8.rb, Formula/gz-launch7.rb, Formula/gz-msgs10.rb, Formula/gz-sensors8.rb, Formula/gz-sim8.rb, Formula/gz-transport13.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2659.
Created using:
~~~
do
done
~~~
=> Rebuild harmonic bottles for protobuf

.github/workflows/main.yml
=> Fix brew test-bot github actions

Formula/gz-fuel-tools9.rb, Formula/gz-gui8.rb, Formula/gz-launch7.rb, Formula/gz-msgs10.rb, Formula/gz-sensors8.rb, Formula/gz-sim8.rb, Formula/gz-transport13.rb
Part of #2668.
Created using:
~~~
do
done
~~~
=> Rebuild harmonic bottles for protobuf 27.1

Formula/gz-fuel-tools8.rb, Formula/gz-gui7.rb, Formula/gz-launch6.rb, Formula/gz-msgs9.rb, Formula/gz-sensors7.rb, Formula/gz-sim7.rb, Formula/gz-transport12.rb
Part of #2668.
Created using:
~~~
do
done
~~~
=> Rebuild garden bottles for protobuf 27.1

Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui6.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2668.
Created using:
~~~
do
done
~~~
=> Rebuild fortress bottles for protobuf 27.1

Formula/ignition-fuel-tools4.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gui3.rb, Formula/ignition-launch2.rb, Formula/ignition-msgs5.rb, Formula/ignition-sensors3.rb, Formula/ignition-transport8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2668.
Created using:
~~~
do
done
~~~
=> Rebuild citadel bottles for protobuf 27.1

Formula/gazebo11.rb
=> gazebo11: rebuild bottle

Formula/gz-physics7.rb
Part of #2688.
~~~
do
brew bump-revision --message="rebuild for dartsim" $f
done
~~~
=> Rebuild harmonic bottles for dartsim 6.14.1

Formula/gz-physics6.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2688.
~~~
do
brew bump-revision --message="rebuild for dartsim" $f
done
~~~
=> Rebuild garden bottles for dartsim 6.14.1

Formula/ignition-physics5.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2688.
~~~
do
brew bump-revision --message="rebuild for dartsim" $f
done
~~~
=> Rebuild fortress bottles for dartsim 6.14.1

Formula/gazebo11.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2688.
=> Rebuild gazebo11 bottle for dartsim 6.14.1

Formula/gz-fuel-tools9.rb, Formula/gz-gui8.rb, Formula/gz-launch7.rb, Formula/gz-msgs10.rb, Formula/gz-sensors8.rb, Formula/gz-sim8.rb, Formula/gz-transport13.rb
Part of #2698.
Created using:
~~~
do
done
~~~
=> Rebuild harmonic bottles for protobuf 27.3

Formula/gz-fuel-tools8.rb, Formula/gz-fuel-tools9.rb, Formula/gz-gui7.rb, Formula/gz-gui8.rb, Formula/gz-launch6.rb, Formula/gz-launch7.rb, Formula/gz-launch8.rb, Formula/gz-msgs10.rb, Formula/gz-msgs9.rb, Formula/gz-sensors7.rb, Formula/gz-sensors8.rb, Formula/gz-sim7.rb, Formula/gz-sim8.rb, Formula/gz-sim9.rb, Formula/gz-transport12.rb, Formula/gz-transport13.rb, Formula/gz-transport14.rb
=> Fix more strict linkage warnings

Formula/ignition-fuel-tools4.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gui3.rb, Formula/ignition-launch2.rb, Formula/ignition-msgs5.rb, Formula/ignition-sensors3.rb, Formula/ignition-transport8.rb
Part of #2698.
Created using:
~~~
do
done
~~~
=> Rebuild citadel bottles for protobuf 27.3

Formula/gz-fuel-tools8.rb, Formula/gz-gui7.rb, Formula/gz-launch6.rb, Formula/gz-msgs9.rb, Formula/gz-sensors7.rb, Formula/gz-sim7.rb, Formula/gz-transport12.rb
Part of #2698.
Created using:
~~~
do
done
~~~
=> Rebuild garden bottles for protobuf 27.3

Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui6.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb
Part of #2698.
Created using:
~~~
do
done
~~~
=> Rebuild fortress bottles for protobuf 27.3

Formula/gazebo11.rb
=> gazebo11: rebuild bottle for protof 27.3

Formula/gz-gui9.rb
=> gz-gui9: use stable branch

Formula/gz-fuel-tools10.rb
=> Ionic: Use gz-fuel-tools10 stable branch

Formula/gz-common6.rb
=> gz-common6: use stable branch

Formula/gz-sim9.rb
=> gz-sim9: use stable branch

Formula/gz-cmake4.rb, Formula/gz-common6.rb, Formula/gz-fuel-tools10.rb, Formula/gz-gui9.rb, Formula/gz-ionic.rb, Formula/gz-launch8.rb, Formula/gz-math8.rb, Formula/gz-msgs11.rb, Formula/gz-physics8.rb, Formula/gz-plugin3.rb, Formula/gz-rendering9.rb, Formula/gz-sensors9.rb, Formula/gz-sim9.rb, Formula/gz-transport14.rb, Formula/gz-utils3.rb, Formula/sdformat15.rb
Pulls changes from
- https://github.com/osrf/homebrew-simulation/pull/2732
- https://github.com/osrf/homebrew-simulation/pull/2764
- https://github.com/osrf/homebrew-simulation/pull/2740
- https://github.com/osrf/homebrew-simulation/pull/2751
- https://github.com/osrf/homebrew-simulation/pull/2765
- https://github.com/osrf/homebrew-simulation/pull/2750
- https://github.com/osrf/homebrew-simulation/pull/2760
- https://github.com/osrf/homebrew-simulation/pull/2766
- https://github.com/osrf/homebrew-simulation/pull/2761
- https://github.com/osrf/homebrew-simulation/pull/2767
- https://github.com/osrf/homebrew-simulation/pull/2753
- https://github.com/osrf/homebrew-simulation/pull/2769
- https://github.com/osrf/homebrew-simulation/pull/2768
- …
=> Ionic prereleases

Formula/gazebo11.rb
Part of #2745, follow-up to #2775.
=> gazebo11: remove bottle broken by fmt

Formula/gazebo11.rb
Follow up https://github.com/osrf/homebrew-simulation/pull/2777 . Part of https://github.com/osrf/homebrew-simulation/issues/2745
=> gazebo11: rebuild broken bottle by fmt

Formula/gz-gui9.rb, Formula/gz-launch8.rb, Formula/gz-sim9.rb
=> ionic: Rebuild gz-gui9 and downstream bottles

Formula/gz-fuel-tools10.rb, Formula/gz-gui9.rb, Formula/gz-launch8.rb, Formula/gz-msgs11.rb, Formula/gz-sensors9.rb, Formula/gz-sim9.rb, Formula/gz-transport14.rb
Part of #2782.
Created using:
~~~
do
done
~~~
=> Rebuild ionic bottles for protobuf 28

Formula/gz-fuel-tools9.rb, Formula/gz-gui8.rb, Formula/gz-launch7.rb, Formula/gz-msgs10.rb, Formula/gz-sensors8.rb, Formula/gz-sim8.rb, Formula/gz-transport13.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2782.
Created using:
~~~
do
done
~~~
=> Rebuild harmonic bottles for protobuf 28

Formula/gz-fuel-tools8.rb, Formula/gz-gui7.rb, Formula/gz-launch6.rb, Formula/gz-msgs9.rb, Formula/gz-sensors7.rb, Formula/gz-sim7.rb, Formula/gz-transport12.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2782.
Created using:
~~~
do
done
~~~
=> Rebuild garden bottles for protobuf 28

Formula/ignition-fuel-tools4.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gui3.rb, Formula/ignition-launch2.rb, Formula/ignition-msgs5.rb, Formula/ignition-sensors3.rb, Formula/ignition-transport8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2782.
Created using:
~~~
do
done
~~~
=> Rebuild citadel bottles for protobuf 28

Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui6.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2782.
Created using:
~~~
do
done
~~~
=> Rebuild fortress bottles for protobuf 28

Formula/gazebo11.rb
=> gazebo11: rebuild bottle for protobuf 28

Formula/ogre2.3.rb
Minor whitespace change to support new bottle.
=> ogre2.3: sonoma bottle

Formula/gz-cmake3.rb, Formula/gz-common5.rb, Formula/gz-math7.rb, Formula/gz-plugin2.rb, Formula/gz-tools2.rb, Formula/gz-utils2.rb
Make trivial changes to formulae shared by Garden
and Harmonic in order to build sonoma bottles.
=> Build sonoma bottles for gz-cmake3, dependents

Formula/ignition-cmake2.rb, Formula/ignition-math6.rb, Formula/ignition-plugin1.rb, Formula/ignition-tools.rb, Formula/ignition-utils1.rb
Start with formulae shared between citadel, fortress.
=> Build sonoma bottles for gz-cmake2, dependents

Formula/ignition-common4.rb, Formula/ignition-physics5.rb, Formula/ignition-rendering6.rb, Formula/ogre2.2.rb, Formula/sdformat12.rb
Add a minor comment in order to build Sonoma bottles.
=> Fortress: build sonoma bottles part 2

Formula/gz-physics7.rb, Formula/gz-rendering8.rb, Formula/sdformat14.rb
Add minor comment to enable building Sonoma bottles.
=> Harmonic: build sonoma bottles part 2

Formula/gz-physics6.rb, Formula/gz-rendering7.rb, Formula/sdformat13.rb
Minor adjustment to comment in order to build bottles.
=> Garden: build sonoma bottles part 2

Formula/gz-fuel-tools9.rb, Formula/gz-gui8.rb, Formula/gz-launch7.rb, Formula/gz-msgs10.rb, Formula/gz-sensors8.rb, Formula/gz-sim8.rb, Formula/gz-transport13.rb
Part of #2791.
Created using:
~~~
do
done
~~~
=> Rebuild harmonic bottles for protobuf 28.2

Formula/gz-fuel-tools8.rb, Formula/gz-gui7.rb, Formula/gz-launch6.rb, Formula/gz-msgs9.rb, Formula/gz-sensors7.rb, Formula/gz-sim7.rb, Formula/gz-transport12.rb
Part of #2791.
Created using:
~~~
do
done
~~~
=> Rebuild garden bottles for protobuf 28.2

Formula/ignition-fuel-tools4.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gui3.rb, Formula/ignition-launch2.rb, Formula/ignition-msgs5.rb, Formula/ignition-sensors3.rb, Formula/ignition-transport8.rb
Part of #2791.
Created using:
~~~
do
done
~~~
=> Rebuild citadel bottles for protobuf 28.2

Formula/ignition-gui3.rb
Follow up to #2814, similar to https://github.com/osrf/homebrew-simulation/pull/2803.
=> gz-gui3: fix rpath for plugins and rebuild

Formula/ignition-gazebo3.rb, Formula/ignition-launch2.rb
Part of #2791, follow-up to #2828.
=> gz-sim3, gz-launch2: build sonoma bottles

Formula/gazebo11.rb
=> gazebo11: rebuild for protobuf 28.2

Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui6.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs8.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb
Part of #2837.
~~~
do
done
~~~
=> Rebuild fortress bottles for protobuf 28.3

Formula/gz-common6.rb, Formula/gz-fuel-tools10.rb, Formula/gz-physics8.rb, Formula/gz-rendering9.rb
=> Ionic: rebuild some gdal dependents

Formula/ignition-fuel-tools4.rb, Formula/ignition-gazebo3.rb, Formula/ignition-gui3.rb, Formula/ignition-launch2.rb, Formula/ignition-msgs5.rb, Formula/ignition-sensors3.rb, Formula/ignition-transport8.rb
Part of #2837.
~~~
do
done
~~~
=> Rebuild citadel bottles for protobuf 28.3

Formula/gazebo11.rb
=> gazebo11: revision bump to rebuild

Formula/gz-gui9.rb, Formula/gz-sensors9.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2837 and https://github.com/osrf/homebrew-simulation/issues/2845.
=> Rebuild more ionic bottles

Formula/gazebo11.rb, Formula/gz-physics6.rb, Formula/gz-physics7.rb, Formula/gz-physics8.rb, Formula/ignition-physics5.rb
Part of #2876.
Similar to https://github.com/osrf/homebrew-simulation/pull/2691, implemented using:
~~~
for f in $(.github/ci/bottled_dependents.sh dartsim)
do
done
~~~
=> Remove bottles broken by dartsim 6.15.0

Formula/gz-physics6.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2876.
=> gz-physics6: rebuild for dartsim

Formula/ignition-physics5.rb
=> ignition-physics5: rebuild for dartsim

Formula/gazebo11.rb
=> gazebo11: rebuild for dartsim

Formula/gz-fuel-tools8.rb, Formula/gz-garden.rb, Formula/gz-gui7.rb, Formula/gz-launch6.rb, Formula/gz-msgs9.rb, Formula/gz-physics6.rb, Formula/gz-rendering7.rb, Formula/gz-sensors7.rb, Formula/gz-sim7.rb, Formula/gz-transport12.rb, Formula/sdformat13.rb
Part of https://github.com/gazebo-tooling/release-tools/issues/1165.
=> Garden: deprecate EOL formulae

Formula/gazebo11.rb
=> gazebo11: rebuild bottle for protobuf 29.0

Formula/gz-math7.rb, Formula/gz-math8.rb
=> gz-math*: fix default argument to python_cmake_arg

Formula/gz-fuel-tools10.rb, Formula/gz-gui9.rb, Formula/gz-launch8.rb, Formula/gz-msgs11.rb, Formula/gz-sensors9.rb, Formula/gz-sim9.rb, Formula/gz-transport14.rb
Part of #2906.
~~~
do
done
~~~
=> Ionic: rebuild bottles broken by protobuf 29.1

Formula/gazebo11.rb
=> gazebo11: rebuild for protobuf 29.1

Formula/dartsim@6.10.0.rb, Formula/gazebo11.rb, Formula/ignition-physics2.rb
=> Remove bottles broken by boost 1.87

Formula/gz-fuel-tools10.rb, Formula/gz-gui9.rb, Formula/gz-launch8.rb, Formula/gz-msgs11.rb, Formula/gz-sensors9.rb, Formula/gz-sim9.rb, Formula/gz-transport14.rb
Part of #2920.
~~~
do
done
~~~
=> Ionic: rebuild bottles broken by protobuf 29.2

Aliases/gz-gui10, Formula/gz-gui10.rb
=> Bumps in jetty : ci_matching_branch/bump_jetty_gz-gui10

Aliases/gz-sim10, Formula/gz-sim10.rb
=> gz-sim10: new formula in jetty

Aliases/gz-launch9, Formula/gz-launch9.rb
=> gz-launch9: new formula in jetty

Formula/ignition-common3.rb, Formula/ignition-fuel-tools4.rb, Formula/ignition-msgs5.rb
ecacfb3 ignition-msgs5: update 5.11.1
ccf1570 ignition-fuel-tools4: update 4.9.2
db4565f ignition-common3: update 3.17.1
Replacing PRs #2947, #2946 , #2948.
=> Gazebo classic EOL Releases

Formula/gazebo11.rb, Formula/ignition-common3.rb, Formula/ignition-fuel-tools4.rb, Formula/ignition-msgs5.rb, Formula/sdformat9.rb, README.md
Part of https://github.com/gazebo-tooling/release-tools/issues/1252
=> Deprecate libraries that have reached EOL with Gazebo Classic 11

Formula/ignition-gazebo6.rb, Formula/ignition-launch5.rb
=> Fortress: remove broken bottles

Formula/gz-common6.rb, Formula/gz-fuel-tools10.rb, Formula/gz-gui9.rb, Formula/gz-launch8.rb, Formula/gz-msgs11.rb, Formula/gz-physics8.rb, Formula/gz-sensors9.rb, Formula/gz-sim9.rb, Formula/gz-transport14.rb, Formula/sdformat15.rb
Part of #2992.
~~~
do
done
~~~
=> Rebuild ionic bottles for tinyxml2

Formula/gz-common5.rb, Formula/gz-fuel-tools9.rb, Formula/gz-gui8.rb, Formula/gz-launch7.rb, Formula/gz-msgs10.rb, Formula/gz-physics7.rb, Formula/gz-sensors8.rb, Formula/gz-sim8.rb, Formula/gz-transport13.rb, Formula/sdformat14.rb
Part of #2992.
~~~
do
done
~~~
=> Rebuild harmonic bottles for tinyxml2

Formula/ignition-common4.rb, Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui6.rb, Formula/ignition-launch5.rb, Formula/ignition-msgs8.rb, Formula/ignition-physics5.rb, Formula/ignition-sensors6.rb, Formula/ignition-transport11.rb, Formula/sdformat12.rb
Part of #2992.
~~~
do
done
~~~
=> Rebuild fortress bottles for tinyxml2

README.md
Also use footnotes to define links outside of table.
=> Add jetty badges, use footnotes

Formula/gz-gui10.rb, Formula/gz-sim10.rb
Part of https://github.com/gazebo-tooling/release-tools/issues/1244.
Passes in local testing on my machine.
=> Jetty: remove package name from gui, sim tests

Formula/gz-gui10.rb, Formula/gz-sim10.rb
This reverts commit a805ac545b8c496e42a61f4756ed5dfd433bf7ee.
Part of #3011.
=> Revert "gz-gui10 and gz-sim10: Add Qt6 dependency (#3007)"

Formula/ogre2.3.rb
=> ogre2.3: patch for XCode 16.3

Aliases/gz-common7, Formula/gz-common7.rb
Part of https://github.com/gazebo-tooling/release-tools/issues/1309.
=> gz-common7: Bump gz-cmake and others in jetty

Aliases/gz-physics9, Formula/gz-physics9.rb
Part of https://github.com/gazebo-tooling/release-tools/issues/1309.
=> gz-physics9: Bump gz-cmake and others in jetty

Aliases/gz-rendering10, Formula/gz-rendering10.rb
Part of https://github.com/gazebo-tooling/release-tools/issues/1309.
=> gz-rendering10: Bump gz-cmake and others in jetty

Formula/gz-common6.rb, Formula/gz-fuel-tools10.rb, Formula/gz-gui9.rb, Formula/gz-launch8.rb, Formula/gz-physics8.rb, Formula/gz-rendering9.rb, Formula/gz-sensors9.rb, Formula/gz-sim9.rb
Part of #3038.
~~~
do
brew bump-revision --message="rebuild for gdal" $f
done
~~~
=> Rebuild ionic bottles for gdal 3.11

Formula/gz-common5.rb, Formula/gz-fuel-tools9.rb, Formula/gz-gui8.rb, Formula/gz-launch7.rb, Formula/gz-physics7.rb, Formula/gz-rendering8.rb, Formula/gz-sensors8.rb, Formula/gz-sim8.rb
Part of #3038.
~~~
do
brew bump-revision --message="rebuild for gdal" $f
done
~~~
=> Rebuild  harmonic bottles for gdal 3.11

Formula/sdformat15.rb
Fixes rpath for standalone executable and adds test.
=> sdformat15: fix standalone executable rpath and rebuild

Formula/sdformat12.rb, Formula/sdformat14.rb
Follow up to https://github.com/Homebrew/homebrew-core/pull/224113.
=> sdformat{12,14}: rebuild for urdfdom

Formula/gz-msgs12.rb
Pairs with https://github.com/gazebosim/gz-msgs/pull/518.
=> gz-msgs12: install executable to unversioned folder

Formula/gz-msgs11.rb
=> gz-msgs11: fix rpath, test executable

Aliases/gz-tools3, Formula/gazebo11.rb, Formula/gz-tools2.rb, Formula/gz-tools3.rb
Needed by https://github.com/gazebosim/gz-tools/pull/157.
=> gz-tools3: new formula using gz-cmake5

Formula/gz-common5.rb, Formula/gz-common6.rb, Formula/gz-fuel-tools10.rb, Formula/gz-fuel-tools9.rb, Formula/gz-gui8.rb, Formula/gz-gui9.rb, Formula/gz-launch7.rb, Formula/gz-launch8.rb, Formula/gz-physics7.rb, Formula/gz-physics8.rb, Formula/gz-rendering8.rb, Formula/gz-rendering9.rb, Formula/gz-sensors8.rb, Formula/gz-sensors9.rb, Formula/gz-sim8.rb, Formula/gz-sim9.rb, Formula/ignition-common4.rb, Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui6.rb, Formula/ignition-launch5.rb, Formula/ignition-physics5.rb, Formula/ignition-rendering6.rb, Formula/ignition-sensors6.rb
Part of #3068.
~~~
for m in gz-common5 gz-common6 gz-common4
do
do
done
done
~~~
cc @Blast545
=> Remove bottles broken by assimp

Formula/gz-common6.rb, Formula/gz-fuel-tools10.rb, Formula/gz-gui9.rb, Formula/gz-rendering9.rb
Part of #3068.
~~~
do
brew bump-revision --message="rebuild for assimp" $f
done
~~~
=> Rebuild Ionic bottles for assimp

Formula/gz-common5.rb, Formula/gz-fuel-tools9.rb, Formula/gz-gui8.rb, Formula/gz-launch7.rb, Formula/gz-physics7.rb, Formula/gz-rendering8.rb, Formula/gz-sensors8.rb, Formula/gz-sim8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/3068.
~~~
do
brew bump-revision --message="rebuild for assimp" $f
done
~~~
=> Rebuild Harmonic bottles for assimp

Formula/ignition-common4.rb, Formula/ignition-fuel-tools7.rb, Formula/ignition-gazebo6.rb, Formula/ignition-gui6.rb, Formula/ignition-launch5.rb, Formula/ignition-physics5.rb, Formula/ignition-rendering6.rb, Formula/ignition-sensors6.rb
Part of https://github.com/osrf/homebrew-simulation/issues/3068.
~~~
do
brew bump-revision --message="rebuild for assimp" $f
done
~~~
=> Rebuild Fortress bottles for assimp

Formula/tinyxml1.rb
=> tinyxml1: fix style

.github/ci/unbottled_dependencies.sh, Formula/gz-common6.rb, Formula/gz-fuel-tools10.rb, Formula/gz-gui9.rb, Formula/gz-launch8.rb, Formula/gz-math8.rb, Formula/gz-msgs11.rb, Formula/gz-physics8.rb, Formula/gz-rendering9.rb, Formula/gz-sensors9.rb, Formula/gz-sim9.rb, Formula/gz-transport14.rb, Formula/sdformat15.rb
Part of https://github.com/osrf/homebrew-simulation/issues/3078.
=> Rebuild ionic bottles

Formula/gz-msgs10.rb
=> gz-msgs10: revision bump for protobuf

.github/ci/bottled_dependents.sh, .github/ci/unbottled_dependencies.sh, Formula/gz-fuel-tools10.rb, Formula/gz-gui9.rb, Formula/gz-launch8.rb, Formula/gz-msgs10.rb, Formula/gz-msgs11.rb, Formula/gz-sensors9.rb, Formula/gz-sim9.rb, Formula/gz-transport14.rb
Part of #3094.
Generated with:
~~~
for m in gz-msgs5 gz-msgs8 gz-msgs9 gz-msgs10 gz-msgs11
do
for f in $(.github/ci/bottled_dependents.sh $m sonoma)
do
done
done
~~~
=> Remove bottles broken by abseil again

Formula/gz-common5.rb, Formula/gz-math7.rb, Formula/gz-physics7.rb, Formula/gz-plugin2.rb, Formula/gz-tools2.rb, Formula/gz-utils2.rb, Formula/sdformat14.rb
Comment out head in several formulae and build arm bottles.
=> Harmonic: build arm bottles part 1

Formula/ogre2.3.rb
=> ogre2.3: build arm bottle

Formula/gz-utils4.rb
Part of https://github.com/gazebosim/gz-jetty/issues/21
=> gz-utils4: Use stable branch in url

Formula/ogre2.2.rb
=> ogre2.2: build arm bottle

Formula/ignition-cmake2.rb, Formula/ignition-common4.rb, Formula/ignition-math6.rb, Formula/ignition-physics5.rb, Formula/ignition-plugin1.rb, Formula/ignition-rendering6.rb, Formula/ignition-tools.rb, Formula/ignition-utils1.rb, Formula/sdformat12.rb
=> Fortress: build arm bottles part 1

Formula/gz-cmake4.rb, Formula/gz-common6.rb, Formula/gz-math8.rb, Formula/gz-physics8.rb, Formula/gz-plugin3.rb, Formula/gz-rendering9.rb, Formula/gz-utils3.rb, Formula/sdformat15.rb
=> Ionic: build arm bottles part 1

Formula/gz-common5.rb, Formula/gz-common6.rb, Formula/ignition-common4.rb
Broken by https://github.com/Homebrew/homebrew-core/pull/234498.
=> Remove gz-common* bottles broken by ffmpeg

Formula/gz-sim8.rb, Formula/gz-sim9.rb, Formula/ignition-gazebo6.rb
=> Remove gz-sim* bottles broken by ffmpeg

Formula/gz-launch7.rb, Formula/gz-launch8.rb, Formula/ignition-common4.rb, Formula/ignition-launch5.rb
=> ffmpeg 8 fixes: gz-common4 patch, remove launch bottles

Formula/gz-common5.rb, Formula/gz-launch7.rb, Formula/gz-sim8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/3164.
=> Harmonic: rebuild bottles for ffmpeg

Formula/ignition-common4.rb, Formula/ignition-gazebo6.rb, Formula/ignition-launch5.rb
Part of https://github.com/osrf/homebrew-simulation/issues/3164.
=> Fortress: rebuild bottles for ffmpeg

Formula/gz-tools2.rb, Formula/ogre1.9.rb, Formula/ogre2.2.rb, Formula/ogre2.3.rb
Make trivial changes to comments in `ogre*` formulae that are shared across multiple versions of gazebo.
=> ogre*: build arm64_sequoia bottles

Formula/gz-common6.rb, Formula/gz-math8.rb, Formula/gz-physics8.rb, Formula/gz-plugin3.rb, Formula/gz-rendering9.rb, Formula/gz-utils3.rb, Formula/sdformat15.rb
Make trivial changes to formulae removing comments or redundant cmake args.
=> Ionic: build arm64_sequoia bottles
