osrf/homebrew-simulation

- ogre.rb
Bypasses sourceforge's new JS-based redirect dingus that breaks Homebrew.
cf. https://github.com/Homebrew/homebrew/issues/41778#issuecomment-122380024
> Point the Ogre download at a specific mirror.

- ogre.rb
Reverts osrf/homebrew-simulation#41 since sourceforge seems to have recovered.
@mikepurvis
> Revert "Point the Ogre download at a specific mirror."

- player.rb
Add const qualifier to comparison operators in a class that gets used in a queue, to comply with new compiler strictness.
Fixes #38 .
> Fix build on 10.10

- gazebo5.rb
- gazebo6.rb
- gazebo7.rb
Bullet recently got updated and it changed library names making
gazebo binary not able to find previous bullet libraries.
> Bump revision on gazebo7 due to problems with bullet dependency

- qt4-no-webkit.rb
qt4 is no longer in core, so we are hosting our own formula.
Due to security concerns, webkit support is disabled.
> qt4-no-webkit: new formula

- ignition-common.rb
After the change in: https://bitbucket.org/ignitionrobotics/ign-common/pull-requests/17/depend-on-ignition-math3/diff
> Use ignition-math3 in ignition-common

- ignition-math2.rb
- ignition-math3.rb
See https://bitbucket.org/osrf/gazebo/issues/2141/risk-of-mixing-ign-math2-and-ign-math3
> Define conflicts between ign-math2 and ign-math3

- gazebo7.rb
- gazebo8.rb
- haptix-comm.rb
- ignition-msgs.rb
- ignition-transport.rb
- ignition-transport2.rb
- ignition-transport3.rb
A protobuf update broke all the bottles using protobuf as a dependency. Bump all revisions to trigger new bottle builds.
> Bump all formula versions using protobuf

- gazebo7.rb
- gazebo8.rb
install build is failing due to updated bullet version:
http://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/430/console
> gazebo78: bump revisions for new bullet

- gazebo8.rb
The `qt5` formula was recently renamed to `qt`, so we need to build new bottles.
Please wait to merge this as I have a separate upstream pull request opened at brew using the unpatched version of this formula as an example for some unrelated weird behavior:
* https://github.com/Homebrew/brew/pull/2462
> gazebo8: rename qt5 to qt

- gazebo1.rb
- gazebo2.rb
- gazebo3.rb
- gazebo4.rb
- gazebo5.rb
- gazebo6.rb
Remove `with-shared` from bullet and change `core-only` to `with-core-only` for dartsim4
> gazebo[1-6]: update option names for bullet/dart

- gazebo7.rb
This is an alternative to #240 that focuses on making sure the gazebo7 bottle will build. The jenkins job was failing due to old formulae, so I've focused on just this:
* https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder-elcapitan/31/
> gazebo7: use cartr/qt4 tap for qt@4

- sdformat.rb
- sdformat3.rb
These aren't used by any supported versions of gazebo, so don't build bottles for them any longer.
> Don't bottle sdformat, sdformat3 any longer

- gazebo8.rb
- ignition-msgs.rb
- ignition-transport.rb
- ignition-transport2.rb
- ignition-transport3.rb
- ogre1.9.rb
- sdformat5.rb
boost 1.65 was just released into homebrew: https://github.com/Homebrew/homebrew-core/pull/17122 and it broke our gazebo bottles:
* https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/625/
> bump formulae for boost 1.65

- gazebo8.rb
This also drops the yosemite bottle from the gazebo8 formula.
> gazebo8: bump revision for bullet 2.87

- ignition-math4.rb
I'm trying out the new homebrew convention for versioned formula with the `@` character. It probably breaks some of our CI scripts.
> ignition-math4: new formula

- ignition-common0.rb
from https://bitbucket.org/ignitionrobotics/ign-common/pull-requests/87/support-new-errorstr-api-in-tinyxml2-600
> ignition-common: patch for tinyxml2 6.0.0

- ignition-fuel-tools0.rb
Being introduced on this PR:
https://bitbucket.org/ignitionrobotics/ign-fuel-tools/pull-requests/29/
I think this should be the right one, I saw an example here:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/ruby.rb#L32
> Add libyaml to ign-fuel-tools dependencies

- ignition-fuel-tools0.rb
Ignition Fuel Tools will use Ignition CMake when [#34](https://bitbucket.org/ignitionrobotics/ign-fuel-tools/pull-requests/34) is merged. This pull request adds the new Ignition CMake dependency.
@scpeters , do I need to make more changes here? Disable bottles or update sha's?
> Add new ign-cmake dependency to fuel-tools.

- sdformat3.rb
I reapplied the patch from https://github.com/osrfbuild/homebrew-simulation/pull/4 to target this repository
> sdformat3: Add patch to fix issues building with cmake

- gazebo9.rb
[`dartsim` is accepted to `homebrew-core`](https://github.com/Homebrew/homebrew-core/pull/23903).
> Use dartsim in homebrew-core instead of dartsim/dart/dartsim6

- ignition-gui0.rb
The formula seems to be working without this dependency since it is probably added to the build by `ignition-rendering0`. Explicitly added it here.
> Added ignition-cmake1 dependency in ignition-gui

- ogre.rb
We are now using ogre1.9 for gazebo7-9, so we don't need to support ogre 1.7 anymore
> ogre: disable bottles

- ignition-gui0.rb
companion to https://bitbucket.org/ignitionrobotics/ign-gui/pull-requests/107/update-to-use-newest-dependencies/diff
> ignition-gui: depend on common2, transport5

- ignition-rendering1.rb
- ignition-sensors0.rb
Based on [this](https://github.com/osrf/homebrew-simulation/commit/d3bed28afee1887c21941586d1de3720662c4aa0#diff-a578e0ba26f6bce6e367db30255ca9fc) commit I updated the depencies for ign_sensors. This is broken because ignition sensors default branch uses gz11 branches for its dependencies since [this PR](https://bitbucket.org/ignitionrobotics/ign-sensors/pull-requests/14/bionic/diff).
> Bump ign sensors dependencies to work with gz11 branches

- ignition-cmake1.rb
I'm looking for an updated version of ignition cmake for ignition rendering (see #457).
This converts it from using a released version to a particular commit, which might not be appropriate. Please advise if a new release is more appropriate instead
> ignition-cmake1: use newer commit

- ignition-rendering0.rb
Context is in https://bitbucket.org/ignitionrobotics/ign-rendering/issues/28
This is the first time I've done this. I'm copying https://github.com/osrf/homebrew-simulation/pull/450. I think the other commits must get generated automatically somehow.
This version of ignition rendering requires an updated version of ignition cmake: see #458
> ignition-rendering0: use newer commit

- sdformat5.rb
The build for sdformat5 includes path information for the
share/sdformat directory. Therefore the build is not relocatable.
With this fix the bottled version is only used when the cellar
name is the same for the build and install place.
Closes: #479
> sdformat5: use bottled version only if build and install directory are identical

- ignition-sensors0.rb
Failing here: https://build.osrfoundation.org/job/ignition_sensors-ci-default-homebrew-amd64/33/console
> ignition-sensors: depend on sdformat8

- Formula/gazebo9.rb
- Formula/ignition-common1.rb
- Formula/ignition-fuel-tools1.rb
needed due to recent tinyxml2 update: https://github.com/Homebrew/homebrew-core/pull/33884
Also, depend on graphviz to help fix build problems reported in #517
> gazebo9: patch for boost 1.68

- Aliases/ignition-gui
- Aliases/ignition-gui1
- Aliases/ignition-gui@1
- Formula/ignition-gui1.rb
The number of different dependencies is too high to maintain the workaround of the alias.
> Create ignition-gui1 formula and remove previous alias

- Formula/gazebo8.rb
When running `brew install gazebo8` on High Sierra, I get:
```
==> Downloading http://gazebosim.org/distributions/bottles-simulation/gazebo8-8.
Already downloaded: /Users/travis/Library/Caches/Homebrew/downloads/0264a43e94f2857762e06d82d9ee057c3947d2675d880755fff6ce9fb6954fa2--gazebo8-8.6.0_4.high_sierra.bottle.tar.gz
==> Pouring gazebo8-8.6.0_4.high_sierra.bottle.tar.gz
Broken dependencies:
/usr/local/opt/bullet/lib/libBulletCollision.2.87.dylib (bullet)
/usr/local/opt/bullet/lib/libBulletDynamics.2.87.dylib (bullet)
/usr/local/opt/bullet/lib/libBulletSoftBody.2.87.dylib (bullet)
/usr/local/opt/bullet/lib/libLinearMath.2.87.dylib (bullet)
Warning: gazebo8 has broken dynamic library links:
Rebuild this from source with:
brew reinstall --build-from-source gazebo8
If that's successful, file …
```
> gazebo8: rebuild bottle for bullet 2.88

- Formula/gazebo10.rb
- Formula/gazebo9.rb
- Formula/ignition-msgs1.rb
- Formula/ignition-transport4.rb
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-install-one_liner-homebrew-amd64&build=1217)](https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/1217/) https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/1217/
> gazebo9/10, deps: bump revision for protobuf 3.7.0

- Aliases/ignition-cmake3
- Aliases/ignition-common4
- Aliases/ignition-fuel-tools4
- Aliases/ignition-fuel_tools3
- Aliases/ignition-gui2
- Aliases/ignition-math7
- Aliases/ignition-physics2
- Aliases/ignition-plugin2
This allows the default branches to install correct dependencies during CI builds.
Thanks to @iche033 who already made some of these.
> Add aliases for Acropolis versions +1

- Aliases/ignition-rendering2
- Aliases/ignition-sensors2
- Formula/ignition-rendering2.rb
- Formula/ignition-sensors2.rb
New ignition-sensors2 formula based on a commit. 
I'm not very sure about the changes. Let me know if I need to change anything. 
I copied from `ignition-sensors1.rb` but removed the `bottle` section and the `version` field. The `url` now points to a specific commit and I also bumped ign-rendering dependency to ignition-rendering2
> ignition-sensors2, ignition-rendering2 initial versions

- Aliases/ignition-launch
The generic build was failing due to the lack of a formula named `ignition-launch`
> Add ignition-launch alias to ignition-launch0

- Aliases/ignition-acropolis1
It will make things easier in the CI since it is currently failing here with our generic script: https://build.osrfoundation.org/job/ignition_acropolis-ci-default-homebrew-amd64/4/
> Add ignition-acropolis1 alias

- Formula/ogre1.9.rb
- Formula/sdformat4.rb
- Formula/sdformat5.rb
- Formula/sdformat6.rb
- Formula/sdformat7.rb
Gazebo bottles are disabled to shorten the build time for gazebo deps. Gazebo bottles will be rebuilt after this is merged.
> Bump ogre / sdformat revisions for boost 1.69

- Formula/ignition-rendering1.rb
The test wasn't sufficient to indicate that a revision bump was needed when we rebuilt bottles for ogre 1.69, but the test in aa457dc fails with the current bottle in a way that matches the test failures we've seen in ign-gazebo.
> ignition-rendering1: better test for ogre plugin, bump revision

- Formula/ogre2.1.rb
Officially Apple says that OpenGL is only deprecated on mojave, but I'm seeing compilation errors like https://github.com/OGRECave/ogre/issues/817 when I try to build ogre 2.1. A workaround suggested in that issue is to disable the GL3Plus rendersystem, which I have added here when xcode 10+ is detected. So I think GL3Plus will be built for Sierra, but it will only have Metal for 10.13+.
There is a possibility that we could fix GL3Plus for Xcode10, but I'm not sure how easy that will be, and 10.15 will only support Metal anyway.
I also added a dependency on rapidjson, which is needed by the Hlms material system.
> ogre2.1: new commit, fix build for xcode 10+

- Formula/ogre2.1.rb
@j-rivero @iche033 I rebased #655 on top of this commit that reverts to the ogre2.1 commit used by our deb and tested ign-rendering1 successfully:
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_rendering-ci-pr_any-homebrew-amd64&build=231)](https://build.osrfoundation.org/job/ignition_rendering-ci-pr_any-homebrew-amd64/231/) https://build.osrfoundation.org/job/ignition_rendering-ci-pr_any-homebrew-amd64/231/
I'll build a new bottle for this, but we also need to modify the formula to allow for side-by-side installation.
> ogre2.1: revert to commit used by deb

- Formula/ignition-gui2.rb
Needed by this:
https://bitbucket.org/ignitionrobotics/ign-gui/pull-requests/202/
After that's merged, we can trigger a new nightly to fix the currently broken `ign-gazebo` CI (which expects `ign-gui2`).
> ign-gui2 use ign-msgs4 + ign-transport7

- Formula/ignition-common3.rb
Partial fix to #676 that uses code from the following pull request:
* https://bitbucket.org/ignitionrobotics/ign-common/pull-requests/189
> ignition-common3: test for and avoid xcode paths

- Formula/gazebo10.rb
- Formula/gazebo9.rb
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-install-one_liner-homebrew-amd64&build=1271)](https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/1271/) https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/1271/
> gazebo9/10: patch for dart 6.8

- Formula/ignition-gui2.rb
Bumping to this commit: https://bitbucket.org/ignitionrobotics/ign-gui/commits/85d9019f6c71f1c533468a0e9907f9a4d6115099
It should already match the latest debian nightly.
> ignition-gui2 blueprint bump

- Formula/sdformat8.rb
Bumping to latest commit on the `sdf8` branch: https://bitbucket.org/osrf/sdformat/commits/a15694f2c14f81bc8ce308bff5dbaac253ac997c
I'm not sure whether to, or how to, change the `bottle`
@nkoenig is triggering matching debian nightlies.
> sdformat8 blueprint bump

- Formula/ignition-msgs4.rb
This commit: https://bitbucket.org/ignitionrobotics/ign-msgs/commits/b82726d01252e141847335da3e8144d4e4cba54b
Matching debian nightlies are being triggered.
> ignition-msgs4 blueprint bump

- Formula/gazebo10.rb
The bottle build failed for gazebo10 when it was revision bumped in #749, but I think this patch will help.
> gazebo10 revision and patch for dart 6.9

- Formula/ignition-gui0.rb
- Formula/ignition-msgs2.rb
as suggested by the following PR's:
* https://bitbucket.org/ignitionrobotics/ign-msgs/pull-requests/138/use-math6/
* https://bitbucket.org/ignitionrobotics/ign-gui/pull-requests/215/gui0-use-rendering2/
> ignition-msgs2: depend on math6

- Formula/gazebo7.rb
- Formula/sdformat4.rb
Similar to #757 and #758, but sdformat4 also needs to be rebuilt, as reported in #756.
> sdformat4, gazebo7: rebuild for boost 1.70

- Formula/ignition-gazebo2.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-gui2.rb
- Formula/ignition-gui3.rb
- Formula/ignition-launch1.rb
- Formula/ignition-msgs4.rb
- Formula/ignition-sensors2.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-transport7.rb
https://github.com/Homebrew/homebrew-core/pull/44841
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-install-one_liner-homebrew-amd64&build=1453)](https://build.osrfoundation.org/view/os_homebrew/job/gazebo-install-one_liner-homebrew-amd64/1453/) https://build.osrfoundation.org/view/os_homebrew/job/gazebo-install-one_liner-homebrew-amd64/1453/
> protobuf 3.10: bump ignition-msgs4 and dependents

- Formula/gazebo7.rb
There's a weird bug that causes the `ignition-tools` bottle builds to fail due to gazebo7 installing `qt@4` and a workaround for this specific case is to remove the `ignition-transport` dependency since it is optional to gazebo7.
> gazebo7: don't depend on ignition-transport

- Formula/ignition-launch1.rb
- Formula/ignition-launch2.rb
SDFormat is an indirect dependency of launch, so I think it doesn't need to be declared.
Also see https://bitbucket.org/ignitionrobotics/ign-launch/pull-requests/53/
> ignition-launch: don't depend directly on SDF

- Formula/gazebo7.rb
Also add a patch to fix linking with gts, since this has been causing builds to fail:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-ci-gazebo7-homebrew-amd64&build=269)](https://build.osrfoundation.org/view/main/view/BuildCopFail/job/gazebo-ci-gazebo7-homebrew-amd64/269/) https://build.osrfoundation.org/view/main/view/BuildCopFail/job/gazebo-ci-gazebo7-homebrew-amd64/269/
> gazebo7: revision bump for protobuf 3.11

- .travis.yml
- azure-pipelines.yml
The high sierra hosted images will be removed from azure in March, so switch back to travis for these.
https://devblogs.microsoft.com/devops/azure-pipelines-hosted-pools-updates/
> use travis for high sierra, not azure

- Formula/sdformat8.rb
don't merge this until the following bitbucket PR has been merged:
* https://bitbucket.org/osrf/sdformat/pull-requests/677/fix-homebrew-build-with-external-urdfdom/diff
> sdformat8: depend on urdfdom

- Formula/dartsim@6.10.0.rb
- Formula/ignition-physics1.rb
- Formula/ignition-physics2.rb
- Formula/sdformat8.rb
- Formula/sdformat9.rb
Many things were broken when console_bridge 0.5.0 was released since it bumped a minor version. This bumps revisions on the broken bottles, and I will start a bottle build job.
> Bump revisions for console_bridge 0.5

- Formula/gazebo10.rb
- Formula/gazebo9.rb
- Formula/ignition-blueprint.rb
- Formula/ignition-gazebo2.rb
- Formula/ignition-gui2.rb
- Formula/ignition-launch1.rb
- Formula/ignition-msgs1.rb
- Formula/ignition-sensors2.rb
- Formula/ignition-transport4.rb
- Formula/ignition-transport7.rb
Protobuf bump killed the ABI in some cases, Bullet bump in some others. They should be regenerated, removing them to use brew test-bot without failures while testing code.
> Remove broken bottles for: gui2, msgs1, sensors2, transport4, transport7. gazebo9 and gazebo10

- Formula/ogre2.1.rb
Mapping the following patch:
* https://bitbucket.org/sinbad/ogre/commits/14b5dc7fc2d8e1281140d027e1effb4d8a317895
* https://github.com/OGRECave/ogre-next/commit/b00a880a4aea5492615ce8e3363e81631a53bb5c
and the following checksum for the archive:
* https://bitbucket.org/sinbad/ogre/commits/06a386fa64e79a7204a90faf53da1735743f6c2e
* https://github.com/OGRECave/ogre-next/commit/b4c4fa785c03c2d4ba2a1d28d94394c7ca000358
> ogre2.1: bitbucket -> github links

- Formula/ignition-fuel-tools5.rb
- Formula/ignition-gazebo4.rb
- Formula/ignition-launch3.rb
- Formula/ignition-msgs6.rb
- Formula/ignition-rendering0.rb
- Formula/ignition-rendering4.rb
- Formula/ignition-rndf0.rb
- Formula/ignition-sensors4.rb
- Formula/ogre1.9.rb
This updates bitbucket URL's to point to the same commit on GitHub. It includes some old formulae (ignition-rndf0, ignition-rendering0, ogre1.9) and new formulae (ignition dome dependencies).
> Bitbucket -> GitHub urls: some old, some new

- Aliases/ignition-transport9
- Formula/ignition-transport9.rb
Remove alias and add new formula that depends on `ign-msgs6`. I took the last commit of https://github.com/ignitionrobotics/ign-transport/pull/149/
This is broken off https://github.com/osrf/homebrew-simulation/pull/1063 so we can make the changes incrementally.
> ignition-transport9: new formula

- Formula/ignition-sensors4.rb
Breaking off just the `ign-sensors` part of https://github.com/osrf/homebrew-simulation/pull/1063/.
Using the latest commit from https://github.com/ignitionrobotics/ign-sensors/pull/31
> ignition-sensors4: bump for msgs6, transport9, sdf10

- Formula/ignition-gui4.rb
- Formula/ignition-transport9.rb
Breaking off just the `ign-gui` part of https://github.com/osrf/homebrew-simulation/pull/1063/files.
Using the latest commit from https://github.com/ignitionrobotics/ign-gui/pull/92/
~~Also fixed major version of `ign-transport9` that was wrong on #1065~~ will do it in a separate PR
> ignition-gui4: bump for msgs6 and transport9

- Formula/ignition-acropolis.rb
- Formula/ignition-gazebo1.rb
- Formula/ignition-gui1.rb
- Formula/ignition-launch0.rb
- Formula/ignition-msgs3.rb
- Formula/ignition-rendering1.rb
- Formula/ignition-sensors1.rb
- Formula/ignition-transport6.rb
The software has been EOL since last September, so mark them as deprecated as of that date and that they will be disabled at the end of this month. We will remove them after being disabled for a week or so.
> acropolis formulae: deprecate and disable soon

- Formula/ignition-transport9.rb
So, I messed up on #1065 and `ignition-transport9` was released with a major too high. Now brew won't allow a version decrease.
Is this fixable? 😟
> ignition-transport9: fix version

- Formula/ignition-math6.rb
Fix the build issue with ruby reported in #1120. Start by adding a `:build` dependency on `swig`.
> ignition-math6: fix build with ruby

- Formula/ignition-math6.rb
It's causing CI failures, so revert it for now.
> ignition-math6: revert swig dependency

- Formula/gazebo10.rb
- Formula/gazebo9.rb
Use patch from osrf/gazebo#2809 to fix #1123.
> gazebo9/10: patch for boost 1.73.0

- Formula/dartsim@6.10.0.rb
This should match the update on DART packages in our stable repository[ corresponding to the new PPA build](https://launchpad.net/~j-rivero/+archive/ubuntu/dartsim-openrobotics-testing/+build/19943026).
There is a discrepancy in the commit attached to the version, it was a bug in Linux packages that points to a commit in the releasing repository instead of the real commit on upstream repository. Should not affect functionality, it just has information proposes.
//cc @azeey
> New dart version 6.10.0~2020-09-16

- Formula/dartsim@6.10.0.rb
The bottles built in #1148 did not get uploaded properly. Let's try building them again with the branch from https://github.com/ignition-tooling/release-tools/pull/281.
> dartsim@6.10.0: revision bump to rebuild bottles

- Aliases/ignition-edifice1
- Formula/ignition-edifice.rb
At the moment, the dependencies are the same as Dome.
Here's the upstream repo: https://github.com/ignitionrobotics/ign-edifice
> New formula: Ignition Edifice

- Aliases/ignition-rendering5
- Formula/ignition-rendering5.rb
Remove the alias and use a formula pointing to the current head commit of the `main` branch.
> ignition-rendering5: new formula

- Aliases/ignition-gazebo5
- Formula/ignition-gazebo5.rb
* Remove alias
* Copy formula from previous version
* Update to use the commit from https://github.com/ignitionrobotics/ign-gazebo/pull/430
> ignition-gazebo5: use rendering5

- Formula/ignition-cmake2.rb
- Formula/ignition-rendering4.rb
This patches ignition-cmake2 with https://github.com/ignitionrobotics/ign-cmake/pull/125 to fix `FindIgnOGRE2`, which should fix https://github.com/ignitionrobotics/ign-sensors/issues/62 after we have rebuilt the corresponding ignition-rendering bottles. This PR will rebuild `ignition-rendering4`. If it is successful, I will rebuild the other supported versions as well.
> Patch ignition-cmake2 and rebuild ignition-rendering4 bottle

- Formula/ignition-rendering2.rb
- Formula/ignition-rendering3.rb
- Formula/ignition-rendering5.rb
Rebuild `ignition-rendering[235]` now that `ignition-cmake2` is finding ogre2 more properly (#1203).
> ignition-rendering[235]: rebuild to fix ogre2

- README.md
When working on #1214, @chapulina and I realized that there are no instructions for updating the state of a repository that is used for a Formula (most importantly, there's no instructions for generating the `sha256`). This PR adds these instructions to the `README`.
Signed-off-by: Ashton Larkin <ashton@openrobotics.org>
> Added url, version and sha256 update instructions

- Formula/ignition-blueprint.rb
This adds a test of the `ignition-blueprint` yaml file similar to #1219, but it also updates the formula to point to the latest commit, since the current release still points to bitbucket:
* https://github.com/ignitionrobotics/ign-blueprint/blob/ignition-blueprint_1.0.0/gazebodistro/collection-blueprint.yaml
> ignition-blueprint: test with vcs validate, update commit

- Formula/ignition-gazebo2.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-gazebo4.rb
- Formula/ignition-gazebo5.rb
This requires dependencies on ruby and ignition-tools.
> ignition-gazebo*: test `ign gazebo -s`

- Formula/ignition-rendering2.rb
- Formula/ignition-rendering3.rb
- Formula/ignition-rendering4.rb
- Formula/ignition-rendering5.rb
- Formula/ogre1.9.rb
- Formula/ogre2.1.rb
> ogre1.9, ogre2.1: use libx11 instead of :x11

- Formula/dartsim@6.10.0.rb
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gazebo3-install_bottle-homebrew-amd64&build=199)](https://build.osrfoundation.org/job/ignition_gazebo3-install_bottle-homebrew-amd64/199/) https://build.osrfoundation.org/job/ignition_gazebo3-install_bottle-homebrew-amd64/199/console
~~~
Warning: Broken symlinks were found. Remove them with `brew cleanup`:
/usr/local/opt/dartsim@6.10.0
~~~
> dartsim@6.10.0: revision bump for boost 1.75

- Formula/ignition-blueprint.rb
- Formula/ignition-fuel-tools3.rb
- Formula/ignition-gazebo2.rb
- Formula/ignition-gui2.rb
- Formula/ignition-launch1.rb
- Formula/ignition-msgs4.rb
- Formula/ignition-physics1.rb
- Formula/ignition-rendering2.rb
- Formula/ignition-sensors2.rb
- Formula/ignition-transport7.rb
- Formula/sdformat8.rb
All the install jobs for the bottles deprecated in #1242 are now failing because the `disable!` method deprecates if it is before the specified date, so it was deprecating them a bit too early. This removes the `disable!` call, so it will not be deprecated until after the deprecate! date. We can re-add the `disable!` line after the deprecation date has passed.
> ignition-blueprint: remove disable!

- Formula/gazebo8.rb
- Formula/ignition-gui0.rb
- Formula/ignition-gui2.rb
- Formula/ignition-gui3.rb
- Formula/ignition-gui4.rb
- Formula/ignition-gui5.rb
- Formula/ignition-launch2.rb
- Formula/ignition-launch3.rb
- Formula/ignition-launch4.rb
- Formula/sofa.rb
There is now a qt@5 alias, so use that instead of qt.
Skipping formulae that have active pull requests open.
Part of #1245.
> Depend on qt@5 instead of qt

- Aliases/ignition-fuel-tools6
- Formula/ignition-fuel-tools6.rb
Addressing https://github.com/ignition-tooling/release-tools/issues/362
Uses commit from https://github.com/ignitionrobotics/ign-fuel-tools/pull/158/
> ignition-fuel-tools6: new formula

- Formula/ignition-gazebo5.rb
Addressing https://github.com/ignition-tooling/release-tools/issues/362
Uses commit from https://github.com/ignitionrobotics/ign-gazebo/pull/546/commits
> ignition-gazebo5: update edifice dependencies

- Formula/ignition-launch4.rb
Addresses https://github.com/ignition-tooling/release-tools/issues/362
Uses commit from https://github.com/ignitionrobotics/ign-launch/pull/86/
> ignition-launch4: bump edifice dependencies

- Formula/ignition-edifice.rb
Addressing https://github.com/ignition-tooling/release-tools/issues/362
Uses commit from https://github.com/ignitionrobotics/ign-edifice/pull/2/
> ignition-edifice: bump dependencies

- Formula/dartsim@6.10.0.rb
Similar to https://github.com/Homebrew/homebrew-core/pull/68877, though I don't think this is currently affecting ignition-physics, since we are only using the ODE collision component, not bullet.
> dartsim@6.10.0: revision bump for bullet

- Formula/gazebo11.rb
The most recent homebrew bottle for bullet switched to double-precision, but this was reverted in https://github.com/Homebrew/homebrew-core/pull/68634, so we need to rebuild bottles to fix the broken ABI.
> gazebo11: revision bump for bullet

- Formula/ignition-utils1.rb
@scpeters , I'm not sure if moving the file like I did is ok, or if you'd prefer to keep version zero and copy over to version 1.
Uses the commit from https://github.com/ignitionrobotics/ign-utils/pull/6
> ignition-utils: version 1 instead of 0

- Formula/ignition-physics2.rb
- Formula/ignition-physics3.rb
There was unintentional linkage to `icu4c` in these bottles due to https://github.com/Homebrew/homebrew-core/issues/67427. They are now failing due to a new version of `icu4c`, so we need to rebuild them now, but it should only be this once.
> ignition-physics[23]: rebuild bottles

- Formula/gazebo11.rb
I've changed the test to include `gazebo/gazebo.hh`, which includes tbb headers via [gazebo/transport/Connection.hh](https://github.com/osrf/gazebo/blob/gazebo11_11.5.1/gazebo/transport/Connection.hh#L57). Sadly, we aren't exporting the `tbb` dependency in our cmake config, so we need to use `CPATH` to properly include the tbb header files.
> gazebo11: use tbb@2020 and update test

- Formula/dartsim@6.10.0.rb
- Formula/gazebo11.rb
- Formula/gazebo9.rb
- Formula/ignition-common1.rb
- Formula/ignition-common2.rb
- Formula/ignition-common3.rb
- Formula/ignition-common4.rb
- Formula/ignition-gui3.rb
- Formula/ignition-gui4.rb
- Formula/ignition-gui5.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch2.rb
- Formula/ignition-launch3.rb
- Formula/ignition-launch4.rb
- Formula/ignition-launch5.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-msgs6.rb
- Formula/ignition-msgs7.rb
- Formula/ignition-msgs8.rb
- Formula/sdformat10.rb
- Formula/sdformat11.rb
- Formula/sdformat12.rb
- Formula/sdformat9.rb
> Disable bottles that depend on tinyxml2

- Formula/sdformat9.rb
It uses tinyxml, not tinyxml2
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat9-install_bottle-homebrew-amd64)](https://build.osrfoundation.org/job/sdformat9-install_bottle-homebrew-amd64/) https://build.osrfoundation.org/job/sdformat9-install_bottle-homebrew-amd64/
partial revert of #1490
> sdformat9: restore bottle

- Formula/gazebo10.rb
- Formula/gazebo11.rb
- Formula/gazebo7.rb
- Formula/gazebo9.rb
- Formula/ignition-math4.rb
- Formula/ignition-math5.rb
- Formula/ignition-math6.rb
- Formula/sdformat6.rb
- Formula/sdformat7.rb
A recent change to brew audit disallows asymmetric
conflicts_with statements. Since these all involve
old formulae, this removes the conflicts_with
statements rather than trying to make them symmetric.
Fixes #1518.
> Remove asymmetric conflicts_with statements

- Formula/sdformat12.rb
Since https://github.com/osrf/homebrew-simulation/pull/1459 the bottle is being built from main, which is much easier than picking a commit and getting the hash.
But since a bottle is built, I think we still need to open this kind of PR to update the revision. Can we just not build a bottle, @scpeters ?
This is needed by https://github.com/ignitionrobotics/ign-gazebo/pull/888
> sdformat12: build from source

- Formula/gazebo11.rb
fix for [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-install-one_liner-homebrew-amd64&build=2131)](https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/2131/) https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/2131/
needed since https://github.com/Homebrew/homebrew-core/pull/82071
> gazebo11: revision bump for dartsim

- Formula/ogre2.2.rb
In sync with @iche033 and @chapulina we are bumping the version of the ogre2 formula in the repository to this upstream commit https://github.com/OGRECave/ogre-next/commit/ec3f70cb53a8a7e5d196855d0274ac03f90a2f4c.
> Update ogre 2.2 to version 2.2.5+20210824~ec3f70c

- Formula/gazebo11.rb
There is an open pull request to upgrade `qwt` to use qt version 6, so home-brew formulae that want to use `qwt` with `qt@5` should now depend on the `qwt-qt5` formula ( as of https://github.com/Homebrew/homebrew-core/pull/84275 ). This updates `gazebo11` to use `qwt-qt5` and bumps the revision. I will do the same for `gazebo9` in a separate pull request.
> gazebo11: depend on qwt-qt5

- Formula/ignition-gui3.rb
- Formula/ignition-gui4.rb
- Formula/ignition-gui5.rb
There is an open pull request to upgrade `qwt` to use qt version 6, so home-brew formulae that want to use `qwt` with `qt@5` should now depend on the `qwt-qt5` formula ( as of https://github.com/Homebrew/homebrew-core/pull/84275 ). These ignition-gui formulae list `qwt` as a dependency but don't actually use it, so just remove the dependency and bump revision so we can update the bottles.
> ignition-gui[345]: rm qwt dependency

- Formula/dartsim@6.10.0.rb
- Formula/gazebo9.rb
Follow-up to #1563, which did the same for gazebo11.
> gazebo9: remove optional dependencies

- Formula/ogre2.1.rb
Adds changes from ~~this pull request: https://github.com/OGRECave/ogre-next/pull/216~~
https://github.com/ignition-forks/ogre-2.1-release/compare/b4c4fa785c03c2d4ba2a1d28d94394c7ca000358..81632330e3ab041345c7fa1075022cf6af30c658
This allows the ignition gazebo gui to work on macOS.
> Add cocoa windowing patch to ogre 2.1 formula

- Aliases/ignition-rendering7
- Formula/ignition-rendering7.rb
See ignition-tooling/release-tools#545
> Bumps in garden : ign-rendering

- Formula/ogre2.1.rb
Testing https://github.com/ignition-tooling/release-tools/pull/556
> ogre2.1: add comment to allow big_sur build

- Formula/gazebo11.rb
- Formula/gazebo9.rb
Needed to fix CI. Workaround for https://github.com/ignition-tooling/release-tools/issues/573, follow-up to #1696.
> gazebo{9,11}: depend on cmake@3.21.4

- Aliases/ignition-common5
- Formula/ignition-common5.rb
> Bumps in garden : create ignition-common5

- Formula/ignition-dome.rb
- Formula/ignition-fuel-tools5.rb
- Formula/ignition-gazebo4.rb
- Formula/ignition-gui4.rb
- Formula/ignition-launch3.rb
- Formula/ignition-msgs6.rb
- Formula/ignition-physics3.rb
- Formula/ignition-rendering4.rb
- Formula/ignition-sensors4.rb
- Formula/ignition-transport9.rb
- Formula/sdformat10.rb
* Part of https://github.com/ignition-tooling/release-tools/issues/600
> 🏁 Dome EOL: deprecate and disable bottles

- Formula/gazebo9.rb
- Formula/ignition-msgs1.rb
- Formula/ignition-transport4.rb
Part of https://github.com/osrf/homebrew-simulation/issues/1728
> Rebuild gazebo9 for protobuf

- Formula/ignition-gazebo3.rb
- Formula/ignition-gazebo5.rb
- Formula/ignition-gazebo6.rb
> Rebuild ignition-gazebo* for protobuf 3.19.1

- Formula/ignition-common3.rb
These fixes (along with https://github.com/Homebrew/homebrew-core/pull/90205) are required to get gazebo11 running on Apple M1 hardware as used by the https://github.com/PX4/PX4-Autopilot project.
> Apple M1 fixes

- Formula/ignition-fuel-tools1.rb
- Formula/ignition-fuel-tools4.rb
- Formula/ignition-fuel-tools5.rb
- Formula/ignition-fuel-tools6.rb
- Formula/ignition-fuel-tools7.rb
Part of https://github.com/osrf/homebrew-simulation/issues/1780
~~~
brew bump-revision --remove-bottle-block --message="for jsoncpp" ignition-fuel-tools1
brew bump-revision --remove-bottle-block --message="for jsoncpp" ignition-fuel-tools4
brew bump-revision --remove-bottle-block --message="for jsoncpp" ignition-fuel-tools5
brew bump-revision --remove-bottle-block --message="for jsoncpp" ignition-fuel-tools6
brew bump-revision --remove-bottle-block --message="for jsoncpp" ignition-fuel-tools7
~~~
> Remove ignition-fuel-tools* bottles due to jsoncpp

- Formula/ignition-edifice.rb
- Formula/ignition-fuel-tools6.rb
- Formula/ignition-gazebo5.rb
- Formula/ignition-gui5.rb
- Formula/ignition-launch4.rb
- Formula/ignition-msgs7.rb
- Formula/ignition-physics4.rb
- Formula/ignition-rendering5.rb
- Formula/ignition-sensors5.rb
- Formula/ignition-transport10.rb
- Formula/sdformat11.rb
Deprecation date taken from https://github.com/ignitionrobotics/docs/blob/master/tools/versions.md
In general, we can add these tags as soon as we know the EOL dates for a given package. After the EOL date has been reached, they can be converted to `disable!` tags.
> edifice: add deprecate! with EOL date

- Formula/ignition-gazebo7.rb
Repeat fixes from #1806 and #1807 for ignition-gazebo7.
> ignition-gazebo7: fix test finding ffmpeg@4

- Formula/gazebo9.rb
Rebuild gazebo9 bottle using ffmpeg@4. Part of https://github.com/osrf/homebrew-simulation/issues/1800.
> gazebo9: revision bump for ffmpeg4

- Formula/ogre2.2.rb
I cherry-picked this from @srmainwaring's fork. It accompanies https://github.com/ignitionrobotics/ign-gui/pull/323 and https://github.com/ignitionrobotics/ign-gazebo/pull/1225
> ogre2.2 add patch for Metal support

- Formula/gazebo11.rb
Use patch from https://github.com/osrf/gazebo/pull/3174 and switch to the current version of `tbb`.
> gazebo11: use new tbb and recent patch

- Formula/ignition-gazebo3.rb
- Formula/ignition-gui3.rb
- Formula/ignition-launch2.rb
- Formula/ignition-msgs5.rb
- Formula/sdformat9.rb
Both ignition-gazebo3 and ignition-launch2 link against ffmpeg but didn't have a declared dependency. When the dependency version was changed from `ffmpeg@4` to `ffmpeg` in #1833, the ignition-gazebo3 and ignition-launch2 bottles should have been rebuilt. The bottle test jobs are now failing:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gazebo3-install_bottle-homebrew-amd64&build=655)](https://build.osrfoundation.org/view/ign-citadel/job/ignition_gazebo3-install_bottle-homebrew-amd64/655/) https://build.osrfoundation.org/view/ign-citadel/job/ignition_gazebo3-install_bottle-homebrew-amd64/655/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_launch2-install_bottle-homebrew-amd64&build=645)](https://build.osrfoundation.org/v …
> citadel: fix rpath and add ffmpeg dependencies

- Formula/ignition-common5.rb
- Formula/ignition-gazebo7.rb
- Formula/ignition-launch6.rb
Support for ffmpeg 5.0 has been merged into
ignition-common5, so switch back from ffmpeg@4
to ffmpeg. Also add dependencies for
ignition-gazebo7 and ignition-launch6 on
ffmpeg.
> garden: use ffmpeg

- Formula/gazebo11.rb
See comment https://github.com/osrf/gazebo/pull/2878#issuecomment-727848922 . The change from PR 2878 is part of Gazebo releases since 11.3.0, see https://github.com/osrf/gazebo/blob/gazebo11_11.3.0/cmake/SearchForStuff.cmake#L706 .
> gazebo11: Remove dependency on ossp-uuid

- Aliases/ignition-cmake3
- Formula/ignition-cmake3.rb
> Bumps in garden : ign-cmake3

- Formula/ignition-gazebo6.rb
- Formula/ignition-gazebo7.rb
* Gazebo has pybind11 binds since https://github.com/ignitionrobotics/ign-gazebo/pull/1219
* This PR is similar to https://github.com/osrf/homebrew-simulation/pull/1793
* This is an attempt at fixing build issues downstream in https://github.com/ignitionrobotics/ign-launch/pull/155
> ignition-gazebo[6,7]: depend on pybind11

- Formula/ignition-physics5.rb
Switch from dartsim@6.10.0 back to upstream dartsim to see if that fixes linking problems documented in #1884.
> ignition-physics5: don't use dartsim fork

- Formula/sdformat11.rb
- Formula/sdformat12.rb
- Formula/sdformat13.rb
The dependency became required since `sdf10`, see
* https://github.com/ignitionrobotics/sdformat/pull/780
> sdformat[11,12,13]: Explicitly depend on ign-cmake2

- Formula/dartsim@6.10.0.rb
- Formula/gazebo11.rb
- Formula/ignition-physics2.rb
- Formula/ignition-physics4.rb
- Formula/ignition-physics5.rb
A new version of bullet was merged in https://github.com/Homebrew/homebrew-core/pull/99927 that has broken some of our bottles:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_physics5-install_bottle-homebrew-amd64&build=209)](https://build.osrfoundation.org/job/ignition_physics5-install_bottle-homebrew-amd64/209/) https://build.osrfoundation.org/job/ignition_physics5-install_bottle-homebrew-amd64/209/
~~~
+ brew linkage --test ignition-physics5
Broken dependencies:
/usr/local/opt/bullet/lib/libBulletCollision.3.20.dylib (bullet)
/usr/local/opt/bullet/lib/libBulletDynamics.3.20.dylib (bullet)
/usr/local/opt/bullet/lib/libBulletSoftBody.3.20.dylib (bullet)
/usr/local/opt/bullet/lib/libLinearMath.3.20.dylib (bullet)
~~~
> Remove bottles broken by bullet 3.22b

- Formula/dartsim@6.10.0.rb
- Formula/ignition-physics2.rb
- Formula/ignition-physics5.rb
Rebuild the `dartsim@6.10.0` and `ignition-physics*` bottles removed in #1907.
> Rebuild dartsim@6.10.0, ign-physics* bottles

- Formula/gazebo11.rb
Rebuild the gazebo11 bottle removed in https://github.com/osrf/homebrew-simulation/pull/1907.
> Rebuild gazebo11 bottle for bullet

- Formula/gazebo11.rb
Since gazebo11 supports the most recent `tbb`, it shouldn't need to use the old version of cmake.
> gazebo11: bump revision and don't use cmake@3.21.4

- Formula/dartsim@6.10.0.rb
- Formula/gazebo11.rb
- Formula/gazebo9.rb
- Formula/ignition-physics2.rb
- Formula/ignition-physics5.rb
We just removed and rebuilt bottles after bullet 3.22b was released in https://github.com/Homebrew/homebrew-core/pull/99927, but we need to do it again for bullet 3.24 from https://github.com/Homebrew/homebrew-core/pull/100511
This removes the bottles, and they will be rebuilt in a subsequent PR
> Remove broken bottles for bullet 3.2.4

- Formula/ignition-edifice.rb
- Formula/ignition-gazebo5.rb
- Formula/ignition-launch4.rb
The `ignition-physics4` bottle was disabled in #1907 and was not rebuilt, so the edifice bottles that depend on it should be disabled as well.
> Remove edifice bottles with unbottled dependencies

- Formula/gazebo11.rb
The gazebo11 Big Sur bottle wasn't properly built in #1915 , so rebuild both
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-install-one_liner-homebrew-amd64&build=2417)](https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/2417/) https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/2417/
> gazebo11: revision bump for bullet again

- Aliases/gz-cmake3
- Aliases/gz-common5
- Aliases/gz-fuel-tools8
- Aliases/gz-garden
- Aliases/gz-gui7
- Aliases/gz-launch6
- Aliases/gz-math7
- Aliases/gz-msgs9
- Aliases/gz-physics6
- Aliases/gz-plugin2
- Aliases/gz-rendering7
- Aliases/gz-sensors7
- Aliases/gz-sim7
- Aliases/gz-tools2
- Aliases/gz-transport12
- Aliases/gz-utils2
Part of https://github.com/gazebo-tooling/release-tools/issues/698. The formulae should be renamed at some point, but the aliases are easy to make quickly.
> Add aliases for gz-* packages

- Formula/sdformat13.rb
I'm opening this to accompany the other PRs in 
* https://github.com/gazebo-tooling/release-tools/issues/718
But I believe this one doesn't need to wait for the others, since it only really needs the aliases that were added in 
* https://github.com/osrf/homebrew-simulation/pull/1922
> sdformat13: Depend on gz instead of ignition

- Formula/ignition-cmake3.rb
* Goes with https://github.com/gazebosim/gz-cmake/pull/244
> ignition-cmake3: Rename CMake project to gz-cmake3

- Formula/ignition-math7.rb
* Goes with https://github.com/gazebosim/gz-math/pull/420
> ignition-math7: Rename CMake project to gz-math7

- Formula/ignition-common5.rb
* Goes with https://github.com/gazebosim/gz-common/pull/352
> ignition-common5: Rename CMake project to gz-common5

- Formula/ignition-transport12.rb
* Goes with https://github.com/gazebosim/gz-transport/pull/320
> ignition-transport12: Rename CMake project to gz-transport12

- Formula/ignition-rendering7.rb
* Goes with https://github.com/gazebosim/gz-rendering/pull/645
> ignition-rendering7: Rename CMake project to gz-rendering7

- Formula/ignition-msgs9.rb
* Goes with https://github.com/gazebosim/gz-msgs/pull/250
> ignition-msgs9: Rename CMake project to gz-msgs9

- Formula/ignition-garden.rb
This hasn't been migrated yet, so revert for now to fix nightly builds.
> ignition-garden: revert gz path to ignition

- Formula/gazebo11.rb
- Formula/gazebo9.rb
- Formula/ignition-citadel.rb
- Formula/ignition-fortress.rb
- Formula/ignition-fuel-tools4.rb
- Formula/ignition-fuel-tools6.rb
- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui3.rb
- Formula/ignition-gui5.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch2.rb
- Formula/ignition-launch5.rb
- Formula/ignition-msgs1.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-msgs7.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-sensors5.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport10.rb
- Formula/ignition-transport11.rb
- Formula/ignition-transport4.rb
- Formula/ignition-transport8.rb
Needed to fix [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_fuel-tools4-install_bottle-homebrew-amd64&build=759)](https://build.osrfoundation.org/job/ignition_fuel-tools4-install_bottle-homebrew-amd64/759/) https://build.osrfoundation.org/job/ignition_fuel-tools4-install_bottle-homebrew-amd64/759/
~~~
+ brew linkage --test ignition-fuel-tools4
Broken dependencies:
/usr/local/opt/ignition-msgs5/lib/libignition-msgs5.5.dylib (ignition-msgs5)
/usr/local/opt/protobuf/lib/libprotobuf.30.dylib (protobuf)
~~~
> Disable broken bottles of protobuf dependents

- Formula/ignition-msgs5.rb
Part of https://github.com/osrf/homebrew-simulation/issues/1860. Unreleased patch from https://github.com/gazebosim/gz-msgs/pull/242 needed to fix compilation.
> gz-msgs5: rebuild after protobuf bump

- Formula/ignition-fortress.rb
- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch5.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
Since `ignition-msgs8` had already been rebuilt, its dependents could be bumped with:
~~~
for f in $(brew uses ignition-msgs8)
do
echo $f
brew bump-revision --message="rebuild after protobuf" $f
done
~~~
> Rebuild fortress bottles after protobuf bump.

- Formula/ignition-common5.rb
Reverts osrf/homebrew-simulation#1976
> Revert "gz-common5: depend on libcsv"

- Formula/ignition-fortress.rb
- Formula/ignition-garden.rb
This should fix the failing bottle tests.
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_fortress-install_bottle-homebrew-amd64&build=479)](https://build.osrfoundation.org/job/ignition_fortress-install_bottle-homebrew-amd64/479/) https://build.osrfoundation.org/job/ignition_fortress-install_bottle-homebrew-amd64/479/
> fortress, garden: build/test depend on python@3.9

- Formula/ignition-gazebo6.rb
- Formula/ignition-launch5.rb
There are some persistent bottle failures due to broken linkage, so bump revisions and try again.
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gazebo6-install_bottle-homebrew-amd64&build=307)](https://build.osrfoundation.org/job/ignition_gazebo6-install_bottle-homebrew-amd64/307/) https://build.osrfoundation.org/job/ignition_gazebo6-install_bottle-homebrew-amd64/307/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_launch5-install_bottle-homebrew-amd64&build=307)](https://build.osrfoundation.org/job/ignition_launch5-install_bottle-homebrew-amd64/307/) https://build.osrfoundation.org/job/ignition_launch5-install_bottle-homebrew-amd64/307/
> Rebuild gz-gazebo6 / launch5 to fix linkage

- Aliases/gz-cmake4
- Aliases/gz-common6
- Aliases/gz-fuel-tools9
- Aliases/gz-gui8
- Aliases/gz-launch7
- Aliases/gz-math8
- Aliases/gz-msgs10
- Aliases/gz-physics7
- Aliases/gz-plugin3
- Aliases/gz-rendering8
- Aliases/gz-sensors8
- Aliases/gz-sim8
- Aliases/gz-tools3
- Aliases/gz-transport13
- Aliases/gz-utils3
* Part of https://github.com/gazebo-tooling/release-tools/issues/578
I think we eventually should flip the Garden formulae to be `gz` and the aliases to be `ignition`.
> Add aliases for versions post-Garden

- Aliases/sdformat14
* Follow up to https://github.com/osrf/homebrew-simulation/pull/1981
* Part of https://github.com/gazebo-tooling/release-tools/issues/578
* Needed by https://github.com/gazebosim/sdformat/pull/1104
Forgot SDF 🤦🏽‍♀️
> Missing post-Garden alias: sdformat14

- Aliases/gz-tools1
This is similar to ignition-tools1. CI is currently failing for PRs targetting (e.g., https://github.com/gazebosim/gz-tools/pull/104) the `gz-tools1` branch with the following error:
```
+ brew install gz-tools1 --only-dependencies
Warning: No available formula with the name "gz-tools1".
==> Searching for similarly named formulae...
```
https://build.osrfoundation.org/job/ignition_tools-ci-pr_any-homebrew-amd64/292/
> gz-tools1: add alias

- Aliases/gz-garden
- Aliases/gz-garden1
- Aliases/ignition-garden
- Aliases/ignition-garden1
- Formula/gz-garden.rb
- Formula/ignition-citadel.rb
- Formula/ignition-fortress.rb
- Formula/ignition-garden.rb
I've noticed some failures building the `gz-garden` formula:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_garden-install_bottle-homebrew-amd64&build=282)](https://build.osrfoundation.org/view/ign-garden/job/ignition_garden-install_bottle-homebrew-amd64/282/) https://build.osrfoundation.org/view/ign-garden/job/ignition_garden-install_bottle-homebrew-amd64/282/
~~~
Last 15 lines from /Users/jenkins/Library/Logs/Homebrew/ignition-garden/03.python3:
2022-08-16 15:14:19 +0000
/usr/local/opt/python@3.9/bin/python3
-m
venv
--system-site-packages
/usr/local/Cellar/ignition-garden/0.999.999~0~20220414/libexec
~~~
The issue is that the `python@3.9` formula no longer provides a `python3` symlink in the `bin` folder (see …
> Fix python path, rename gz-garden formula

- Formula/gz-math7.rb
- Formula/ignition-math6.rb
- Formula/sdformat13.rb
I think this is related to python test failures like the following:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat-ci-sdformat13-homebrew-amd64&build=6)](https://build.osrfoundation.org/job/sdformat-ci-sdformat13-homebrew-amd64/6/) https://build.osrfoundation.org/job/sdformat-ci-sdformat13-homebrew-amd64/6/
~~~
282:     from gz.math import Pose3d, Color
282: E   ModuleNotFoundError: No module named 'gz'
~~~
> Add python dependency to packages with bindings

- Formula/gz-math7.rb
- Formula/sdformat13.rb
This installs the python bindings for `gz-math7` and `sdformat13` to `lib/python3.10` instead of `lib/python` and explicitly depends on the `python@3.10` formula. This should allow our bindings to be used with home-brew's `python@3.10` without setting `PYTHONPATH`.
> Fix python bindings so PYTHONPATH isn't needed

- Formula/gz-tools2.rb
This avoids the need for setting `GZ_CONFIG_PATH` for gz libraries installed via homebrew.
> gz-tools2: fix default data path

- Formula/ignition-tools.rb
Similar to https://github.com/osrf/homebrew-simulation/pull/2039.
This avoids the need for setting `IGN_CONFIG_PATH` for `ign` libraries installed via homebrew.
> ignition-tools: fix default data path

- Formula/gazebo11.rb
- Formula/gazebo9.rb
Boost 1.80 was recently released, and the gazebo9 and gazebo11 bottles are broken at the moment (see #2069). This removes the broken bottles so users will build from source for now.
> gazebo9/11: remove broken bottles

- Formula/gz-math7.rb
- Formula/gz-plugin2.rb
- Formula/gz-tools2.rb
- Formula/gz-utils2.rb
triggered.
* gz-tools2
* gz-utils2
* gz-math7
* gz-plugin2
Built using a deployment of https://github.com/gazebo-tooling/release-tools/pull/840.
> Garden: build monterey bottles part 1

- Formula/gz-common5.rb
- Formula/gz-msgs9.rb
- Formula/gz-transport12.rb
- Formula/sdformat13.rb
triggered.
* gz-common5, gz-msgs9, gz-transport12, sdformat13
> Garden: build monterey bottles part 2

- Formula/ogre1.9.rb
- Formula/ogre2.2.rb
- Formula/ogre2.3.rb
Add small change to several formulae
triggered.
* ogre1.9, ogre2.2, ogre2.3
> ogre*: build monterey bottles

- Formula/gz-fuel-tools8.rb
- Formula/gz-gui7.rb
- Formula/gz-rendering7.rb
- Formula/gz-sensors7.rb
triggered.
* gz-fuel-tools8, gz-gui7, gz-rendering7, gz-sensors7
> Garden: build monterey bottles part 3

- Formula/dartsim@6.10.0.rb
Add small change to formula (fix URL)
so bottle build for macOS Monterey can be
triggered.
> dartsim@6.10.0: build monterey bottle

- Formula/ignition-cmake2.rb
- Formula/ignition-math6.rb
- Formula/ignition-plugin1.rb
- Formula/ignition-tools.rb
- Formula/ignition-utils1.rb
triggered.
* ign-cmake2, ign-utils1, ign-tools, ign-math6, ign-plugin1
> Citadel: build monterey bottles part 1

- Formula/ignition-common3.rb
- Formula/ignition-fuel-tools4.rb
- Formula/ignition-gui3.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-rendering3.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-transport8.rb
- Formula/ogre2.1.rb
- Formula/sdformat9.rb
triggered.
* ign-common3, ign-fuel-tools4, ign-gui3, ign-msgs5, ign-rendering3, ign-sensors3, ign-transport8, sdformat9
> Citadel: build monterey bottles part 2

- Formula/ignition-common4.rb
- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gui6.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-rendering6.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
- Formula/sdformat12.rb
triggered.
* ign-common4, ign-fuel-tools7, ign-gui6, ign-msgs8, ign-rendering6, ign-sensors6, ign-transport11, sdformat12
> Fortress: build monterey bottles part 1

- Formula/gazebo11.rb
- Formula/simbody.rb
Add small change to the formula so a bottle
build for macOS Monterey can be triggered.
> gazebo11: build monterey bottle

- Formula/chrono-engine.rb
Add small change to formula so bottle builds
for macOS Monterey can be triggered.
> chrono-engine: build monterey bottle

- Formula/gazebo10.rb
- Formula/gazebo7.rb
- Formula/ignition-cmake1.rb
- Formula/ignition-common0.rb
- Formula/ignition-common2.rb
- Formula/ignition-fuel-tools0.rb
- Formula/ignition-fuel-tools2.rb
- Formula/ignition-math2.rb
- Formula/ignition-math3.rb
- Formula/ignition-math5.rb
- Formula/ignition-math@1.rb
- Formula/ignition-msgs0.rb
- Formula/ignition-msgs2.rb
- Formula/ignition-plugin0.rb
- Formula/ignition-rendering0.rb
- Formula/ignition-transport5.rb
- Formula/sdformat.rb
- Formula/sdformat3.rb
- Formula/sdformat4.rb
- Formula/sdformat7.rb
There's a lot of old formulae in this tap that should be cleaned up. I'm adding `deprecate!` fields now and will add `disable!` tags in about a month and then remove them about a month after that.
> Deprecate old formulae

- Formula/gz-garden.rb
- Formula/gz-launch6.rb
- Formula/gz-physics6.rb
- Formula/gz-sim7.rb
triggered.
* gz-physics6, gz-sim7, gz-launch6, gz-garden
> Garden: build monterey bottles part 4

- Formula/ignition-citadel.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-launch2.rb
- Formula/ignition-physics2.rb
triggered. Disable test for ignition-physics2
due to gazebosim/gz-physics#442.
* ign-physics2, ign-gazebo3, ign-launch2, ign-citadel
> Citadel: build monterey bottles final part

- Formula/gz-rendering7.rb
- Formula/ignition-rendering3.rb
Test that both ogre and ogre2 components can be found by cmake.
I have confirmed locally that this works for both rendering3 and rendering7. There is a problem with rendering6 that I am sorting out separately.
> gz-rendering{3,7}: test both ogre components

- Formula/ignition-fortress.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-launch5.rb
triggered.
* ign-gazebo6, ign-launch5, ign-fortress
> Fortress: build monterey bottles final part

- Aliases/gz-sensors8
- Formula/gz-sensors8.rb
Bump rendering dep from 7 to 8
Removed gz-sensors8 alias and added a new gz-sensors8.rb formulat.
I removed the bottle section as I think it may not needed but I'm not sure that's correct.
> gz-sensors8: depend on gz-rendering8

- Aliases/gz-gui8
- Formula/gz-gui8.rb
Bump gui8's rendering dep from 7 to 8
Removed gz-gui8 alias and added a new gz-gui8.rb formula.
> gz-gui8: depend on gz-rendering8

- Aliases/gz-launch7
- Formula/gz-launch7.rb
> gz-launch7: depend on gz-sim8 and gz-gui8

- Aliases/gz-sim8
- Formula/gz-sim8.rb
Bump gui, sensors, rendering dep from 7 to 8
Removed gz-sim8 alias and added a new gz-sim8.rb formula.
> gz-sim8: depend on gz-gui8, gz-sensors8, and gz-rendering8

- Aliases/gz-harmonic
- Aliases/ignition-harmonic
There is a harmonic bottle CI job since https://github.com/gazebo-tooling/release-tools/pull/857/ was merged, but it fails because there is no `gz-harmonic` formula:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_harmonic-install_bottle-homebrew-amd64&build=4)](https://build.osrfoundation.org/job/ignition_harmonic-install_bottle-homebrew-amd64/4/) https://build.osrfoundation.org/job/ignition_harmonic-install_bottle-homebrew-amd64/4/
~~~
+ brew install --include-test ignition-harmonic
Warning: No available formula with the name "ignition-harmonic".
~~~
So let's just make an alias for now.
> gz-harmonic: alias to gz-garden

- Formula/gz-physics6.rb
- Formula/ignition-physics2.rb
- Formula/ignition-physics5.rb
The gz-physics bottles have been broken since https://github.com/Homebrew/homebrew-core/pull/119513 was merged. This disables the bottles, which will be rebuilt in a subsequent pull request.
> Disable gz-ohysics bottles

- Formula/gazebo11.rb
Follow-up to https://github.com/Homebrew/homebrew-core/pull/120157
From https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/2660
~~~
+ brew test gazebo11
==> Testing osrf/simulation/gazebo11
==> /usr/local/Cellar/gazebo11/11.12.0_3/bin/gz sdf
Last 15 lines from /Users/jenkins/Library/Logs/Homebrew/gazebo11/test.01.gz:
2023-01-10 03:33:13 -0800
/usr/local/Cellar/gazebo11/11.12.0_3/bin/gz
sdf
dyld: lazy symbol binding failed: Symbol not found: __ZN5boost10filesystem4path9append_v3ERKS1_
Referenced from: /usr/local/Cellar/gazebo11/11.12.0_3/bin/../lib/libgazebo_common.11.dylib
Expected in: /usr/local/opt/boost/lib/libboost_filesystem-mt.dylib
dyld: Symbol not found: __ZN5boost10filesystem4path9append_v3ERKS1_
Referenced from: …
> gazebo11: remove bottles broken by boost

- Formula/dartsim@6.10.0.rb
- Formula/gazebo11.rb
- Formula/gz-physics6.rb
- Formula/ignition-physics2.rb
- Formula/ignition-physics5.rb
Several of our bottles were broken by https://github.com/Homebrew/homebrew-core/pull/121687, so disable them for now.
> Disable broken bottles due to bullet 3.25

- Aliases/gz-transport13
- Formula/gz-transport13.rb
Remove the alias, copy the transport12 formula and bump dependency on msgs to version 10. Update all references to 12 to 13.
> gz-transport13: depend on gz-msgs10

- Formula/gz-sensors8.rb
Bump to use msgs 10 and transport 13 
related PR: https://github.com/gazebosim/gz-sensors/pull/316
> gz-sensors8: depend on msgs10 and transport13

- Formula/gz-gui8.rb
Related PR: https://github.com/gazebosim/gz-gui/pull/517
Part of https://github.com/gazebo-tooling/release-tools/issues/878
> gz-gui8: depend on msgs10 and transport13

- Formula/sdformat9.rb
Fix for #2218. Patch from gazebosim/sdformat#1216. Don't need to build a bottle for this.
> sdformat9: add patch for ruby syntax

- Formula/ignition-common4.rb
Applying this patch separate from a bottle build to fix CI without waiting for the bottle to complete.
Part of #2241
> gz-common4: patch for ffmpeg6

- Formula/ignition-common3.rb
Apply patch directly to fix CI without waiting for bottle build.
Part of #2241.
> gz-common3: patch for ffmpeg 6

- Formula/gz-gui7.rb
- Formula/gz-rendering7.rb
- Formula/gz-sensors7.rb
There is a problem with the gz-rendering7 pkg-config file, so disable its pkg-config test and for its dependent formulae as well.
First discovered in https://github.com/osrf/homebrew-simulation/pull/2237#issuecomment-1518890616, caused by https://github.com/gazebosim/gz-rendering/pull/840.
> gz-rendering7, gui7, sensors7: no pkg-config test

- Formula/gz-gui7.rb
- Formula/gz-rendering7.rb
- Formula/gz-sensors7.rb
This re-enables the pkg-config tests for gz-rendering7, gz-gui7, and gz-sensors7 by reverting #2251, and applies a patch from https://github.com/gazebosim/gz-rendering/pull/844 to fix the tests.
This change doesn't require building new bottles; this can be merged as is.
> gz-rendering7: re-enable pkg-config test

- .github/workflows/main.yml
Version v1 is deprecated. Similar to https://github.com/Homebrew/brew/pull/15127.
> workflows/main.yml: use actions/cache@v3

- Formula/gz-physics6.rb
CI is failing with the following error, so attempting to fix it by rebuilding the bottle
```
==> Fetching osrf/simulation/gz-physics6
==> Downloading https://osrf-distributions.s3.amazonaws.com/bottles-simulation/gz-physics6-6.4.0.big_sur.bottle.tar.gz
Already downloaded: /Users/jenkins/Library/Caches/Homebrew/downloads/727045607bbb4925e393058b187598c10da17ee7db84414821a3bcd617df6164--gz-physics6-6.4.0.big_sur.bottle.tar.gz
Error: gz-sim7: SHA256 mismatch
Expected: 1d0586293d24f0200bcae7253dc466dd1e219fdf6cb6d7297d552b2b29babe7c
Actual: f7f7041e6bc4ab6da97aa418697c7914196fac471cef89e27f1b77287ec8ba4c
File: /Users/jenkins/Library/Caches/Homebrew/downloads/727045607bbb4925e393058b187598c10da17ee7db84414821a3bcd617df6164--gz-physics6-6.4.0.big_sur.bottle.tar.gz
```
I'll wait for @scpeters …
> gz-physics6: rebuild bottle

- Formula/ignition-msgs5.rb
* Remove unneeded dependency on `protobuf-c`
* Change dependency from `protobuf@21` back to `protobuf`
* Add patch from https://github.com/gazebosim/gz-msgs/pull/346 to fix compilation
* Disable broken `pkg-config` test
cc @traversaro
> gz-msgs5: rebuild, depend on protobuf

- Formula/ignition-transport8.rb
* Change `protobuf@21` dependency to `protobuf` and add patch from https://github.com/gazebosim/gz-transport/pull/405/
* Remove unneeded dependency on `protobuf-c`
* Disable broken `png-config` test
> gz-transport8: depend on protobuf, rebuild bottle

- Formula/ignition-msgs8.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
This adds patches for the following formulae:
* gz-sensors3, gz-sensors6 (from https://github.com/gazebosim/gz-sensors/pull/351)
* gz-msgs8 (similar to #2277)
* gz-transport11 (similar to #2278)
I'm going to merge the patches alone and then rebuild bottles separately in order to fix the formulae when building from source
> Some protobuf patches for citadel/fortress

- Formula/gz-msgs9.rb
- Formula/gz-transport12.rb
Part of #2274.
Depend on `protobuf`, add patch, remove unneeded dependency on `protobuf-c`, disable broken `png-config` test.
> gz-msgs9/transport12: patches for new protobuf

- Formula/ignition-gui3.rb
- Formula/ignition-gui6.rb
Part of #2274. Add patch from https://github.com/gazebosim/gz-gui/pull/544 to `gz-gui3` and `gz-gui6`. Also remove bottle block from `gz-gui3` that was built without this patch. I'm not sure how it worked, but it's causing an issue with `gz-sim3`, so let's rebuild after merging these patches.
> gz-gui3, gz-gui6: add protobuf patches

- Formula/gazebo11.rb
Part of #2274. Also depend on `protobuf`, not `protobuf@21` with patch from https://github.com/gazebosim/gazebo-classic/pull/3331.
I will merge this patch quickly and then open a separate PR to rebuild the bottle.
> gazebo11: patch for new version of protobuf

- Formula/gazebo11.rb
- Formula/gz-msgs9.rb
- Formula/gz-transport12.rb
- Formula/ignition-gui3.rb
- Formula/ignition-gui6.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
- Formula/ignition-transport8.rb
I think there was an ABI change in https://github.com/Homebrew/homebrew-core/pull/133818 because the bottles are broken again. This should remove all the relevant bottles that are currently built.
See also #2274.
> Remove broken protobuf bottles again

- Formula/gz-gui7.rb
- Formula/gz-gui8.rb
- Formula/gz-sensors7.rb
- Formula/gz-sensors8.rb
- Formula/gz-sim7.rb
- Formula/gz-sim8.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui3.rb
- Formula/ignition-gui6.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-sensors6.rb
These packages explicitly find protobuf, so add it as a dependency. Also remove some broken bottles missed in #2300.
> Add missing protobuf dependency to gui, sensors, sim

- Formula/gz-fuel-tools8.rb
- Formula/gz-fuel-tools9.rb
- Formula/ignition-fuel-tools4.rb
- Formula/ignition-fuel-tools7.rb
Also remove broken bottles for gz-fuel-tools4 and gz-fuel-tools7.
Part of #2274.
> gz-fuel-tools*: explicitly depend on protobuf

- Formula/gz-common5.rb
- Formula/gz-physics6.rb
Temporary fix for Garden until `apache-arrow` depends on unversioned protobuf.
Part of #2274.
> gz-common5: disable dependency on gdal

- Formula/gz-common5.rb
- Formula/gz-physics6.rb
gz-physics5: remove unneeded patch
Part of #2274
> gz-common5: re-enable gdal dependency

- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch5.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
Part of #2314.
~~~
for f in $(grep -L '^ *bottle do' $(grep -rnI depend.*ignition ignition-fortress.rb | sed -e 's@.* "@@' -e 's@"@.rb@'))
do
done
~~~
> Rebuild fortress bottles for protobuf 23.4

- Aliases/gz-harmonic
- Formula/gz-harmonic.rb
> gz-harmonic: new formula

- Formula/gz-cmake3.rb
- Formula/gz-math7.rb
- Formula/gz-tools2.rb
- Formula/gz-utils2.rb
Add cosmetic changes to some garden formulae in
order to build ventura bottles.
> Test build of some ventura bottles

- Formula/gz-transport13.rb
[Downstream](https://build.osrfoundation.org/view/ign-harmonic/job/ignition_sensors-ci-main-homebrew-amd64/87/consoleFull) builds are failing with
```
==> cmake .. -DBUILD_TESTING=Off -DCMAKE_INSTALL_RPATH=@loader_path/../lib
==> make install
Warning: Tried to install empty array to /usr/local/Cellar/gz-transport13/12.999.999~0~20230203/lib/python3.11/site-packages
Error: An exception occurred within a child process:
Errno::ENOENT: No such file or directory @ dir_s_rmdir - /usr/local/Cellar/gz-transport13/12.999.999~0~20230203/lib/python
```
> gz-transport13: Add pybind11 dependency

- Formula/gz-fuel-tools8.rb
- Formula/gz-gui7.rb
- Formula/gz-msgs9.rb
- Formula/gz-sensors7.rb
- Formula/gz-transport12.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2339
> Rebuild garden bottles for protobuf 24.1 part 1

- Formula/gz-fuel-tools8.rb
- Formula/gz-fuel-tools9.rb
- Formula/gz-gui7.rb
- Formula/gz-msgs10.rb
- Formula/gz-msgs9.rb
- Formula/gz-sensors7.rb
- Formula/gz-transport12.rb
- Formula/gz-transport13.rb
The recent release of abseil in https://github.com/Homebrew/homebrew-core/pull/139025 has broken our bottles that use protobuf yet again. This removes the broken bottles.
Lumping with https://github.com/osrf/homebrew-simulation/issues/2339.
> Remove broken abseil bottles

- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gui6.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2339
> Rebuild Fortress bottles for protobuf 24.1

- Formula/gz-sim7.rb
It should be fixed now that https://github.com/gazebosim/gz-physics/pull/529 has been merged and released. Tested successfully on [mac-five.monterey](https://build.osrfoundation.org/computer/mac-five.monterey/) in the following build (using https://github.com/gazebo-tooling/release-tools/pull/1005):
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_sim7-install_bottle-homebrew-amd64&build=185)](https://build.osrfoundation.org/job/ignition_sim7-install_bottle-homebrew-amd64/185/) https://build.osrfoundation.org/job/ignition_sim7-install_bottle-homebrew-amd64/185/
> gz-sim7: enable test on monterey

- Formula/ignition-fuel-tools4.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-gui3.rb
- Formula/ignition-launch2.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-transport8.rb
> Rebuild citadel bottles for protobuf

- Formula/gz-plugin2.rb
While reviewing https://github.com/osrf/homebrew-simulation/pull/2273, I noticed an issue on ARM Macs with the RPATH of the `gz-plugin` executable in the `libexec` folder. I've added a test for this executable to the `gz-plugin2` formula that I expect to pass on Intel CPUs and  fail on arm CPUs.
> gz-plugin2: test executable in libexec

- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch5.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-physics5.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
This adds a patch for gz-physics5 from https://github.com/gazebosim/gz-physics/pull/537 so that the gz-sim6 test on monterey can be enabled.
This also rebuilds the fortress bottles that depend on protobuf as part of #2394.
> Fortress: patch physics and rebuild bottles

- Formula/gz-plugin2.rb
Add an rpath entry with a relative path from the libexec subfolder containing the CLI executable to lib.
Fixes https://github.com/osrf/homebrew-simulation/issues/2403#issuecomment-1716888880.
This could alternatively be fixed in gz-plugin with something like https://github.com/gazebosim/gz-plugin/commit/c5d69a40ae73d1de0f5f9ab1ea5f734fe0d4bba6.
For reference, I copied the implementation for this from the [arrayfire](https://github.com/Homebrew/homebrew-core/blob/master/Formula/a/arrayfire.rb#L36-L51) formula in homebrew-core.
> gz-plugin: fix rpath for libexec/gz/plugin2

- Formula/ignition-fortress.rb
> ignition-fortress: build ventura bottle

- Formula/ignition-physics5.rb
- Formula/ignition-transport11.rb
Fix rpath for `gz-physics5` and `gz-transport11`.
> Fortress: fix rpath part 1

- Formula/ignition-gazebo6.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch5.rb
Fix rpath for binaries in remaining Fortress packages and add a patch for gz-launch5. Note this fixes rpath issues but that `gz sim -g` does not work as the patch from https://github.com/gazebosim/gz-sim/pull/1225 would need to be backported.
> Fortress: fix rpath part 2

- Aliases/gz-rendering9
- Formula/gz-rendering9.rb
> Bumps in ionic : ci_matching_branch/bump_ionic_gz-rendering9

- Aliases/gz-sensors9
- Formula/gz-sensors9.rb
> Bumps in ionic : ci_matching_branch/bump_ionic_gz-sensors9

- Aliases/gz-physics8
- Formula/gz-physics8.rb
> gz-physics8: new formula for ionic

- Formula/bullet@2.87.rb
- Formula/chrono-engine.rb
- Formula/simbody.rb
- Formula/sofa.rb
- Formula/tbb@2020_u3.rb
- Formula/tinyxml2@6.2.0.rb
Seems like brew has changed the linting to avoid github archive paths not using refs/tags, see https://github.com/osrf/homebrew-simulation/actions/runs/6655393821/job/18085564469?pr=2480.
Let's try to make it happy.
> Fix linting problems with github tarball refs

- Formula/gz-sim7.rb
- Formula/gz-sim8.rb
- Formula/gz-sim9.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-gazebo6.rb
These lines could have been removed in https://github.com/osrf/homebrew-simulation/pull/1833 and https://github.com/osrf/homebrew-simulation/pull/1840 when the dependencies on `ffmpeg@4` were reverted.
> gz-sim*: remove unneeded references to ffmpeg@4

- Formula/gz-fuel-tools9.rb
- Formula/gz-gui8.rb
- Formula/gz-launch7.rb
- Formula/gz-msgs10.rb
- Formula/gz-sensors8.rb
- Formula/gz-sim8.rb
- Formula/gz-transport13.rb
Part of #2483.
~~~
for f in $(grep -L '^ *bottle do' $(grep -rnI depend.*gz gz-harmonic.rb | sed -e 's@.* "@@' -e 's@"@.rb@'))
do
done
~~~
> Rebuild harmonic bottles for protobuf 25

- Formula/ignition-fuel-tools4.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-gui3.rb
- Formula/ignition-launch2.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-transport8.rb
Part of #2483.
~~~
for f in $(grep -L '^ *bottle do' $(grep -rnI depend.*ignition ignition-citadel.rb | sed -e 's@.* "@@' -e 's@"@.rb@'))
do
done
~~~
> Rebuild citadel bottles for protobuf 25

- Formula/gz-fuel-tools8.rb
- Formula/gz-gui7.rb
- Formula/gz-launch6.rb
- Formula/gz-msgs9.rb
- Formula/gz-sensors7.rb
- Formula/gz-sim7.rb
- Formula/gz-transport12.rb
~~~
for f in $(grep -L '^ *bottle do' $(grep -rnI depend.*gz gz-garden.rb | sed -e 's@.* "@@' -e 's@"@.rb@'))
do
done
~~~
> Rebuild garden bottles for protobuf 25.1

- Formula/dartsim@6.10.0.rb
- Formula/gz-physics6.rb
- Formula/gz-physics7.rb
- Formula/gz-physics8.rb
- Formula/ignition-physics2.rb
- Formula/ignition-physics5.rb
- Formula/sdformat12.rb
- Formula/sdformat13.rb
- Formula/sdformat14.rb
- Formula/sdformat4.rb
- Formula/sdformat9.rb
Part of #2505.
I added a missing dependency on `urdfdom` to the `gz-physics*` formulae in https://github.com/osrf/homebrew-simulation/commit/607c935005986e447f08e41709b08adeb054bb39 and then used the script from https://github.com/osrf/homebrew-simulation#to-disable-broken-bottles to remove the broken bottles.
This should be merged when https://github.com/Homebrew/homebrew-core/pull/158963 is merged.
> Remove broken bottles for urdfdom 4.0.0

- Formula/gz-garden.rb
- Formula/gz-launch6.rb
- Formula/gz-physics6.rb
- Formula/gz-sensors7.rb
- Formula/gz-sim7.rb
- Formula/sdformat13.rb
> Rebuild garden bottles for urdfdom 4.0.0

- Formula/gazebo11.rb
- Formula/ignition-citadel.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-launch2.rb
- Formula/ignition-physics2.rb
- Formula/ignition-sensors3.rb
- Formula/sdformat9.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2503 and #2505. Depend on a `brew extract`ed formula instead of `homebrew/core/tinyxml` in preparation for the removal of `tinyxml` from homebrew-core.
> sdformat9, gazebo11: use tinyxml1

- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gui6.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
Rebuild fortress bottles below gz-sim6, so I can separately update that to `python@3.12`.
> Rebuild most fortress bottles

- Formula/gz-math7.rb
Part of https://github.com/gazebosim/gz-sim/issues/2249.
> gz-math7: explicitly use python@3.11

- Formula/gz-math7.rb
- Formula/gz-sim7.rb
- Formula/sdformat13.rb
Used by macOS CI. Part of gazebosim/gz-sim#2249.
This can be merged without rebuilding any bottles.
> Garden: add python_cmake_arg method

- Formula/gz-math8.rb
- Formula/gz-msgs11.rb
- Formula/gz-sim9.rb
- Formula/gz-transport14.rb
- Formula/sdformat15.rb
Used by macOS CI. Part of https://github.com/gazebosim/gz-sim/issues/2249.
This includes two improvements to the `gz-sim9` formula and the addition of a `python_cmake_arg` method to all Ionic packages that install python bindings.
This can be merged without rebuilding any bottles.
> Ionic: add python_cmake_arg method

- Formula/gz-gui9.rb
The gz-gui9 pkg-config test fails without a useful error message. Running with --cflags and --libs will improve the error message.
> gz-gui9: improve test error message

- Formula/sdformat13.rb
Part of #2504. Patch is from https://github.com/gazebosim/sdformat/pull/1370.
> sdformat13: patch to fix finding python

- Formula/gz-fuel-tools8.rb
- Formula/gz-garden.rb
- Formula/gz-gui7.rb
- Formula/gz-launch6.rb
- Formula/gz-msgs9.rb
- Formula/gz-physics6.rb
- Formula/gz-sensors7.rb
- Formula/gz-sim7.rb
- Formula/gz-transport12.rb
- Formula/sdformat13.rb
Part of #2504.
~~~
for f in $(grep -L '^ *bottle do' $(grep -rnI 'depend.*"[gs][zd][-f]' gz-garden.rb | sed -e 's@.* "@@' -e 's@"@.rb@'))
do
done
brew bump-revision gz-garden --message="rebuild bottle"
~~~
> Garden: rebuild bottles for tinyxml2

- Formula/ignition-common3.rb
- Formula/ignition-fuel-tools4.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-transport8.rb
Part of #2504.
There are several dependencies shared by Citadel and Gazebo11. This rebuilds those common dependencies so that gazebo11 and the rest of Citadel can be built separately.
~~~
for f in $(grep -L '^ *bottle do' $(grep -rnI 'depend.*"ignition-' gazebo11.rb | sed -e 's@.* "@@' -e 's@"@.rb@'))
do
done
~~~
> Rebuild gazebo11 dependencies for tinyxml2

- Formula/dartsim@6.10.0.rb
- Formula/ignition-citadel.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-gui3.rb
- Formula/ignition-launch2.rb
- Formula/ignition-physics2.rb
- Formula/ignition-sensors3.rb
Part of #2504.
~~~
for f in $(grep -L '^ *bottle do' $(grep -rnI 'depend.*"[is][gd][nf]' ignition-citadel.rb | sed -e 's@.* "@@' -e 's@"@.rb@'))
do
done
brew bump-revision ignition-citadel --message="rebuild bottle"
~~~
> Citadel: rebuild bottles for tinyxml2

- Formula/gazebo11.rb
- Formula/gz-fuel-tools8.rb
- Formula/gz-fuel-tools9.rb
- Formula/gz-gui7.rb
- Formula/gz-gui8.rb
- Formula/gz-launch6.rb
- Formula/gz-launch7.rb
- Formula/gz-msgs10.rb
- Formula/gz-msgs9.rb
- Formula/gz-sensors7.rb
- Formula/gz-sensors8.rb
- Formula/gz-sim7.rb
- Formula/gz-sim8.rb
- Formula/gz-transport12.rb
- Formula/gz-transport13.rb
- Formula/ignition-fuel-tools4.rb
- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui3.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch2.rb
- Formula/ignition-launch5.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
- Formula/ignition-transport8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2571.
Commits for the pull request were created with the following command:
~~~
for f in $(grep -l '^ *bottle do' $(grep -rlI depend.*protobuf .) | sort)
do
done
~~~
> Remove bottles broken by protobuf 25.3

- Formula/ignition-fuel-tools4.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-transport8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2571.
This rebuilds the dependencies shared by Citadel and gazebo11, with commits generated using the following command:
~~~
for f in $(grep -L '^ *bottle do' $(grep -rnI 'depend.*"[gsi][zdg][-fn]' gazebo11.rb | sed -e 's@.* "@@' -e 's@"@.rb@'))
do
done
~~~
> Citadel: rebuild some bottles for protobuf

- Formula/gazebo11.rb
Needed for https://github.com/osrf/homebrew-simulation/issues/2571, patch from https://github.com/gazebosim/gazebo-classic/commit/3a9efee7ccdf552cbf22188131782f242f6c0542.
> gazebo11: patch to fix build with graphviz 10.0

- Formula/gz-gui7.rb
- Formula/gz-gui8.rb
- Formula/gz-gui9.rb
- Formula/gz-launch6.rb
- Formula/gz-launch7.rb
- Formula/gz-launch8.rb
- Formula/gz-physics6.rb
- Formula/gz-physics7.rb
- Formula/gz-physics8.rb
- Formula/gz-rendering7.rb
- Formula/gz-rendering8.rb
- Formula/gz-rendering9.rb
- Formula/gz-sim7.rb
- Formula/gz-sim8.rb
- Formula/gz-sim9.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch5.rb
- Formula/ignition-physics5.rb
- Formula/ignition-rendering6.rb
- Formula/ogre2.2.rb
- Formula/ogre2.3.rb
Follow-up to Homebrew/brew#16848.
First noticed in the following build:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_rendering7-install_bottle-homebrew-amd64&build=87)](https://build.osrfoundation.org/view/gz-garden/job/gz_rendering7-install_bottle-homebrew-amd64/87/) https://build.osrfoundation.org/view/gz-garden/job/gz_rendering7-install_bottle-homebrew-amd64/87/
~~~
+ brew audit --strict gz-rendering7
osrf/simulation/gz-rendering7
* line 56, col 45: Omit the hash value.
Error: 1 problem in 1 formula detected.
~~~
> Fix hash syntax

- Formula/gz-fuel-tools9.rb
- Formula/gz-gui8.rb
- Formula/gz-launch7.rb
- Formula/gz-msgs10.rb
- Formula/gz-sensors8.rb
- Formula/gz-sim8.rb
- Formula/gz-transport13.rb
- Formula/ignition-citadel.rb
- Formula/ignition-fortress.rb
- Formula/ignition-fuel-tools4.rb
- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui3.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch2.rb
- Formula/ignition-launch5.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
- Formula/ignition-transport8.rb
Part of #2611.
Implemented using a script from https://github.com/osrf/homebrew-simulation/pull/2610:
~~~
do
do
done
done
~~~
The garden bottles (dependents of gz-msgs9) hadn't been rebuilt from the last failure, so there's fewer bottles to remove.
> Remove bottles broken by protobuf 26.0

- Formula/gz-common5.rb
- Formula/gz-fuel-tools8.rb
- Formula/gz-fuel-tools9.rb
- Formula/gz-gui7.rb
- Formula/gz-gui8.rb
- Formula/gz-launch6.rb
- Formula/gz-launch7.rb
- Formula/gz-physics6.rb
- Formula/gz-physics7.rb
- Formula/gz-rendering7.rb
- Formula/gz-rendering8.rb
- Formula/gz-sensors7.rb
- Formula/gz-sensors8.rb
- Formula/gz-sim7.rb
- Formula/gz-sim8.rb
Part of #2639.
Only the ventura bottles are affected, so use a targeted sed script to delete the ventura bottle line with the following command:
~~~
sed -i -e '/sha256 .*ventura: /d' $(brew --repo osrf/simulation)/Formula/gz-common5.rb
for f in $(.github/ci/bottled_dependents.sh gz-common5 | sed -e 's@osrf/simulation/@@')
do
sed -i -e '/sha256 .*ventura: /d' $(brew --repo osrf/simulation)/Formula/$f.rb
done
~~~
> gz-common5, dependents: remove ventura bottle

- Formula/gz-common5.rb
Part of #2639. Rebuild now since https://github.com/Homebrew/brew/pull/17104 has landed.
> gz-common5: revision bump for llvm

- Formula/gz-common5.rb
- Formula/gz-fuel-tools8.rb
- Formula/gz-fuel-tools9.rb
- Formula/gz-gui7.rb
- Formula/gz-gui8.rb
- Formula/gz-launch6.rb
- Formula/gz-launch7.rb
- Formula/gz-physics6.rb
- Formula/gz-physics7.rb
- Formula/gz-rendering7.rb
- Formula/gz-rendering8.rb
- Formula/gz-sensors7.rb
- Formula/gz-sensors8.rb
- Formula/gz-sim7.rb
- Formula/gz-sim8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2651.
Implemented using a script from https://github.com/osrf/homebrew-simulation/pull/2610:
~~~
for m in gz-common5
do
do
done
done
~~~
> Remove bottles broken by gdal 3.9.0

- Formula/ogre1.9.rb
This applies a patch from @marvinosswald and sets CMAKE_CXX_STANDARD to use c++14 to fix compilation errors when building `ogre1.9` from source.
I tested this with gazebo11, and it seems to work still. We don't need new bottles though since bottles are still working; it is just building from source that is broken.
Fixes https://github.com/osrf/homebrew-simulation/issues/2646.
> ogre1.9: fix build from source

- .github/ci/bottled_dependents.sh
- .github/ci/unbottled_dependencies.bash
- .github/ci/unbottled_dependencies.sh
I'm working on a GitHub actions workflows to automate removing broken bottles and rebuilding missing bottles, and I'm starting with two scripts:
* `unbottled_dependencies.sh` prints the unbottled dependencies needed by a given formula (useful for rebuilding bottles)
* `bottled_dependents.sh` prints the bottled dependents that use a given formula (useful for removing broken bottles)
Gazebo Ionic not yet bottled, so it has lots of unbottled dependencies:
~~~
$ ./unbottled_dependencies.sh gz-ionic
osrf/simulation/gz-cmake4
osrf/simulation/gz-common6
osrf/simulation/gz-fuel-tools10
osrf/simulation/gz-gui9
osrf/simulation/gz-launch8
osrf/simulation/gz-math8
osrf/simulation/gz-msgs11
osrf/simulation/gz-physics8
osrf/simulation/gz-plugin3
osrf/simulation/gz-rendering9
osrf/simulation/gz-sensors9 …
> Add scripts to help identify bottled / unbottled formulae

- Formula/gazebo11.rb
- Formula/gz-fuel-tools8.rb
- Formula/gz-fuel-tools9.rb
- Formula/gz-gui7.rb
- Formula/gz-gui8.rb
- Formula/gz-launch6.rb
- Formula/gz-launch7.rb
- Formula/gz-msgs10.rb
- Formula/gz-msgs9.rb
- Formula/gz-sensors7.rb
- Formula/gz-sensors8.rb
- Formula/gz-sim7.rb
- Formula/gz-sim8.rb
- Formula/gz-transport12.rb
- Formula/gz-transport13.rb
- Formula/ignition-fuel-tools4.rb
- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui3.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch2.rb
- Formula/ignition-launch5.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
- Formula/ignition-transport8.rb
Part of #2659.
~~~
do
do
done
done
~~~
> Remove bottles broken by protobuf 27.0

- Formula/gazebo11.rb
- Formula/gz-fuel-tools8.rb
- Formula/gz-fuel-tools9.rb
- Formula/gz-gui7.rb
- Formula/gz-gui8.rb
- Formula/gz-launch6.rb
- Formula/gz-launch7.rb
- Formula/gz-msgs10.rb
- Formula/gz-msgs9.rb
- Formula/gz-sensors7.rb
- Formula/gz-sensors8.rb
- Formula/gz-sim7.rb
- Formula/gz-sim8.rb
- Formula/gz-transport12.rb
- Formula/gz-transport13.rb
- Formula/ignition-fuel-tools4.rb
- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui3.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch2.rb
- Formula/ignition-launch5.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
- Formula/ignition-transport8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2668.
~~~
do
do
done
done
~~~
> Remove bottles broken by protobuf 27.1

- Formula/gazebo11.rb
- Formula/gz-physics6.rb
- Formula/gz-physics7.rb
- Formula/ignition-physics5.rb
Part of #2688.
Merge immediately after https://github.com/Homebrew/homebrew-core/pull/175563 is merged (if not before).
~~~
for f in $(.github/ci/bottled_dependents.sh dartsim)
do
done
~~~
> Remove bottles broken by dartsim 6.14.0

- Formula/ogre1.9.rb
Part of #2699.
I tested this locally with gazebo-classic on an intel machine and it still works, so I think this is safe, and it has been suggested that this improves support for arm-based processors.
> ogre1.9: remove configuration forcing x86_64

- Formula/gazebo11.rb
- Formula/gz-fuel-tools8.rb
- Formula/gz-fuel-tools9.rb
- Formula/gz-gui7.rb
- Formula/gz-gui8.rb
- Formula/gz-launch6.rb
- Formula/gz-launch7.rb
- Formula/gz-msgs10.rb
- Formula/gz-msgs9.rb
- Formula/gz-sensors7.rb
- Formula/gz-sensors8.rb
- Formula/gz-sim7.rb
- Formula/gz-sim8.rb
- Formula/gz-transport12.rb
- Formula/gz-transport13.rb
- Formula/ignition-fuel-tools4.rb
- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui3.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch2.rb
- Formula/ignition-launch5.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
- Formula/ignition-transport8.rb
Part of #2698.
~~~
do
do
done
done
~~~
> Remove bottles broken by protobuf 27.3

- Formula/gz-fuel-tools9.rb
- Formula/gz-gui8.rb
- Formula/gz-launch7.rb
- Formula/gz-msgs10.rb
- Formula/gz-sensors8.rb
- Formula/gz-sim8.rb
- Formula/gz-transport13.rb
- Formula/ignition-fuel-tools4.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-gui3.rb
- Formula/ignition-launch2.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-transport8.rb
Bottles are broken due to https://github.com/Homebrew/homebrew-core/pull/179381
Patch from running
```
do
do
done
done
```
> Remove bottles broken by abseil 20240722.0 (redo)

- Formula/sdformat14.rb
@iche033 This reverts commit dcc70d5c4a23ce49fab23e8fbf8a30537c6757a9 so that Harmonic is not broken on macOS until we rebuild all the bottles and resolve the root issue.
> Revert "sdformat14: update 14.5.0 (#2716)"

- Formula/gz-fuel-tools9.rb
- Formula/gz-gui8.rb
- Formula/gz-launch7.rb
- Formula/gz-msgs10.rb
- Formula/gz-physics7.rb
- Formula/gz-sensors8.rb
- Formula/gz-sim8.rb
- Formula/gz-transport13.rb
- Formula/sdformat14.rb
This also rebuilds sdformat14 which failed to build in #2716 and was reverted in #2720.
> Rebuild harmonic bottles for protobuf 27.3

- Formula/gz-math8.rb
As reported in https://github.com/gazebosim/gz-math/pull/614#issuecomment-2284101515, the gz-math8 bottle install jobs are broken after https://github.com/gazebosim/gz-math/pull/614. This is because the PR made changes to the `SignalStats.hh` file to include a header from `gz-utils`. One solution is to update the manual flags to include `gz-utils3`, but that proved to be nontrivial because the variables defined by homebrew are specific to the package being built, in this case gz-math8. Figuring out the library and include directories for `gz-utils3` would involve using the `HOMEBREW_PREFIX` variable and somehow determining the version of `gz-utils3`. So, instead I opted to remove this test. @scpeters suggested implementing a replacement with `pkg-config`, but I think we should do that in …
> gz-math8: remove test based on manual compiler flags

- Formula/ignition-fuel-tools4.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-gui3.rb
- Formula/ignition-launch2.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-transport8.rb
Second try at https://github.com/osrf/homebrew-simulation/pull/2712. Part of https://github.com/osrf/homebrew-simulation/issues/2698.
Created using:
~~~
do
done
~~~
> Rebuild citadel bottles for protobuf / abseil

- Formula/gz-math8.rb
Follow-up to #2723. The test is adapted from that used in other formulae, like [sdformat14](https://github.com/osrf/homebrew-simulation/blob/master/Formula/sdformat14.rb#L74-L82).
> gz-math8: add pkg-config test

- Formula/gz-garden.rb
- Formula/gz-harmonic.rb
Test the existence of the collection yaml file instead of trying to verify it with vcstool since there are some python issues. This more closely matches the test for gz-ionic.
This should fix the broken bottle install builds:
* [![gz-garden](https://build.osrfoundation.org/buildStatus/icon?job=gz_garden-install_bottle-homebrew-amd64)](https://build.osrfoundation.org/view/gz-garden/job/gz_garden-install_bottle-homebrew-amd64/) https://build.osrfoundation.org/view/gz-garden/job/gz_garden-install_bottle-homebrew-amd64/
* [![gz-harmonic](https://build.osrfoundation.org/buildStatus/icon?job=gz_harmonic-install_bottle-homebrew-amd64)](https://build.osrfoundation.org/view/gz-harmonic/job/gz_harmonic-install_bottle-homebrew-amd64/) https://build.osrfoundation.org/view/gz-harmonic/job/gz_harmonic-i …
> gz-garden, gz-harmonic: simplify test

- Formula/cmake@3.21.4.rb
- Formula/gazebo9.rb
- Formula/ignition-cmake0.rb
- Formula/ignition-common1.rb
- Formula/ignition-fuel-tools1.rb
- Formula/ignition-math4.rb
- Formula/ignition-msgs1.rb
- Formula/ignition-transport4.rb
- Formula/ogre.rb
- Formula/sdformat6.rb
- Formula/tbb@2020_u3.rb
This includes gazebo9 and dependencies. These have all been deprecated since January 2023.
Also deprecate `ogre` 1.7 formula since it is past its end-of-life.
> Disable deprecated formulae on 2024-08-31

- Formula/gz-utils3.rb
related to https://github.com/gazebosim/gz-utils/pull/134
> gz-utils3: Add spdlog dependency

- Formula/gz-cmake4.rb
Note that I didn't have to change the `head` statement on line 8. For some reason it was already set to `gz-cmake4` instead of `main`.
> gz-cmake4: use stable branch in url

- Formula/gz-utils3.rb
> gz-utils3: use stable branch in url

- Formula/gz-math8.rb
> gz-math8: use stable branch in url

- Formula/gz-rendering9.rb
> gz-rendering9: use stable branch

- Formula/gz-sensors9.rb
> gz-sensors9: use stable branch

- Formula/gazebo11.rb
Patch from https://github.com/gazebosim/gazebo-classic/pull/3397 to fix build with boost 1.86.
> gazebo11: patch for boost 1.86

- Formula/gz-msgs11.rb
> Ionic: Use gz-msgs11 stable branch

- Formula/gz-transport14.rb
> Ionic: Use gz-transport14 stable branch

- Formula/gz-plugin3.rb
> Ionic: Use gz-plugin3 stable branch

- Formula/gz-physics8.rb
Update CMakeLists.txt test version to 3.22.1
> gz-physics8: use stable branch

- Formula/gz-launch8.rb
> gz-launch8: use stable branch

- Formula/gz-common6.rb
to go with: https://github.com/gazebosim/gz-common/pull/615
note: `gz-utils3` should pull in `spdlog` so this may not be necessary.
> gz-common6: depend on spdlog

- Formula/gz-common6.rb
bottles failed to build for gz-common6 in #2773 due to a test failure.
> gz-common6: disable pkg-config test

- Formula/gz-physics6.rb
- Formula/gz-physics7.rb
- Formula/ignition-physics5.rb
A recent update to fmt has broken several gz-physics bottles, via its usage by dartsim. I've added an explicit dependency on fmt to help with identifying future issues like this.
Part of #2745.
> gz-physics*: remove bottles for fmt

- Formula/gz-physics6.rb
- Formula/gz-physics7.rb
- Formula/ignition-physics5.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2745.
> gz-physics*:  bump versions to rebuild bottles for new fmt

- Formula/gz-fuel-tools10.rb
- Formula/gz-gui9.rb
- Formula/gz-launch8.rb
- Formula/gz-physics8.rb
- Formula/gz-rendering9.rb
- Formula/gz-sensors9.rb
- Formula/gz-sim9.rb
Bottles for packages downstream of gz-common6 failed in #2773 due to a failure in gz-common6. This PR is to build the rest of the bottles now that that failure has been fixed (#2774)
> Ionic: Rebuild bottles after gz-common6

- Formula/gz-gui9.rb
Follow up to #2774.
Test is currently failing, so disable it.
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_gui9-install_bottle-homebrew-amd64&build=267)](https://build.osrfoundation.org/view/gz-ionic/job/gz_gui9-install_bottle-homebrew-amd64/267/) https://build.osrfoundation.org/view/gz-ionic/job/gz_gui9-install_bottle-homebrew-amd64/267/
> gz-gui9: disable pkg-config test

- Formula/dartsim@6.10.0.rb
- Formula/ignition-common3.rb
- Formula/ignition-physics2.rb
- Formula/ignition-rendering3.rb
- Formula/ogre2.1.rb
- Formula/sdformat9.rb
- Formula/simbody.rb
- Formula/tinyxml1.rb
Make trivial changes to allow building all formulae used in citadel and gazebo11 that don't use protobuf, since that will be addressed by #2791.
> Citadel: build sonoma bottles part 2

- Formula/ignition-rendering3.rb
This formula's Sonoma bottle failed its `brew test` in #2799. I noticed some rpath fixes in the fortress formula that hadn't been backported to citadel, so I'm backporting the fix here and bumping the revision to that the Ventura bottle will be rebuilt as well.
> gz-rendering3: fix rpath issues

- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch5.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
Part of #2791.
Created using:
~~~
do
done
~~~
> Rebuild fortress bottles for protobuf 28.2

- Aliases/gz-cmake5
- Aliases/gz-common7
- Aliases/gz-fuel-tools11
- Aliases/gz-gui10
- Aliases/gz-launch9
- Aliases/gz-math9
- Aliases/gz-msgs12
- Aliases/gz-physics9
- Aliases/gz-plugin4
- Aliases/gz-rendering10
- Aliases/gz-sensors10
- Aliases/gz-sim10
- Aliases/gz-transport15
- Aliases/gz-utils4
- Aliases/sdformat16
https://github.com/gazebo-tooling/release-tools/issues/1092
Add aliases for the next major version of all libraries (except gz-tools3 which exists already).
> Add aliases for versions post-Ionic

- Formula/gz-math8.rb
Part of #2834. Uses patch from https://github.com/gazebosim/gz-math/pull/636.
> gz-math8: patch to build multiple python bindings

- Formula/gz-math7.rb
- Formula/gz-msgs10.rb
- Formula/gz-msgs11.rb
- Formula/gz-sim7.rb
- Formula/gz-sim8.rb
- Formula/gz-sim9.rb
- Formula/gz-transport13.rb
- Formula/gz-transport14.rb
- Formula/sdformat13.rb
- Formula/sdformat14.rb
- Formula/sdformat15.rb
Use opt_libexec/bin/python, which works for python@3.11, python@3.12, and python@3.13 formulae.
This is particularly needed because the `bin/python3` symlink has been removed from `python@3.12`, which caused a bottle failure in #2840.
> Fix python path in tests

- Formula/gz-math7.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2834. Applies patches from https://github.com/gazebosim/gz-math/pull/640.
> gz-math7: patch to build multiple python bindings

- Formula/gz-msgs11.rb
Part of #2834.
This package doesn't generate python binaries, just python files, so we can just symlink the generated python files to versioned python folders.
> gz-msgs11: support multiple python versions

- Formula/gz-msgs10.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2834.
This package doesn't generate python binaries, just python files, so we can just symlink the generated python files to versioned python folders.
> gz-msgs10: support multiple python versions

- .github/workflows/main.yml
Failure first noticed in #2836.
> GitHub workflow: use actions/cache@v4

- Formula/gz-math8.rb
- Formula/sdformat15.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2834. Build bindings for both python@3.12 and python@3.13.
The following is a test of this branch, that only fails because of a `brew audit` error, which I am discussing with homebrew maintainers in https://github.com/Homebrew/brew/pull/18552:
Test: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_math8-install_bottle-homebrew-amd64&build=303)](https://build.osrfoundation.org/view/gz-ionic/job/gz_math8-install_bottle-homebrew-amd64/303/) https://build.osrfoundation.org/view/gz-ionic/job/gz_math8-install_bottle-homebrew-amd64/303/
> sdformat15: support multiple python versions

- Formula/sdformat14.rb
Part of #2834, including patches from https://github.com/gazebosim/sdformat/pull/1496 and https://github.com/gazebosim/sdformat/pull/1497.
> sdformat14: support multiple python versions

- Formula/gz-common5.rb
- Formula/gz-common6.rb
- Formula/gz-fuel-tools8.rb
- Formula/gz-physics6.rb
- Formula/gz-physics7.rb
- Formula/gz-physics8.rb
- Formula/gz-rendering7.rb
- Formula/gz-rendering8.rb
- Formula/gz-rendering9.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2845.
~~~
for m in gz-common5 gz-common6
do
do
done
done
~~~
> Remove bottles broken by gdal 3.10.0

- Formula/gz-common5.rb
- Formula/gz-fuel-tools8.rb
- Formula/gz-gui7.rb
- Formula/gz-launch6.rb
- Formula/gz-physics6.rb
- Formula/gz-rendering7.rb
- Formula/gz-sensors7.rb
- Formula/gz-sim7.rb
Part of #2845.
~~~
do
brew bump-revision --message="rebuild for gdal" $f
done
~~~
> Rebuild garden bottles for gdal 3.10

- Formula/gz-transport14.rb
Part of #2834, currently pointing to branch for https://github.com/gazebosim/gz-transport/pull/554.
Testing:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_transport14-install_bottle-homebrew-amd64&build=330)](https://build.osrfoundation.org/view/gz-ionic/job/gz_transport14-install_bottle-homebrew-amd64/330/) https://build.osrfoundation.org/view/gz-ionic/job/gz_transport14-install_bottle-homebrew-amd64/330/
> gz-transport14: support multiple python versions

- Formula/gz-transport13.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2834, includes a patch from https://github.com/gazebosim/gz-transport/pull/555.
Testing:
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_transport13-install_bottle-homebrew-amd64&build=340)](https://build.osrfoundation.org/view/gz-harmonic/job/gz_transport13-install_bottle-homebrew-amd64/340/) https://build.osrfoundation.org/view/gz-harmonic/job/gz_transport13-install_bottle-homebrew-amd64/340/
> gz-transport13: support multiple python versions

- Formula/gz-common6.rb
- Formula/gz-fuel-tools10.rb
- Formula/gz-gui9.rb
- Formula/gz-math8.rb
- Formula/gz-msgs11.rb
- Formula/gz-plugin3.rb
- Formula/gz-rendering9.rb
- Formula/gz-sensors9.rb
- Formula/gz-transport14.rb
- Formula/gz-utils3.rb
- Formula/sdformat15.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2882.
~~~
for m in gz-utils3
do
do
done
done
~~~
> Remove bottles broken by spdlog 1.15.0

- Formula/gazebo11.rb
- Formula/gz-fuel-tools10.rb
- Formula/gz-fuel-tools9.rb
- Formula/gz-gui8.rb
- Formula/gz-gui9.rb
- Formula/gz-msgs10.rb
- Formula/gz-msgs11.rb
- Formula/gz-sensors8.rb
- Formula/gz-sensors9.rb
- Formula/gz-transport13.rb
- Formula/gz-transport14.rb
- Formula/ignition-fuel-tools4.rb
- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui3.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch2.rb
- Formula/ignition-launch5.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
- Formula/ignition-transport8.rb
Part of #2896.
~~~
for m in gz-msgs11 gz-msgs10 gz-msgs8 gz-msgs5
do
do
done
done
~~~
> Remove bottles broken by protobuf 29.0

- Formula/gz-fuel-tools10.rb
- Formula/gz-gui9.rb
- Formula/gz-msgs11.rb
- Formula/gz-sensors9.rb
- Formula/gz-transport14.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2896.
~~~
for f in $(.github/ci/unbottled_dependencies.sh gz-sim9)
do
done
~~~
> Ionic: rebuild gz-sim9 dependents broken by protobuf 29

- Formula/gz-fuel-tools9.rb
- Formula/gz-gui8.rb
- Formula/gz-msgs10.rb
- Formula/gz-sensors8.rb
- Formula/gz-transport13.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2896.
~~~
for f in $(.github/ci/unbottled_dependencies.sh gz-sim8)
do
done
~~~
> Harmonic: rebuild gz-sim9 dependents broken by protobuf 29

- Formula/ignition-fuel-tools4.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-gui3.rb
- Formula/ignition-launch2.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-transport8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2896.
~~~
do
done
~~~
> Citadel: rebuild bottles broken by protobuf 29

- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch5.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2896.
~~~
do
done
~~~
> Fortress: rebuild bottles broken by protobuf 29

- Formula/gz-sim9.rb
Part of #2834. For now just update to use the current default python version.
> gz-sim9: use python@3.13

- Formula/gz-sim8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2834. For now just update to use the current default python version.
> gz-sim8: use python@3.13

- Formula/gazebo11.rb
- Formula/gz-fuel-tools10.rb
- Formula/gz-fuel-tools9.rb
- Formula/gz-gui8.rb
- Formula/gz-gui9.rb
- Formula/gz-msgs10.rb
- Formula/gz-msgs11.rb
- Formula/gz-sensors8.rb
- Formula/gz-sensors9.rb
- Formula/gz-sim8.rb
- Formula/gz-sim9.rb
- Formula/gz-transport13.rb
- Formula/gz-transport14.rb
- Formula/ignition-fuel-tools4.rb
- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui3.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch2.rb
- Formula/ignition-launch5.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
- Formula/ignition-transport8.rb
Part of #2906.
Merge when https://github.com/Homebrew/homebrew-core/pull/200077 has merged, if not sooner.
~~~
for m in gz-msgs11 gz-msgs10 gz-msgs8 gz-msgs5
do
do
done
done
~~~
> Remove bottles broken by protobuf 29.1

- Formula/gz-fuel-tools9.rb
- Formula/gz-gui8.rb
- Formula/gz-launch7.rb
- Formula/gz-msgs10.rb
- Formula/gz-sensors8.rb
- Formula/gz-sim8.rb
- Formula/gz-transport13.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2906.
~~~
do
done
~~~
> Harmonic: rebuild bottles broken by protobuf 29.1

- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch5.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2906.
~~~
do
done
~~~
> Fortress: rebuild bottles broken by protobuf 29.1

- Formula/ignition-fuel-tools4.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-gui3.rb
- Formula/ignition-launch2.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-transport8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2906.
~~~
do
done
~~~
> Citadel: rebuild bottles broken by protobuf 29.1

- Formula/gz-fuel-tools10.rb
- Formula/gz-fuel-tools9.rb
- Formula/gz-gui8.rb
- Formula/gz-gui9.rb
- Formula/gz-launch7.rb
- Formula/gz-launch8.rb
- Formula/gz-msgs10.rb
- Formula/gz-msgs11.rb
- Formula/gz-sensors8.rb
- Formula/gz-sensors9.rb
- Formula/gz-sim8.rb
- Formula/gz-sim9.rb
- Formula/gz-transport13.rb
- Formula/gz-transport14.rb
- Formula/ignition-fuel-tools4.rb
- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gazebo3.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui3.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch2.rb
- Formula/ignition-launch5.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
- Formula/ignition-transport8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2920.
~~~
for m in gz-msgs11 gz-msgs10 gz-msgs8 gz-msgs5
do
do
done
done
~~~
> Remove bottles broken by protobuf 29.2

- Formula/gz-fuel-tools9.rb
- Formula/gz-gui8.rb
- Formula/gz-launch7.rb
- Formula/gz-msgs10.rb
- Formula/gz-sensors8.rb
- Formula/gz-sim8.rb
- Formula/gz-transport13.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2920.
~~~
do
done
~~~
> Harmonic: rebuild bottles broken by protobuf 29.2

- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch5.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2920.
~~~
do
done
~~~
> Fortress: rebuild bottles broken by protobuf 29.2

- Formula/ignition-fuel-tools4.rb
- Formula/ignition-gui3.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-sensors3.rb
- Formula/ignition-transport8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2920.
This skips the bottles that don't work due to #2917.
> Citadel: rebuild bottles broken by protobuf 29.2 (part 1)

- Formula/gz-utils3.rb
Needed by https://github.com/gazebosim/gz-utils/pull/167.
> gz-utils3: depend on cli11

- Formula/gz-fuel-tools10.rb
- Formula/gz-fuel-tools9.rb
- Formula/gz-gui8.rb
- Formula/gz-gui9.rb
- Formula/gz-launch7.rb
- Formula/gz-launch8.rb
- Formula/gz-msgs10.rb
- Formula/gz-msgs11.rb
- Formula/gz-sensors8.rb
- Formula/gz-sensors9.rb
- Formula/gz-sim8.rb
- Formula/gz-sim9.rb
- Formula/gz-transport13.rb
- Formula/gz-transport14.rb
- Formula/ignition-fuel-tools4.rb
- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch5.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
- Formula/ignition-transport8.rb
Merge when https://github.com/Homebrew/homebrew-core/pull/203651 has merged or is about to merge.
Part of #2929.
~~~
for m in gz-msgs11 gz-msgs10 gz-msgs8 gz-msgs5
do
do
done
done
~~~
> Remove bottles broken by protobuf 29.3

- Formula/gz-fuel-tools10.rb
- Formula/gz-gui9.rb
- Formula/gz-launch8.rb
- Formula/gz-msgs11.rb
- Formula/gz-sensors9.rb
- Formula/gz-sim9.rb
- Formula/gz-transport14.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2929.
~~~
do
done
~~~
> Ionic: rebuild bottles broken by protobuf 29.3

- Formula/gz-fuel-tools9.rb
- Formula/gz-gui8.rb
- Formula/gz-launch7.rb
- Formula/gz-msgs10.rb
- Formula/gz-sensors8.rb
- Formula/gz-sim8.rb
- Formula/gz-transport13.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2929.
~~~
do
done
~~~
> Harmonic: rebuild bottles broken by protobuf 29.3

- Formula/ignition-fuel-tools4.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-transport8.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2929.
~~~
for f in $(.github/ci/unbottled_dependencies.sh gazebo11)
do
done
~~~
> gazebo11 deps: rebuild bottles broken by protobuf 29.3

- Formula/boost@1.85.0.rb
- Formula/gazebo11.rb
- Formula/ogre1.9-with-boost1.85.rb
This is a workaround for #2916 and https://github.com/gazebosim/gazebo-classic/issues/3414 that uses forked versions of `boost` and `ogre1.9`:
* `boost@1.85.0` (derived using `brew extract bost@1.85 osrf/simulation`)
* `ogre1.9-with-boost1.85` (copied from `ogre1.9`)
If we find a fix for https://github.com/gazebosim/gazebo-classic/issues/3414, we can revert to using the system version of `boost`.
Note that `boost@1.85.0` and `ogre1.9-with-boost1.85` are keg-only, which means they are not sym-linked to `HOMEBREW_PREFIX`, so compiling gazebo11 from source or compiling custom plugins will require setting additional environment variables, similar to the approach for `qt@5` in the [build-from-source documentation](https://gazebosim.org/docs/latest/install_osx_src/#install-dependencies).
> gazebo11: use boost 1.85

- Formula/gz-gui10.rb
> gui10: fix rpath

- Aliases/gz-jetty
- Formula/gz-jetty.rb
> gz-jetty: new formula

- Formula/gz-common5.rb
- Formula/gz-plugin2.rb
- Formula/sdformat14.rb
Cherry-picked #2956 and #2955 as well to reduce build time.
> sdformat14 14.7.0, harmonic patch releases

- README.md
There are issues with building bottles simultaneously in multiple pull requests, and this documents those issues and describes strategies for how to build bottles effectively when there are multiple open pull requests.
As indicated in the changes added here, due to #1990, please do not merge this while any bottle builds are ongoing for other pull requests.
> README: how to handle multiple pull requests

- Formula/gz-garden.rb
- Formula/gz-harmonic.rb
- Formula/gz-ionic.rb
- Formula/gz-jetty.rb
Fix brew test-bot warnings such as:
```
Taps/osrf/homebrew-simulation/Formula/gz-garden.rb:44:5: C: [Correctable] FormulaAudit/AssertStatements: Use assert_path_exists <path_to_file> instead of assert_predicate share/"gz/gz-garden/gazebodistro/collection-garden.yaml", :exist?
assert_predicate share/"gz/gz-garden/gazebodistro/collection-garden.yaml", :exist?
```
> Fix brew style warnings in gz-<collection>.rb files

- Formula/gz-sim10.rb
Related issue: https://github.com/gazebosim/gz-launch/issues/288
Needed by: https://github.com/gazebosim/gz-sim/pull/2792
The websocket server is being ported from gz-launch to gz-sim. This adds `libwebsockets` dependency to gz-sim10 for Jetty. Note: I don't see this in the gz-launch9 formula as I think it's only an optional dependency there.
> gz-sim10: depend on libwebsockets

- Formula/gz-common5.rb
- Formula/gz-common6.rb
- Formula/gz-fuel-tools10.rb
- Formula/gz-fuel-tools9.rb
- Formula/gz-gui8.rb
- Formula/gz-gui9.rb
- Formula/gz-launch7.rb
- Formula/gz-launch8.rb
- Formula/gz-msgs10.rb
- Formula/gz-msgs11.rb
- Formula/gz-physics7.rb
- Formula/gz-physics8.rb
- Formula/gz-sensors8.rb
- Formula/gz-sensors9.rb
- Formula/gz-sim8.rb
- Formula/gz-sim9.rb
- Formula/gz-transport13.rb
- Formula/gz-transport14.rb
- Formula/ignition-common4.rb
- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gui6.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-physics5.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
- Formula/ignition-transport8.rb
- Formula/sdformat12.rb
- Formula/sdformat14.rb
- Formula/sdformat15.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2992.
Generated with:
~~~
for f in $(.github/ci/bottled_dependents.sh tinyxml2)
do
done
~~~
> Remove bottles broken by tinyxml2 10.1.0

- Formula/gz-common5.rb
- Formula/gz-common6.rb
- Formula/gz-fuel-tools10.rb
- Formula/gz-fuel-tools9.rb
- Formula/gz-gui8.rb
- Formula/gz-gui9.rb
- Formula/gz-launch7.rb
- Formula/gz-launch8.rb
- Formula/gz-msgs10.rb
- Formula/gz-msgs11.rb
- Formula/gz-physics7.rb
- Formula/gz-physics8.rb
- Formula/gz-sensors8.rb
- Formula/gz-sensors9.rb
- Formula/gz-sim8.rb
- Formula/gz-sim9.rb
- Formula/gz-transport13.rb
- Formula/gz-transport14.rb
- Formula/ignition-common4.rb
- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch5.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-physics5.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
- Formula/sdformat12.rb
- Formula/sdformat14.rb
- Formula/sdformat15.rb
Part of https://github.com/osrf/homebrew-simulation/issues/2998.
Generated with:
~~~
for f in $(.github/ci/bottled_dependents.sh tinyxml2)
do
done
~~~
> Remove bottles broken by tinyxml2 11.0

- Formula/gz-gui10.rb
- Formula/gz-sim10.rb
Adds Qt6 dependency alongside of Qt5. Once the switch is made in the source repos (gz-sim, gz-gui), we can remove Qt5. 
Tested with https://github.com/gazebosim/gz-gui/pull/673
https://build.osrfoundation.org/job/gz_gui-ci-pr_any-homebrew-amd64/202/
[![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gz_gui-ci-pr_any-homebrew-amd64&build=202)](https://build.osrfoundation.org/job/gz_gui-ci-pr_any-homebrew-amd64/202/)
> gz-gui10 and gz-sim10: Add Qt6 dependency

- Aliases/gz-transport15
- Formula/gz-transport15.rb
Removed alias to gz-transport14 and added a new gz-transport15.rb formula
~~Added 2 new dependencies related to zenoh that comes from a thirdparty tap:~~
~~depends_on "eclipse-zenoh/homebrew-zenoh/libzenohcpp"~~
~~depends_on "eclipse-zenoh/homebrew-zenoh/libzenohc"~~
~~Related gz-transport PR: https://github.com/gazebosim/gz-transport/pull/600~~
> gz-transport15: new formula

- Aliases/gz-sensors10
- Formula/gz-gui10.rb
- Formula/gz-launch9.rb
- Formula/gz-sensors10.rb
- Formula/gz-sim10.rb
Part of https://github.com/gazebo-tooling/release-tools/issues/1292.
> gz-launch9: Bump gz-transport and others in jetty

- Formula/gz-launch9.rb
I removed the search for Qt packages in source code: https://github.com/gazebosim/gz-launch/pull/297 but given that homebrew bottle building may need transitive dependencies, I updated it to Qt6 here instead of removing the dependency.
> gz-launch9: Update to Qt6

- Formula/gz-common5.rb
- Formula/gz-common6.rb
- Formula/gz-fuel-tools10.rb
- Formula/gz-fuel-tools9.rb
- Formula/gz-gui8.rb
- Formula/gz-gui9.rb
- Formula/gz-launch7.rb
- Formula/gz-launch8.rb
- Formula/gz-physics7.rb
- Formula/gz-physics8.rb
- Formula/gz-rendering8.rb
- Formula/gz-rendering9.rb
- Formula/gz-sensors8.rb
- Formula/gz-sensors9.rb
- Formula/gz-sim8.rb
- Formula/gz-sim9.rb
Part of #3038.
~~~
for m in gz-common5 gz-common6
do
do
done
done
~~~
> Remove bottles broken by gdal 3.11.0

- Formula/ignition-transport8.rb
Part of gazebo-tooling/release-tools#1252. This was accidentally missed in #2950.
> ignition-transport8: add deprecation date

- Formula/ogre2.1.rb
Part of gazebo-tooling/release-tools#1252. Follow-up to #2950.
> ogre2.1: add deprecation date

- Formula/gz-sim10.rb
Related to https://github.com/gazebosim/gz-sim/pull/2849.
> gz-sim10: configure rpath for standalone execs

- Formula/gz-launch7.rb
- Formula/gz-launch8.rb
- Formula/gz-physics7.rb
- Formula/gz-physics8.rb
- Formula/gz-sensors8.rb
- Formula/gz-sensors9.rb
- Formula/gz-sim8.rb
- Formula/gz-sim9.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-launch5.rb
- Formula/ignition-physics5.rb
- Formula/ignition-sensors6.rb
- Formula/sdformat12.rb
- Formula/sdformat14.rb
- Formula/sdformat15.rb
Part of 3078. I've included what I think are the formulas corresponding to our support distributions.
I've used https://github.com/gazebo-tooling/gazebodistro/pull/208/files to generate the list of packages, mostly doing:
```bash
> cd /home/jrivero/code/gazebodistro && python3 tools/get_package_version.py \
--collection-files collection-fortress.yaml collection-harmonic.yaml collection-ionic.yaml collection-jetty.yaml \
--libs sdformat gz-sim gz-sensors gz-launch sdformat gz-physics
gz-launch7 gz-launch8 gz-launch9 gz-physics7 gz-physics8 gz-sensors10 gz-sensors8 gz-sensors9 gz-sim10 gz-sim8 gz-sim9 ignition-gazebo6 ignition-launch5 ignition-physics5 ignition-sensors6 sdformat12 sdformat14 sdformat15
```
There were some warnings about some Formulas that does not have a bottle block …
> Remove supported broken bottles by the urfdom5 release

- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch5.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-physics5.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
- Formula/sdformat12.rb
Part of #3078 and #3090.
Generated with:
~~~
for f in $(.github/ci/unbottled_dependencies.sh gz-fortress sonoma);
do
brew bump-revision --message="rebuild for abseil" $f;
done 
~~~
> Rebuild fortress bottles for abseil

- Formula/gz-fuel-tools10.rb
- Formula/gz-fuel-tools9.rb
- Formula/gz-gui8.rb
- Formula/gz-gui9.rb
- Formula/gz-launch7.rb
- Formula/gz-launch8.rb
- Formula/gz-msgs10.rb
- Formula/gz-msgs11.rb
- Formula/gz-msgs9.rb
- Formula/gz-sensors8.rb
- Formula/gz-sensors9.rb
- Formula/gz-sim8.rb
- Formula/gz-sim9.rb
- Formula/gz-transport13.rb
- Formula/gz-transport14.rb
- Formula/ignition-fuel-tools7.rb
- Formula/ignition-gazebo6.rb
- Formula/ignition-gui6.rb
- Formula/ignition-launch5.rb
- Formula/ignition-msgs5.rb
- Formula/ignition-msgs8.rb
- Formula/ignition-sensors6.rb
- Formula/ignition-transport11.rb
Part of #3094.
Implemented with
~~~
for m in gz-msgs5 gz-msgs8 gz-msgs9 gz-msgs10 gz-msgs11
do
brew bump-revision --remove-bottle-block --message="broken bottle" $m;
do
brew bump-revision --remove-bottle-block --message="broken bottle" $f;
done
done
~~~
> Remove bottles broken by abseil

- Formula/gz-gui9.rb
Part of https://github.com/osrf/homebrew-simulation/issues/3094, applies patch from https://github.com/gazebosim/gz-gui/pull/677 / https://github.com/gazebosim/gz-gui/commit/e1eb227411f605577c4eb6de2f4df627d72d1ade.
> gz-gui9: patch for protobuf 30

- Formula/ignition-msgs8.rb
Patch from gazebosim/gz-msgs#524.
> gz-msgs8: patch for protobuf 30

- Formula/gz-sim8.rb
Part of #3094. Patch from https://github.com/gazebosim/gz-sim/pull/3034.
> gz-sim8: patch for protobuf 30 compatibility

- Formula/gz-cmake5.rb
Part of https://github.com/gazebosim/gz-jetty/issues/19
> gz-cmake5: Use stable branch in url

- Formula/gz-msgs12.rb
Part of https://github.com/gazebosim/gz-jetty/issues/25
> gz-msgs12: use stable branch in url

- Formula/gz-gui10.rb
Part of https://github.com/gazebosim/gz-jetty/issues/32
> gz-gui10: Use stable branch in the url

- Formula/gz-physics9.rb
Part of https://github.com/gazebosim/gz-jetty/issues/29.
> gz-physics9: use stable branch in url

- Formula/boost@1.85.0.rb
- Formula/bullet@2.87.rb
- Formula/ogre1.9-with-boost1.85.rb
- Formula/tinyxml1.rb
These formulae are not used by any currently supported formulae, so deprecate them in a little over 1 month.
> Deprecate old versioned formulae on 2025-09-30

- Formula/gz-plugin4.rb
Related with https://github.com/gazebosim/gz-jetty/issues/23
> gz-plugin4: use stable branch in url

- Formula/gz-fuel-tools11.rb
Part of https://github.com/gazebosim/gz-jetty/issues/18
> gz-fuel-tools11: use stable branch in url

- Formula/gz-launch9.rb
Part of https://github.com/gazebosim/gz-jetty/issues/18
> gz-launch9: use stable branch in url

- Formula/gz-cmake4.rb
Need to make a minor change to files to build new bottles, so remove the `BUILD_TESTING` cmake arg since it's already set to `OFF` in [std_cmake_args](https://github.com/Homebrew/brew/blob/b352fff140b2e55bef2953f43bdfa5867adae6b6/Library/Homebrew/formula.rb#L1878).
> gz-cmake4: build arm64_sequoia bottle

- README.md
There are now separate bottle install jobs for amd64 and arm64. The current README badges are only for amd64; this labels them as such.
A follow-up will add arm64 labels and badges.
> README: add amd64 label to badges
